OSOS Dev: kheap.hpp File Reference
kheap.hpp File Reference
#include <cstdint>
#include <stddef.h>
Classes
class memory::HeapManager
struct memory::MemoryBlockHeader
Namespaces
namespace memory
Functions
void * calloc (size_t num, size_t size)
void free (void *ptr)
void * malloc (size_t size)
void operator delete (void *ptr) noexcept
void operator delete (void *ptr, size_t size) noexcept
void operator delete[] (void *ptr) noexcept
void operator delete[] (void *ptr, size_t size) noexcept
void * operator new (size_t size)
void * operator new[] (size_t size)
void * realloc (void *ptr, size_t new_size)
Class Documentation
memory::MemoryBlockHeader
struct memory::MemoryBlockHeader
Definition at line 9 of file kheap.hpp.
Class Members
bool is_free
MemoryBlockHeader * next
MemoryBlockHeader * prev
size_t size
Function Documentation
calloc()
void * calloc (size_t num, size_t size)
Definition at line 103 of file kheap.cpp.
{
        size_t total = num * size;
        void* ptr = malloc(total);
        if (ptr) {
            uint8_t* p = (uint8_t*)ptr;
            for (size_t i = 0; i < total; i++) {
                p[i] = 0;
            }
        }
        return ptr;
    }
References malloc().
free()
void free (void * ptr)
Definition at line 99 of file kheap.cpp.
{
        memory::kernel_heap.free(ptr);
    }
References memory::HeapManager::free(), and memory::kernel_heap.
Referenced by realloc().
malloc()
void * malloc (size_t size)
Definition at line 95 of file kheap.cpp.
{
        return memory::kernel_heap.allocate(size);
    }
References memory::HeapManager::allocate(), and memory::kernel_heap.
Referenced by calloc(), and realloc().
operator delete() [1/2]
void operator delete (void * ptr) noexcept
Definition at line 151 of file kheap.cpp.
{
    memory::kernel_heap.free(ptr);
}
References memory::HeapManager::free(), and memory::kernel_heap.
operator delete() [2/2]
void operator delete (void * ptr, size_t size) noexcept
Definition at line 159 of file kheap.cpp.
{
    (void)size;
    memory::kernel_heap.free(ptr);
}
References memory::HeapManager::free(), and memory::kernel_heap.
operator delete[]() [1/2]
void operator delete[] (void * ptr) noexcept
Definition at line 155 of file kheap.cpp.
{
    memory::kernel_heap.free(ptr);
}
References memory::HeapManager::free(), and memory::kernel_heap.
operator delete[]() [2/2]
void operator delete[] (void * ptr, size_t size) noexcept
Definition at line 164 of file kheap.cpp.
{
    (void)size;
    memory::kernel_heap.free(ptr);
}
References memory::HeapManager::free(), and memory::kernel_heap.
operator new()
void * operator new (size_t size)
Definition at line 143 of file kheap.cpp.
{
    return memory::kernel_heap.allocate(size);
}
References memory::HeapManager::allocate(), and memory::kernel_heap.
operator new[]()
void * operator new[] (size_t size)
Definition at line 147 of file kheap.cpp.
{
    return memory::kernel_heap.allocate(size);
}
References memory::HeapManager::allocate(), and memory::kernel_heap.
realloc()
void * realloc (void * ptr, size_t new_size)
Definition at line 115 of file kheap.cpp.
{
        if (!ptr) return malloc(new_size);
        if (new_size == 0) {
            free(ptr);
            return nullptr;
        }
        memory::MemoryBlockHeader* header = (memory::MemoryBlockHeader*)((uintptr_t)ptr - sizeof(memory::MemoryBlockHeader));
        size_t old_size = header->size;
        // Allocate new block
        void* new_ptr = malloc(new_size);
        if (!new_ptr) return nullptr;
        // Copy data (Manual memcpy)
        size_t copy_size = (old_size < new_size) ? old_size : new_size;
        uint8_t* src = (uint8_t*)ptr;
        uint8_t* dst = (uint8_t*)new_ptr;
        for (size_t i = 0; i < copy_size; i++) {
            dst[i] = src[i];
        }
        free(ptr);
        return new_ptr;
    }
References free(), malloc(), and memory::MemoryBlockHeader::size.