OSOS Dev: net::EtherFrameProvider
net::EtherFrameProvider
#include "ketherframe.hpp"
Public Member Functions
EtherFrameProvider (driver::amd_am79c973 *backend)
~EtherFrameProvider ()
uint32_t getIPAddress ()
uint64_t getMACAddress ()
bool onRawDataReceived (uint8_t *buffer, uint32_t size)
void send (uint64_t dstMAC_BE, uint16_t etherType_BE, uint8_t *buffer, uint32_t size)
void send (uint8_t *buffer, uint32_t size)
Protected Attributes
amd_am79c973 * backend
EtherFrameHandler * handlers [65535]
Detailed Description
Definition at line 38 of file ketherframe.hpp.
Constructor & Destructor Documentation
EtherFrameProvider()
EtherFrameProvider::EtherFrameProvider (driver::amd_am79c973 * backend)
Definition at line 44 of file ketherframe.cpp.
: RawDataHandler(backend)
{
    for(uint32_t i = 0; i < 65535; i++)
        handlers[i] = 0;
}
References handlers.
~EtherFrameProvider()
EtherFrameProvider::~EtherFrameProvider ()
Definition at line 51 of file ketherframe.cpp.
{
}
Member Function Documentation
getIPAddress()
uint32_t EtherFrameProvider::getIPAddress ()
Definition at line 98 of file ketherframe.cpp.
{
    return backend->getIPAddress();
}
References driver::RawDataHandler::backend, and driver::amd_am79c973::getIPAddress().
Referenced by net::EtherFrameHandler::getIPAddress().
getMACAddress()
uint64_t EtherFrameProvider::getMACAddress ()
Definition at line 103 of file ketherframe.cpp.
{
    return backend->getMACAddress();
}
References driver::RawDataHandler::backend, and driver::amd_am79c973::getMACAddress().
onRawDataReceived()
bool EtherFrameProvider::onRawDataReceived (uint8_t * buffer, uint32_t size) virtual
Reimplemented from driver::RawDataHandler.
Definition at line 55 of file ketherframe.cpp.
{
    if(size < sizeof(EtherFrameHeader))
        return false;
    EtherFrameHeader* frame = (EtherFrameHeader*)buffer;
    bool sendBack = false;
    if(frame->dstMAC_BE == 0xFFFFFFFFFFFF
    || frame->dstMAC_BE == backend->getMACAddress())
    {
        if(handlers[frame->etherType_BE] != 0)
            sendBack = handlers[frame->etherType_BE]->onEtherFrameReceived(
                buffer + sizeof(EtherFrameHeader), size - sizeof(EtherFrameHeader));
    }
    if(sendBack)
    {
        frame->dstMAC_BE = frame->srcMAC_BE;
        frame->srcMAC_BE = backend->getMACAddress();
    }
    return sendBack;
}
References driver::RawDataHandler::backend, net::EtherFrameHeader::dstMAC_BE, net::EtherFrameHeader::etherType_BE, driver::amd_am79c973::getMACAddress(), handlers, net::EtherFrameHandler::onEtherFrameReceived(), size, and net::EtherFrameHeader::srcMAC_BE.
send() [1/2]
void EtherFrameProvider::send (uint64_t dstMAC_BE, uint16_t etherType_BE, uint8_t * buffer, uint32_t size)
Definition at line 80 of file ketherframe.cpp.
{
    uint8_t* buffer2 = (uint8_t*)malloc(sizeof(EtherFrameHeader) + size);
    EtherFrameHeader* frame = (EtherFrameHeader*)buffer2;
    frame->dstMAC_BE = dstMAC_BE;
    frame->srcMAC_BE = backend->getMACAddress();
    frame->etherType_BE = etherType_BE;
    uint8_t* src = buffer;
    uint8_t* dst = buffer2 + sizeof(EtherFrameHeader);
    for(uint32_t i = 0; i < size; i++)
        dst[i] = src[i];
    backend->send(buffer2, size + sizeof(EtherFrameHeader));
    free(buffer2);
}
References driver::RawDataHandler::backend, dstMAC_BE, net::EtherFrameHeader::dstMAC_BE, etherType_BE, net::EtherFrameHeader::etherType_BE, free(), driver::amd_am79c973::getMACAddress(), malloc(), driver::amd_am79c973::send(), size, and net::EtherFrameHeader::srcMAC_BE.
Referenced by net::EtherFrameHandler::send().
send() [2/2]
void RawDataHandler::send (uint8_t * buffer, uint32_t size) inherited
Definition at line 27 of file kamd79c973.cpp.
{
    backend->send(buffer, size);
}
References driver::RawDataHandler::backend, driver::amd_am79c973::send(), and size.
Member Data Documentation
backend
amd_am79c973* driver::RawDataHandler::backend protected inherited
Definition at line 17 of file kamd79c973.hpp.
Referenced by driver::RawDataHandler::RawDataHandler(), driver::RawDataHandler::~RawDataHandler(), getIPAddress(), getMACAddress(), onRawDataReceived(), send(), and driver::RawDataHandler::send().
handlers
EtherFrameHandler* net::EtherFrameProvider::handlers[65535] protected
Definition at line 42 of file ketherframe.hpp.
Referenced by net::EtherFrameHandler::EtherFrameHandler(), EtherFrameProvider(), net::EtherFrameHandler::~EtherFrameHandler(), and onRawDataReceived().
The documentation for this class was generated from the following files:
ketherframe.hpp
ketherframe.cpp