OSOS - Documentation: essential::GDT
essential::GDT
Manages the Global Descriptor Table (GDT), holding segment descriptors for the CPU.
#include "kgdt.hpp"
Public Member Functions
GDT ()
~GDT ()
void installTable ()
Static Public Member Functions
static uint16_t kernel_CS_selector ()
static uint16_t kernel_DS_selector ()
static void printLoadedTable ()
static void printLoadedTableHeader ()
static uint16_t user_CS_selector ()
static uint16_t user_DS_selector ()
Private Attributes
uintptr_t base
GDT_row kernel_CS
GDT_row kernel_DS
uint16_t limit
GDT_row nullSegment
GDT_row user_CS
GDT_row user_DS
Detailed Description
Manages the Global Descriptor Table (GDT), holding segment descriptors for the CPU.
Definition at line 53 of file kgdt.hpp.
Constructor & Destructor Documentation
GDT()
essential::GDT::GDT ()
~GDT()
essential::GDT::~GDT ()
Member Function Documentation
installTable()
void essential::GDT::installTable ()
Referenced by kernelMain().
kernel_CS_selector()
static uint16_t essential::GDT::kernel_CS_selector () static
Referenced by hardware_communication::InterruptManager::InterruptManager().
kernel_DS_selector()
static uint16_t essential::GDT::kernel_DS_selector () static
printLoadedTable()
static void essential::GDT::printLoadedTable () static
printLoadedTableHeader()
static void essential::GDT::printLoadedTableHeader () static
Referenced by kernelMain().
user_CS_selector()
static uint16_t essential::GDT::user_CS_selector () static
user_DS_selector()
static uint16_t essential::GDT::user_DS_selector () static
Member Data Documentation
base
uintptr_t essential::GDT::base private
Definition at line 56 of file kgdt.hpp.
kernel_CS
GDT_row essential::GDT::kernel_CS private
Definition at line 58 of file kgdt.hpp.
kernel_DS
GDT_row essential::GDT::kernel_DS private
Definition at line 59 of file kgdt.hpp.
limit
uint16_t essential::GDT::limit private
Definition at line 55 of file kgdt.hpp.
nullSegment
GDT_row essential::GDT::nullSegment private
Definition at line 57 of file kgdt.hpp.
user_CS
GDT_row essential::GDT::user_CS private
Definition at line 60 of file kgdt.hpp.
user_DS
GDT_row essential::GDT::user_DS private
Definition at line 61 of file kgdt.hpp.
The documentation for this class was generated from the following file:
/home/shreekar/Desktop/Building_own_OS/OSOS/libk_header/essential/kgdt.hpp