OSOS - Documentation: essential::GDT_Manager
essential::GDT_Manager
Manages the Global Descriptor Table (GDT), holding segment descriptors for the CPU.
#include "kgdt.hpp"
Public Member Functions
GDT_Manager ()
Constructs a new GDT_Manager object and initializes the standard kernel/user segments.
~GDT_Manager ()
Destroys the GDT_Manager object.
void installTable ()
Loads this GDT into the CPU's GDTR and reloads all segment registers.
Static Public Member Functions
static uint16_t kernel_CS_selector ()
(Static) Gets the kernel code segment selector.
static uint16_t kernel_DS_selector ()
(Static) Gets the kernel data segment selector.
static void printLoadedTable ()
(Static) Prints the details of all entries in the currently loaded GDT.
static void printLoadedTableHeader ()
(Static) Prints the header information (base, limit, count) of the currently loaded GDT.
static uint16_t user_CS_selector ()
(Static) Gets the user code segment selector.
static uint16_t user_DS_selector ()
(Static) Gets the user data segment selector.
Private Attributes
uintptr_t base
GDT_Row kernel_CS
GDT_Row kernel_DS
uint16_t limit
GDT_Row nullSegment
GDT_Row user_CS
GDT_Row user_DS
Detailed Description
Manages the Global Descriptor Table (GDT), holding segment descriptors for the CPU.
Definition at line 53 of file kgdt.hpp.
Constructor & Destructor Documentation
GDT_Manager()
essential::GDT_Manager::GDT_Manager ()
Constructs a new GDT_Manager object and initializes the standard kernel/user segments.
Definition at line 30 of file kgdt.cpp.
    : nullSegment(), // First entry must be a null descriptor.
      kernel_CS(0, 0xFFFFFFFF, GDT_ACCESS_CODE_PL0, GDT_GRAN_FLAGS),
      kernel_DS(0, 0xFFFFFFFF, GDT_ACCESS_DATA_PL0, GDT_GRAN_FLAGS),
      user_CS(0, 0xFFFFFFFF, GDT_ACCESS_CODE_PL3, GDT_GRAN_FLAGS),
      user_DS(0, 0xFFFFFFFF, GDT_ACCESS_DATA_PL3, GDT_GRAN_FLAGS)
{
    // The GDT limit is its total size in bytes minus 1.
    // 5 entries * 8 bytes/entry = 40 bytes. Limit = 39 (0x27).
    limit = (sizeof(essential::GDT_Row) * 5) - 1;
    // The base address is the address of the first entry in our table.
    base = (uintptr_t)&this->nullSegment;
}
References base, limit, and nullSegment.
~GDT_Manager()
essential::GDT_Manager::~GDT_Manager ()
Destroys the GDT_Manager object.
Definition at line 47 of file kgdt.cpp.
{}
Member Function Documentation
installTable()
void essential::GDT_Manager::installTable ()
Loads this GDT into the CPU's GDTR and reloads all segment registers.
Definition at line 51 of file kgdt.cpp.
{
    // A structure that matches the 6-byte format required by the 'lgdt' instruction.
    struct GDT_Pointer {
        uint16_t limit;
        uint32_t base; // Use uint32_t for our i686 (32-bit) target
    } __attribute__((packed));
    GDT_Pointer gdt_ptr;
    gdt_ptr.limit = this->limit;
    gdt_ptr.base = this->base;
    asm volatile(
        // Load the address of our GDT_Pointer structure into the GDTR.
        "lgdt (%0)\n\t"
        // Reload all data segment registers with the kernel data selector.
        "mov $0x10, %%ax\n\t"   // 0x10 is the selector for kernel_DS
        "mov %%ax, %%ds\n\t"
        "mov %%ax, %%es\n\t"
        "mov %%ax, %%fs\n\t"
        "mov %%ax, %%gs\n\t"
        "mov %%ax, %%ss\n\t"
        // Perform a 32-bit far jump to reload the CS register and flush the CPU pipeline.
        "jmp $0x08, $flush_cs\n\t" // 0x08 is the selector for kernel_CS
        "flush_cs:\n\t"
        : // No output operands
        : "r"(&gdt_ptr) // Input: address of our GDT_Pointer
        : "memory", "eax" // Clobbered registers
    );
    basic::printf("GDT Installed\n");
}
References __attribute__, base, limit, and basic::printf().
Referenced by kernelMain().
kernel_CS_selector()
uint16_t essential::GDT_Manager::kernel_CS_selector () static
(Static) Gets the kernel code segment selector.
Returns
The 16-bit selector value.
Definition at line 146 of file kgdt.cpp.
{ return sizeof(essential::GDT_Row) * 1; } // Selector 0x08
Referenced by hardware_communication::InterruptManager::InterruptManager().
kernel_DS_selector()
uint16_t essential::GDT_Manager::kernel_DS_selector () static
(Static) Gets the kernel data segment selector.
Returns
The 16-bit selector value.
Definition at line 149 of file kgdt.cpp.
{ return sizeof(essential::GDT_Row) * 2; } // Selector 0x10
printLoadedTable()
void essential::GDT_Manager::printLoadedTable () static
(Static) Prints the details of all entries in the currently loaded GDT.
Definition at line 85 of file kgdt.cpp.
{
    struct GDT_Pointer {
        uint16_t limit;
        uint32_t base;
    } __attribute__((packed));
    GDT_Pointer gdtr;
    // Store the current GDT register contents into our struct.
    asm volatile("sgdt %0" : "=m"(gdtr));
    basic::printf("---\n");
    basic::printf("INFO about : Currently Loaded GDT\n");
    basic::printf("Base Address: %#x\n", gdtr.base);
    basic::printf("Limit: %#x (%d bytes)\n", gdtr.limit, gdtr.limit);
    basic::printf("Entries: %d\n", (gdtr.limit + 1) / sizeof(essential::GDT_Row));
    basic::printf("---\n");
    essential::GDT_Row* gdt_entries = (essential::GDT_Row*)gdtr.base;
    int num_entries = (gdtr.limit + 1) / sizeof(essential::GDT_Row);
    for (int i = 0; i < num_entries; i++) {
        essential::GDT_Row entry = gdt_entries[i];
        // Reconstruct the base and limit from the scattered fields.
        uint32_t base = entry.base_high << 24 | entry.base_middle << 16 | entry.base_low;
        uint32_t limit = (entry.granularity & 0x0F) << 16 | entry.limit_low;
        // If the granularity bit is set, the limit is in 4 KiB pages.
        if ((entry.granularity & 0x80) != 0) {
            limit = (limit << 12) | 0xFFF;
        }
        basic::printf("GDT Entry %d: Base=%p, Limit=%#x, Access=%#x, Granularity=%#x\n",
               i, (void*)(uintptr_t)base, limit, entry.access, entry.granularity);
    }
    basic::printf("---\n");
}
References __attribute__, essential::GDT_Row::access, base, essential::GDT_Row::base_high, essential::GDT_Row::base_low, essential::GDT_Row::base_middle, essential::GDT_Row::granularity, limit, essential::GDT_Row::limit_low, and basic::printf().
printLoadedTableHeader()
void essential::GDT_Manager::printLoadedTableHeader () static
(Static) Prints the header information (base, limit, count) of the currently loaded GDT.
Definition at line 124 of file kgdt.cpp.
{
    struct GDT_Pointer {
        uint16_t limit;
        uint32_t base;
    } __attribute__((packed));
    GDT_Pointer gdtr;
    // Store the current GDT register contents into our struct.
    asm volatile("sgdt %0" : "=m"(gdtr));
    basic::printf("---\n");
    basic::printf("INFO about : Currently Loaded GDT\n");
    basic::printf("Base Address: %#x\n", gdtr.base);
    basic::printf("Limit: %#x (%d bytes)\n", gdtr.limit, gdtr.limit);
    basic::printf("Entries: %d\n", (gdtr.limit + 1) / sizeof(essential::GDT_Row));
    basic::printf("---\n");
}
References __attribute__, base, limit, and basic::printf().
Referenced by kernelMain().
user_CS_selector()
uint16_t essential::GDT_Manager::user_CS_selector () static
(Static) Gets the user code segment selector.
Returns
The 16-bit selector value.
Definition at line 152 of file kgdt.cpp.
{ return sizeof(essential::GDT_Row) * 3; } // Selector 0x18
user_DS_selector()
uint16_t essential::GDT_Manager::user_DS_selector () static
(Static) Gets the user data segment selector.
Returns
The 16-bit selector value.
Definition at line 155 of file kgdt.cpp.
{ return sizeof(essential::GDT_Row) * 4; }
Member Data Documentation
base
uintptr_t essential::GDT_Manager::base private
Definition at line 56 of file kgdt.hpp.
Referenced by GDT_Manager().
kernel_CS
GDT_Row essential::GDT_Manager::kernel_CS private
Definition at line 58 of file kgdt.hpp.
kernel_DS
GDT_Row essential::GDT_Manager::kernel_DS private
Definition at line 59 of file kgdt.hpp.
limit
uint16_t essential::GDT_Manager::limit private
Definition at line 55 of file kgdt.hpp.
Referenced by GDT_Manager().
nullSegment
GDT_Row essential::GDT_Manager::nullSegment private
Definition at line 57 of file kgdt.hpp.
Referenced by GDT_Manager().
user_CS
GDT_Row essential::GDT_Manager::user_CS private
Definition at line 60 of file kgdt.hpp.
user_DS
GDT_Row essential::GDT_Manager::user_DS private
Definition at line 61 of file kgdt.hpp.
The documentation for this class was generated from the following files:
/home/shreekar/Desktop/Building_own_OS/OSOS/libk_header/essential/kgdt.hpp
/home/shreekar/Desktop/Building_own_OS/OSOS/libk_src/essential/kgdt.cpp