OSOS Dev: basic Namespace Reference
basic Namespace Reference
Functions
void __printMemoryMap (multiboot_info_t *mbi)
Prints the system memory map provided by the Multiboot bootloader.
void clearScreen ()
Clears the entire text mode screen and resets the cursor to (0,0).
void disable_cursor ()
Disables the text mode cursor.
static void doubleToString (double d, char *buffer, int precision)
Converts a double-precision floating point number to a string.
void enable_cursor (uint8_t cursor_start, uint8_t cursor_end)
Enables the text mode cursor and sets its shape.
static bool is_serial_ready ()
Checks if the serial port's transmit buffer is empty (COM1).
void * memcpy (void *dest, const void *src, int num)
Copies 'num' bytes from source memory to destination memory.
void * memset (void *ptr, int value, int num)
Fills a block of memory with a specific value.
static double power (double base, int exp)
Calculates the power of a number.
static void printCharStr (const char *str)
Internal function to print a null-terminated string to video memory AND serial.
int printf (const char *format,...)
A custom implementation of the standard printf function for writing to both VGA text mode memory and the COM1 serial port.
static void printHex (uintptr_t n, int digits)
Prints a hexadecimal number with leading zeros.
static void reverse (char *str, int length)
Reverses a string in place.
char * strcat (char *dest, const char *src)
Appends the source string to the end of the destination string.
int strcmp (const char *s1, const char *s2)
Compares two strings lexicographically.
char * strcpy (char *dest, const char *src)
Copies the source string to the destination buffer.
int strlen (const char *str)
Calculates the length of a null-terminated string.
int strncmp (const char *s1, const char *s2, int n)
Compares up to 'n' characters of two strings.
static void ullToString (unsigned long long n, char *buffer, int base, int is_signed, int uppercase)
Converts an unsigned long long integer to a string.
void update_cursor (int x, int y)
Updates the position of the text mode cursor.
static void write_serial_char (char c)
Writes a single character to the COM1 serial port.
Variables
static int cursor_x_ = 0
static int cursor_y_ = 0
static Port8Bit vgaDataPort (0x3D5)
static Port8Bit vgaIndexPort (0x3D4)
Function Documentation
__printMemoryMap()
void basic::__printMemoryMap (multiboot_info_t * mbi)
Prints the system memory map provided by the Multiboot bootloader.
Parameters
mbi Pointer to the Multiboot information structure.
Definition at line 7 of file kmemory.cpp.
{
    // Check if the memory map flag is set (bit 6)
    if (!(mbi->flags & (1 << 6))) {
        printf("\nError: Memory map not provided by bootloader.\n");
        return;
    }
    printf("\n--- System Memory Map ---\n");
    // Use uint64_t to correctly accumulate total memory size
    uint64_t total_available_bytes = 0;
    // Use uintptr_t for pointer arithmetic to ensure portability
    uintptr_t mmap_start = mbi->mmap_addr;
    uintptr_t mmap_end = mbi->mmap_addr + mbi->mmap_length;
    for (multiboot_memory_map_t *mmap = (multiboot_memory_map_t *)mmap_start;
        (uintptr_t)mmap < mmap_end;
        mmap = (multiboot_memory_map_t *)((uintptr_t)mmap + mmap->size + sizeof(mmap->size)))
    {
        const char *type_str;
        switch (mmap->type)
        {
        case MULTIBOOT_MEMORY_AVAILABLE:
            type_str = "Available";
            total_available_bytes += mmap->len;
            break;
        case MULTIBOOT_MEMORY_RESERVED:
            type_str = "Reserved";
            break;
        case MULTIBOOT_MEMORY_ACPI_RECLAIMABLE:
            type_str = "ACPI Reclaimable";
            break;
        case MULTIBOOT_MEMORY_NVS:
            type_str = "NVS";
            break;
        case MULTIBOOT_MEMORY_BADRAM:
            type_str = "Bad RAM";
            break;
        default:
            type_str = "Unknown";
            break;
        }
        // Use %#llx for 64-bit hex values (address and length)
        printf("Addr: %#llx | Len: %.2fKB | Type: %s\n", mmap->addr, mmap->len/1024.0, type_str);
    }
    // Use floating point for the final calculation and display
    double total_mb = total_available_bytes / 1024.0;
    printf("Total available memory: %.2f KB\n\n", total_mb);
}
References printf().
clearScreen()
void basic::clearScreen ()
Clears the entire text mode screen and resets the cursor to (0,0).
Definition at line 156 of file kiostream.cpp.
{
    unsigned short *video_memory = (unsigned short *)0xb8000;
    unsigned short blank = (0x07 << 8) | ' ';
    int screenSize = MAGIC_WIDTH * MAGIC_HEIGHT;
    // This part is correct for clearing the VGA screen
    for (int i = 0; i < screenSize; i++)
    {
        video_memory[i] = blank;
    }
    cursor_x_ = 0;
    cursor_y_ = 0;
    update_cursor(cursor_x_, cursor_y_);
    // ANSI escape sequence to clear the serial terminal
    // \e[2J = Clear entire screen
    // \e[H  = Move cursor to home (top-left)
    const char* clear_sequence = "\e[2J\e[H";
    for (int i = 0; clear_sequence[i] != '\0'; i++)
    {
        write_serial_char(clear_sequence[i]);
    }
}
References cursor_x_, cursor_y_, MAGIC_HEIGHT, MAGIC_WIDTH, update_cursor(), and write_serial_char().
Referenced by kernelMain().
disable_cursor()
void basic::disable_cursor ()
Disables the text mode cursor.
Definition at line 68 of file kiostream.cpp.
{
    vgaIndexPort.write(0x0A);
    vgaDataPort.write(0x20);
}
References vgaDataPort, vgaIndexPort, and hardware_communication::Port8Bit::write().
Referenced by kernelMain().
doubleToString()
static void basic::doubleToString (double d, char * buffer, int precision) static
Converts a double-precision floating point number to a string.
Parameters
d The double to convert.
buffer The output buffer to store the string.
precision The number of digits after the decimal point.
Definition at line 255 of file kiostream.cpp.
{
    if (precision < 0)
        precision = 6;
    char *ptr = buffer;
    if (d < 0)
    {
        *ptr++ = '-';
        d = -d;
    }
    unsigned long long int_part = (unsigned long long)d;
    double frac_part = d - (double)int_part;
    ullToString(int_part, ptr, 10, 0, 0);
    while (*ptr) ptr++;
    *ptr++ = '.';
    unsigned long long frac_as_ull = (unsigned long long)(frac_part * power(10, precision) + 0.5);
    char frac_buffer[32];
    ullToString(frac_as_ull, frac_buffer, 10, 0, 0);
    int frac_len = 0;
    while(frac_buffer[frac_len] != '\0') frac_len++;
    int padding = precision - frac_len;
    for (int i = 0; i < padding; i++)
        *ptr++ = '0';
    char* frac_ptr = frac_buffer;
    while(*frac_ptr) *ptr++ = *frac_ptr++;
    *ptr = '\0';
}
References power(), and ullToString().
Referenced by printf().
enable_cursor()
void basic::enable_cursor (uint8_t cursor_start, uint8_t cursor_end)
Enables the text mode cursor and sets its shape.
Parameters
cursor_start The starting scanline for the cursor block.
cursor_end The ending scanline for the cursor block.
Definition at line 46 of file kiostream.cpp.
{
    vgaIndexPort.write(0x0A);
    vgaDataPort.write((vgaDataPort.read() & 0xC0) | cursor_start);
    vgaIndexPort.write(0x0B);
    vgaDataPort.write((vgaDataPort.read() & 0xE0) | cursor_end);
}
References hardware_communication::Port8Bit::read(), vgaDataPort, vgaIndexPort, and hardware_communication::Port8Bit::write().
Referenced by kernelMain().
is_serial_ready()
static bool basic::is_serial_ready () static
Checks if the serial port's transmit buffer is empty (COM1).
Definition at line 22 of file kiostream.cpp.
{
    // Check 6th bit (0x20) of Line Status Port (0x3FD)
    Port8Bit lineStatusPort(0x3FD);
    return (lineStatusPort.read() & 0x20); // 0x20 = (1 << 5)
}
References hardware_communication::Port8Bit::read().
Referenced by write_serial_char().
memcpy()
void * basic::memcpy (void * dest, const void * src, int num)
Copies 'num' bytes from source memory to destination memory.
Parameters
dest Pointer to the destination memory.
src Pointer to the source memory.
num Number of bytes to copy.
Returns
A pointer to the destination.
Definition at line 58 of file kstring.cpp.
    {
        char* d = (char*)dest;
        const char* s = (const char*)src;
        while (num--) {
            *d++ = *s++;
        }
        return dest;
    }
memset()
void * basic::memset (void * ptr, int value, int num)
Fills a block of memory with a specific value.
Parameters
ptr Pointer to the block of memory to fill.
value The value to be set.
num Number of bytes to be set to the value.
Returns
A pointer to the block of memory.
Definition at line 49 of file kstring.cpp.
    {
        unsigned char* p = (unsigned char*)ptr;
        while (num--) {
            *p++ = (unsigned char)value;
        }
        return ptr;
    }
power()
static double basic::power (double base, int exp) static
Calculates the power of a number.
Parameters
base The base.
exp The exponent.
Returns
The result of base raised to the power of exp.
Definition at line 243 of file kiostream.cpp.
{
    double res = 1.0;
    for (int i = 0; i < exp; ++i)
        res *= base;
    return res;
}
References base.
Referenced by doubleToString().
printCharStr()
static void basic::printCharStr (const char * str) static
Internal function to print a null-terminated string to video memory AND serial.
Parameters
str The string to print.
Definition at line 77 of file kiostream.cpp.
{
    uint16_t *video_memory = (uint16_t *)0xb8000;
    // FOR TEXT : Attribute for Gray-White (0x7) text on a Black (0x0) background (last 2 bytes (LSBs) are not used for color).
    const uint16_t color_attribute = 0x0700;
    // remove mouse pointer
    int mouse_offset = driver::MouseDriver::__mouse_y_ * MAGIC_WIDTH + driver::MouseDriver::__mouse_x_;
    if(mouse_offset>=0) video_memory[mouse_offset] = driver::MouseDriver::old_char_under_mouse_pointer;
    for (int i = 0; str[i] != '\0'; i++)
    {
        write_serial_char(str[i]);
        if (str[i] == '\n')
        {
            cursor_y_++;
            cursor_x_ = 0;
        }
        else if (str[i] == '\b')
        {
            if (cursor_x_ > 0)
            {
                cursor_x_--;
                int offset = cursor_y_ * MAGIC_WIDTH + cursor_x_;
                video_memory[offset] = color_attribute | ' ';
            }
        }
        else if (str[i] == '\r')
        {
            cursor_x_ = 0;
        }
        else if (str[i] == '\t')
        {
            cursor_x_ = cursor_x_ + (TAB_WIDTH - (cursor_x_ % TAB_WIDTH));
        }
        else
        {
            int offset = cursor_y_ * MAGIC_WIDTH + cursor_x_;
            video_memory[offset] = color_attribute | str[i];
            cursor_x_++;
        }
        if (cursor_x_ >= MAGIC_WIDTH)
        {
            cursor_y_++;
            cursor_x_ = 0;
        }
        if (cursor_y_ >= MAGIC_HEIGHT)
        {
            for (int y = 0; y < (MAGIC_HEIGHT - 1); y++)
            {
                for (int x = 0; x < MAGIC_WIDTH; x++)
                {
                    int current_offset = y * MAGIC_WIDTH + x;
                    int next_line_offset = (y + 1) * MAGIC_WIDTH + x;
                    video_memory[current_offset] = video_memory[next_line_offset];
                }
            }
            int last_line_offset_start = (MAGIC_HEIGHT - 1) * MAGIC_WIDTH;
            for (int x = 0; x < MAGIC_WIDTH; x++)
            {
                video_memory[last_line_offset_start + x] = color_attribute | ' ';
            }
            cursor_y_ = MAGIC_HEIGHT - 1;
            cursor_x_ = 0;
        }
    }
    // add mouse pointer again
    driver::MouseDriver::old_char_under_mouse_pointer = video_memory[mouse_offset];
    if(mouse_offset>=0) video_memory[mouse_offset] = driver::MouseDriver::mouse_block_video_mem_value(driver::MouseDriver::old_char_under_mouse_pointer, MOUSE_POINTER_COLOR);
}
References driver::MouseDriver::__mouse_x_, driver::MouseDriver::__mouse_y_, cursor_x_, cursor_y_, MAGIC_HEIGHT, MAGIC_WIDTH, driver::MouseDriver::mouse_block_video_mem_value(), MOUSE_POINTER_COLOR, driver::MouseDriver::old_char_under_mouse_pointer, TAB_WIDTH, and write_serial_char().
Referenced by printf(), and printHex().
printf()
int basic::printf (const char * format, ...)
A custom implementation of the standard printf function for writing to both VGA text mode memory and the COM1 serial port.
This function formats a string and prints it to the screen and serial console, handling various format specifiers, flags, width, precision, and length modifiers. It returns the total number of characters written.
Parameters
format The null-terminated format string.
... Variable arguments corresponding to the format specifiers in the format string.
Returns
The total number of characters written (to both screen and serial).
This function internally uses printCharStr, which routes every character to both the VGA buffer (0xb8000) and the serial port (COM1, 0x3F8) simultaneously.
Supported Format Specifiers:
c - Character
s - String
d, i - Signed decimal integer
u - Unsigned decimal integer
f - Floating point number (double)
x - Unsigned hexadecimal integer (lowercase)
X - Unsigned hexadecimal integer (uppercase)
b - Unsigned binary integer
o - Unsigned octal integer
p - Pointer address (formats as 0x prefixed hex)
%% - A literal '' character
Supported Flags:
'#' - Alternative form (e.g., 0x for hex, 0b for binary, 0 for octal).
'0' - Zero-padding for width (ignored if precision is specified or '-' flag is used).
Supported Width:
A number after '' specifies the minimum field width (e.g., %10d). Padded with spaces by default, or zeros if '0' flag is used.
Supported Precision:
A period followed by a number (e.g., %.4f, %.8X).
For floats: specifies the number of digits after the decimal point.
For integers: specifies the minimum number of digits to print (padded with leading zeros).
Supported Length Modifiers:
h - short (for d, i, u, x, X, o, b)
hh - char (for d, i, u, x, X, o, b)
l - long (for d, i, u, x, X, o, b)
ll - long long (for d, i, u, x, X, o, b)
Definition at line 313 of file kiostream.cpp.
{
    int chars_written = 0;
    va_list args;
    va_start(args, format);
    char buffer[128];
    char char_str[2] = {0, 0};
    for (int i = 0; format[i] != '\0'; i++)
    {
        if (format[i] == '%')
        {
            i++;
            int use_alternative_form = 0;
            int zero_pad = 0;
            int width = 0;
            int precision = -1;
            // Flags
            if (format[i] == '#') {
                use_alternative_form = 1;
                i++;
            }
            if (format[i] == '0') {
                zero_pad = 1;
                i++;
            }
            // Width
            while (format[i] >= '0' && format[i] <= '9') {
                width = width * 10 + (format[i] - '0');
                i++;
            }
            // Precision
            if (format[i] == '.') {
                i++;
                precision = 0;
                while (format[i] >= '0' && format[i] <= '9') {
                    precision = precision * 10 + (format[i] - '0');
                    i++;
                }
                zero_pad = 0;
            }
            // Length Modifiers
            int is_long = 0, is_long_long = 0, is_short = 0, is_char = 0;
            if (format[i] == 'l') {
                is_long = 1; i++;
                if (format[i] == 'l') { is_long_long = 1; is_long = 0; i++; }
            } else if (format[i] == 'h') {
                is_short = 1; i++;
                if (format[i] == 'h') { is_char = 1; is_short = 0; i++; }
            }
            // Handle Specifiers
            switch (format[i])
            {
                case 'c':
                    char_str[0] = (char)va_arg(args, int);
                    printCharStr(char_str);
                    chars_written++;
                    break;
                case 's':
                {
                    const char *str = va_arg(args, char *);
                    if (!str) {
                        str = "(null)";
                    }
                    int len = 0;
                    while (str[len]) {
                        len++;
                    }
                    printCharStr(str);
                    chars_written += len;
                    break;
                }
                case 'f':
                {
                    doubleToString(va_arg(args, double), buffer, precision);
                    int len = 0;
                    while(buffer[len]) {
                        len++;
                    }
                    printCharStr(buffer);
                    chars_written += len;
                    break;
                }
                case 'd': case 'i': case 'u': case 'x': case 'X': case 'b': case 'o':
                {
                    unsigned long long val;
                    int base = 10;
                    int uppercase = 0;
                    char sign_char = 0;
                    if (format[i] == 'd' || format[i] == 'i') {
                        long long signed_val;
                        if (is_long_long) signed_val = va_arg(args, long long);
                        else if (is_long) signed_val = va_arg(args, long);
                        else if (is_char) signed_val = (signed char)va_arg(args, int);
                        else if (is_short) signed_val = (short)va_arg(args, int);
                        else signed_val = va_arg(args, int);
                        if (signed_val < 0) {
                            sign_char = '-';
                            val = -signed_val;
                        } else {
                            val = signed_val;
                        }
                    } else {
                        if (is_long_long) val = va_arg(args, unsigned long long);
                        else if (is_long) val = va_arg(args, unsigned long);
                        else if (is_char) val = (unsigned char)va_arg(args, unsigned int);
                        else if (is_short) val = (unsigned short)va_arg(args, unsigned int);
                        else val = va_arg(args, unsigned int);
                    }
                    switch(format[i]) {
                        case 'x': base = 16; break;
                        case 'X': base = 16; uppercase = 1; break;
                        case 'b': base = 2; break;
                        case 'o': base = 8; break;
                    }
                    ullToString(val, buffer, base, 0, uppercase);
                    const char* prefix = "";
                    if (use_alternative_form && val != 0) {
                        switch(format[i]) {
                            case 'x': prefix = "0x"; break;
                            case 'X': prefix = "0X"; break;
                            case 'b': prefix = "0b"; break;
                            case 'o': prefix = "0"; break;
                        }
                    }
                    int num_len = 0; while(buffer[num_len]) num_len++;
                    int prefix_len = 0; while(prefix[prefix_len]) prefix_len++;
                    int precision_pads = (precision > num_len) ? (precision - num_len) : 0;
                    int total_len = num_len + (sign_char ? 1 : 0) + prefix_len + precision_pads;
                    int width_pads = (width > total_len) ? (width - total_len) : 0;
                    chars_written += width_pads + total_len;
                    if (!zero_pad && width_pads > 0) {
                        for (int j = 0; j < width_pads; j++) printCharStr(" ");
                    }
                    if (sign_char) {
                        char_str[0] = sign_char; printCharStr(char_str);
                    }
                    if (prefix_len > 0) printCharStr(prefix);
                    if (zero_pad && width_pads > 0) {
                        for (int j = 0; j < width_pads; j++) printCharStr("0");
                    }
                    if (precision_pads > 0) {
                        for (int j = 0; j < precision_pads; j++) printCharStr("0");
                    }
                    printCharStr(buffer);
                    break;
                }
                case 'p':
                {
                    printCharStr("0x");
                    int hex_digits = sizeof(uintptr_t) * 2;
                    printHex((uintptr_t)va_arg(args, void *), hex_digits);
                    chars_written += 2 + hex_digits;
                    break;
                }
                case '%':
                    printCharStr("%");
                    chars_written++;
                    break;
                default:
                    printCharStr("%");
                    char_str[0] = format[i];
                    printCharStr(char_str);
                    chars_written += 2;
                    break;
            }
        }
        else
        {
            char_str[0] = format[i];
            printCharStr(char_str);
            chars_written++;
        }
    }
    va_end(args);
    update_cursor(cursor_x_, cursor_y_);
    return chars_written;
}
References base, cursor_x_, cursor_y_, doubleToString(), printCharStr(), printHex(), ullToString(), and update_cursor().
Referenced by __printMemoryMap(), hardware_communication::InterruptManager::activate(), driver::KeyboardDriver::activate(), driver::MouseDriver::activate(), driver::SerialDriver::activate(), hardware_communication::InterruptManager::deactivate(), driver::SerialDriver::deactivate(), hardware_communication::PCI_Controller::getDriver(), KernelShell::handle_key(), hardware_communication::InterruptManager::handleInterrupt(), essential::GDT_Manager::installTable(), hardware_communication::InterruptManager::installTable(), kernelMain(), essential::GDT_Manager::printLoadedTable(), hardware_communication::InterruptManager::printLoadedTable(), essential::GDT_Manager::printLoadedTableHeader(), hardware_communication::InterruptManager::printLoadedTableHeader(), KernelShell::process_command(), hardware_communication::PCI_Controller::recursiveSelDriver(), hardware_communication::PCI_Controller::scanBus(), taskA(), and taskB().
printHex()
static void basic::printHex (uintptr_t n, int digits) static
Prints a hexadecimal number with leading zeros.
Parameters
n The number to print.
digits The total number of digits to print (padded with zeros).
Definition at line 296 of file kiostream.cpp.
{
    char buffer[32];
    ullToString(n, buffer, 16, 0, 1); // Use uppercase for pointers typically
    int len = 0;
    while (buffer[len] != '\0') {
        len++;
    }
    for (int i = 0; i < digits - len; i++) {
        printCharStr("0");
    }
    printCharStr(buffer);
}
References printCharStr(), and ullToString().
Referenced by printf().
reverse()
static void basic::reverse (char * str, int length) static
Reverses a string in place.
Parameters
str The string to reverse.
length The length of the string.
Definition at line 185 of file kiostream.cpp.
{
    int start = 0;
    int end = length - 1;
    while (start < end)
    {
        char temp = str[start];
        str[start] = str[end];
        str[end] = temp;
        start++;
        end--;
    }
}
Referenced by ullToString().
strcat()
char * basic::strcat (char * dest, const char * src)
Appends the source string to the end of the destination string.
Parameters
dest The string to append to.
src The string to add.
Returns
A pointer to the destination string.
Definition at line 41 of file kstring.cpp.
    {
        char* original_dest = dest;
        while (*dest != '\0') dest++; // Move to end of dest
        while ((*dest++ = *src++) != '\0'); // Copy src
        return original_dest;
    }
strcmp()
int basic::strcmp (const char * s1, const char * s2)
Compares two strings lexicographically.
Parameters
s1 The first string.
s2 The second string.
Returns
0 if equal, <0 if s1 < s2, >0 if s1 > s2.
Definition at line 14 of file kstring.cpp.
    {
        while (*s1 && (*s1 == *s2)) {
            s1++;
            s2++;
        }
        return *(const unsigned char*)s1 - *(const unsigned char*)s2;
    }
Referenced by KernelShell::process_command().
strcpy()
char * basic::strcpy (char * dest, const char * src)
Copies the source string to the destination buffer.
Parameters
dest The buffer to copy into.
src The string to copy from.
Returns
A pointer to the destination string.
Definition at line 34 of file kstring.cpp.
    {
        char* original_dest = dest;
        while ((*dest++ = *src++) != '\0');
        return original_dest;
    }
strlen()
int basic::strlen (const char * str)
Calculates the length of a null-terminated string.
Parameters
str The input string.
Returns
The number of characters preceding the null byte.
Definition at line 6 of file kstring.cpp.
    {
        int len = 0;
        while (str[len] != '\0')
            len++;
        return len;
    }
strncmp()
int basic::strncmp (const char * s1, const char * s2, int n)
Compares up to 'n' characters of two strings.
Parameters
s1 The first string.
s2 The second string.
n The maximum number of characters to compare.
Returns
0 if equal (or n reached), <0 if s1 < s2, >0 if s1 > s2.
Definition at line 23 of file kstring.cpp.
    {
        while (n > 0 && *s1 && (*s1 == *s2)) {
            s1++;
            s2++;
            n--;
        }
        if (n == 0) return 0;
        return *(const unsigned char*)s1 - *(const unsigned char*)s2;
    }
ullToString()
static void basic::ullToString (unsigned long long n, char * buffer, int base, int is_signed, int uppercase) static
Converts an unsigned long long integer to a string.
Parameters
n The number to convert.
buffer The output buffer to store the string.
base The numerical base (e.g., 2, 8, 10, 16).
is_signed Whether the original number was signed (for handling negative sign).
uppercase Whether to use uppercase letters for bases > 10.
Definition at line 205 of file kiostream.cpp.
{
    int i = 0;
    int isNegative = 0;
    if (n == 0)
    {
        buffer[i++] = '0';
        buffer[i] = '\0';
        return;
    }
    if (is_signed && (long long)n < 0)
    {
        isNegative = 1;
        n = -(long long)n;
    }
    while (n != 0)
    {
        int rem = n % base;
        buffer[i++] = (rem > 9) ? ((rem - 10) + (uppercase ? 'A' : 'a')) : (rem + '0');
        n = n / base;
    }
    if (isNegative)
    {
        buffer[i++] = '-';
    }
    buffer[i] = '\0';
    reverse(buffer, i);
}
References base, and reverse().
Referenced by doubleToString(), printf(), and printHex().
update_cursor()
void basic::update_cursor (int x, int y)
Updates the position of the text mode cursor.
Parameters
x The new x-coordinate (column).
y The new y-coordinate (row).
Definition at line 56 of file kiostream.cpp.
{
    cursor_x_=x;
    cursor_y_=y;
    uint16_t pos = y * 80 + x;
    vgaIndexPort.write(0x0F);
    vgaDataPort.write((uint8_t)(pos & 0xFF));
    vgaIndexPort.write(0x0E);
    vgaDataPort.write((uint8_t)((pos >> 8) & 0xFF));
}
References cursor_x_, cursor_y_, vgaDataPort, vgaIndexPort, and hardware_communication::Port8Bit::write().
Referenced by clearScreen(), MouseEventHandler_for_kernel::onMouseDown(), and printf().
write_serial_char()
static void basic::write_serial_char (char c) static
Writes a single character to the COM1 serial port.
Definition at line 30 of file kiostream.cpp.
{
    Port8Bit dataPort(0x3F8); // COM1 Data Port
    // Handle newline: serial port needs CRLF (\r\n)
    if (c == '\n') {
        while (is_serial_ready() == 0); // Wait for port to be ready
        dataPort.write((uint8_t)'\r'); // Send carriage return
    }
    while (is_serial_ready() == 0); // Wait for port to be ready
    dataPort.write((uint8_t)c);    // Send the character
}
References is_serial_ready(), and hardware_communication::Port8Bit::write().
Referenced by clearScreen(), and printCharStr().
Variable Documentation
cursor_x_
int basic::cursor_x_ = 0 static
Definition at line 10 of file kiostream.cpp.
Referenced by clearScreen(), printCharStr(), printf(), and update_cursor().
cursor_y_
int basic::cursor_y_ = 0 static
Definition at line 11 of file kiostream.cpp.
Referenced by clearScreen(), printCharStr(), printf(), and update_cursor().
vgaDataPort
Port8Bit basic::vgaDataPort(0x3D5) (0x3D5) static
Referenced by disable_cursor(), enable_cursor(), and update_cursor().
vgaIndexPort
Port8Bit basic::vgaIndexPort(0x3D4) (0x3D4) static
Referenced by disable_cursor(), enable_cursor(), and update_cursor().