OSOS Dev: kinterrupt.hpp File Reference
kinterrupt.hpp File Reference
#include "basic/ktypes.hpp"
#include "essential/kgdt.hpp"
#include "concurrency/kmultitasking.hpp"
#include "hardware_communication/kport.hpp"
Classes
class hardware_communication::IDT_Row
Represents a single 8-byte entry (gate descriptor) in the Interrupt Descriptor Table (IDT).
class hardware_communication::InterruptHandler
Base class (interface) for handling specific CPU interrupts.
class hardware_communication::InterruptManager
Manages the Interrupt Descriptor Table (IDT) and Programmable Interrupt Controllers (PICs), dispatching interrupts to registered handlers.
Namespaces
namespace hardware_communication
Functions
~IDT_Row ()
class hardware_communication::IDT_Row hardware_communication::__attribute__ ((packed))
void handleIRQ0x00 ()
void handleIRQ0x01 ()
void handleIRQ0x04 ()
void handleIRQ0x0B ()
void handleIRQ0x0C ()
void handleIRQ0x60 ()
IDT_Row ()
void ignoreInterrupt ()
Variables
class hardware_communication::InterruptManager hardware_communication::__attribute__
uint8_t access
uint16_t handlerAddressHighbits
uint16_t handlerAddressLowbits
uint16_t kernelCodeSegmentSelector
uint8_t reserved
Function Documentation
~IDT_Row()
__attribute__::~IDT_Row ()
handleIRQ0x00()
void handleIRQ0x00 ()
Referenced by hardware_communication::InterruptManager::InterruptManager().
handleIRQ0x01()
void handleIRQ0x01 ()
Referenced by hardware_communication::InterruptManager::InterruptManager().
handleIRQ0x04()
void handleIRQ0x04 ()
Referenced by hardware_communication::InterruptManager::InterruptManager().
handleIRQ0x0B()
void handleIRQ0x0B ()
Referenced by hardware_communication::InterruptManager::InterruptManager().
handleIRQ0x0C()
void handleIRQ0x0C ()
Referenced by hardware_communication::InterruptManager::InterruptManager().
handleIRQ0x60()
void handleIRQ0x60 ()
Referenced by hardware_communication::InterruptManager::InterruptManager().
IDT_Row()
__attribute__::IDT_Row ()
ignoreInterrupt()
void ignoreInterrupt ()
Referenced by hardware_communication::InterruptManager::InterruptManager().
Variable Documentation
access
uint8_t access private
Definition at line 4 of file kinterrupt.hpp.
handlerAddressHighbits
uint16_t handlerAddressHighbits private
Definition at line 5 of file kinterrupt.hpp.
handlerAddressLowbits
uint16_t handlerAddressLowbits private
Definition at line 1 of file kinterrupt.hpp.
Referenced by hardware_communication::InterruptManager::printLoadedTable().
kernelCodeSegmentSelector
uint16_t kernelCodeSegmentSelector private
Definition at line 2 of file kinterrupt.hpp.
Referenced by hardware_communication::InterruptManager::printLoadedTable().
reserved
uint8_t reserved private
Definition at line 3 of file kinterrupt.hpp.