OSOS Dev: kernel.hpp File Reference
kernel.hpp File Reference
#include "essential/multiboot.h"
#include "essential/kgdt.hpp"
#include "essential/kicxxabi.hpp"
#include "concurrency/kmultitasking.hpp"
#include "basic/ktime.hpp"
#include "hardware_communication/kinterrupt.hpp"
#include "hardware_communication/kpci.hpp"
#include "driver/kdriver.hpp"
#include "driver/ktimer.hpp"
#include "driver/kkeyboard.hpp"
#include "driver/kmouse.hpp"
#include "driver/kserial.hpp"
#include "driver/kamd79c973.hpp"
#include "net/ketherframe.hpp"
#include "kshell.hpp"
#include "khandlers.hpp"
Classes
struct KernelArgs
Functions
void kernelMain (multiboot_info_t *mbi, uint32_t magicnumber)
Entrypoint for C++ code. we will call this function from assembly.
void kernelTail (void *arg)
this is tail of kernelMain whose CPU state will be preserved
void task_Net (void *arg)
function for shell task3 - send network packets
void task_o (void *arg)
function for shell task1 - prints o
void task_X (void *arg)
function for shell task2 - prints x
Class Documentation
KernelArgs
struct KernelArgs
Definition at line 22 of file kernel.hpp.
Class Members
DriverManager * driverManager
GDT_Manager * gdtManager
InterruptManager * interruptManager
KeyboardDriver * keyboard
multiboot_info_t * mbi
MouseDriver * mouse
SerialDriver * serial
KernelShell * shell
KThreadManager * theradManager
TimerDriver * timer
Function Documentation
kernelMain()
void kernelMain (multiboot_info_t * mbi, uint32_t magicnumber)
Entrypoint for C++ code. we will call this function from assembly.
Parameters
mbi multiboot information provided by grub
magicnumber magic number (just to varify)
Definition at line 68 of file kernel.cpp.
{
    essential::__callConstructors();
    enable_cursor(0,15);
    clearScreen();
    osos_GDT_Manager.installTable();
    // https://wiki.osdev.org/Memory_management
    memory::PhysicalMemoryManager::init(mbi);
    memory::PagingManager::init();
    // https://wiki.osdev.org/Writing_a_memory_manager
    memory::kernel_heap.init((void*)0x1000000, 8 * 1024 * 1024);
    // for kernel therads
    concurrency::KThreadManager* osos_ThreadManager = new concurrency::KThreadManager(&osos_GDT_Manager);
    // for interrupts
    hardware_communication::InterruptManager* osos_InterruptManager = new hardware_communication::InterruptManager(&osos_GDT_Manager, osos_ThreadManager);
    // creating KernelShell object to interract with OSOS
    KernelShell* shell = new KernelShell(osos_ThreadManager, mbi);
    // https://wiki.osdev.org/Category:Drivers
    driver::DriverManager* driverManager = new driver::DriverManager();
        driver::TimerDriver* timer = new driver::TimerDriver(osos_InterruptManager, 1000);
        essential::Time::setTimerDriver(timer); // to initialize essential::Time with timer
        driverManager->addDriver(timer);
        KeyboardEventHandler_for_kernel* kbdHandler = new KeyboardEventHandler_for_kernel(shell);
        driver::KeyboardDriver* keyboard = new driver::KeyboardDriver(osos_InterruptManager, kbdHandler);
        driverManager->addDriver(keyboard);
        MouseEventHandler_for_kernel* mouseHandler = new MouseEventHandler_for_kernel();
        driver::MouseDriver* mouse = new driver::MouseDriver(osos_InterruptManager, mouseHandler);
        driverManager->addDriver(mouse);
        SerialEventHandler_for_kernel* serialHandler = new SerialEventHandler_for_kernel(shell);
        driver::SerialDriver* serialIO = new driver::SerialDriver(osos_InterruptManager, serialHandler);
        driverManager->addDriver(serialIO);
        hardware_communication::PCI_Controller* pciController = new hardware_communication::PCI_Controller();
        pciController->selectDrivers(driverManager, osos_InterruptManager);
    // activate all drivers
    driverManager->activateAll();
    osos_InterruptManager->installTable();
    // making Thread Arguments for kernelTail task
    kArgs = new KernelArgs();
    kArgs->gdtManager = &osos_GDT_Manager;
    kArgs->interruptManager = osos_InterruptManager;
    kArgs->driverManager = driverManager;
    kArgs->timer = timer;
    kArgs->shell = shell;
    kArgs->theradManager = osos_ThreadManager;
    // creating tasks (or kernel therads)
    concurrency::KThread* task1 = new concurrency::KThread(&task_o, nullptr);
    concurrency::KThread* task2 = new concurrency::KThread(&task_X, nullptr);
    shell->addShellTask(task1);
    shell->addShellTask(task2);
    if(globalNetDriver != nullptr) {
        concurrency::KThread* task3 = new concurrency::KThread(&task_Net, (void*)globalNetDriver);
        shell->addShellTask(task3);
        printf("[INFO] Network task added to Kernel Shell.\n");
    } else {
        printf("[WARN] Network driver not initialized.\n");
    }
    concurrency::KThread *haltTask= new concurrency::KThread(&kernelTail, kArgs);
    haltTask->start(); // will not start executing till interrupts are off
    // Enable Interrupts (Start the System)
    hardware_communication::InterruptManager::activate();
    while (true){asm("hlt");};
    disable_cursor();
    essential::__cxa_finalize(0);
    (void)magicnumber;
}
References essential::__callConstructors(), essential::__cxa_finalize(), hardware_communication::InterruptManager::activate(), driver::DriverManager::activateAll(), driver::DriverManager::addDriver(), KernelShell::addShellTask(), basic::clearScreen(), basic::disable_cursor(), KernelArgs::driverManager, basic::enable_cursor(), KernelArgs::gdtManager, globalNetDriver, memory::PagingManager::init(), memory::PhysicalMemoryManager::init(), memory::HeapManager::init(), essential::GDT_Manager::installTable(), hardware_communication::InterruptManager::installTable(), KernelArgs::interruptManager, kArgs, memory::kernel_heap, kernelTail(), osos_GDT_Manager, basic::printf(), hardware_communication::PCI_Controller::selectDrivers(), essential::Time::setTimerDriver(), KernelArgs::shell, concurrency::KThread::start(), task_Net(), task_o(), task_X(), KernelArgs::theradManager, and KernelArgs::timer.
kernelTail()
void kernelTail (void * arg)
this is tail of kernelMain whose CPU state will be preserved
Parameters
arg
Definition at line 45 of file kernel.cpp.
{
    KernelArgs* kArgs = (KernelArgs*)arg;
    printf("\nHELLO FROM OSOS ('help' to see commands)...\n");
    #if defined(serialMode) && serialMode == 1
    printf("\nYou are using serial QEMU, Use 'ctrl+H' For Backspace\n");
    #endif
    printf("\nOSOS> ");
    while (true){
        kArgs->shell->update();
        asm("hlt");
    }
    disable_cursor();
    essential::__cxa_finalize(0);
}
References essential::__cxa_finalize(), basic::disable_cursor(), kArgs, basic::printf(), KernelArgs::shell, and KernelShell::update().
Referenced by kernelMain().
task_Net()
void task_Net (void * arg)
function for shell task3 - send network packets
Parameters
arg necessory argument as per KThread rule
Definition at line 32 of file kernel.cpp.
{
    driver::amd_am79c973* netDriver = (driver::amd_am79c973*)arg;
    printf("%p\n", netDriver);
    if(netDriver == 0) {
        printf("[NET ERROR] no driver found!\n");
        return;
    }
    return;
}
References basic::printf().
Referenced by kernelMain().
task_o()
void task_o (void * arg)
function for shell task1 - prints o
Parameters
arg necessory argument as per KThread rule
Definition at line 8 of file kernel.cpp.
                       {
    (void) arg;
    int time1, time2;
    time1 = kArgs->timer->getUptimeMS();
    for(int i=0; i<100; i++){
        printf("o");
        essential::Time::sleep(40);
    }
    time2 = kArgs->timer->getUptimeMS();
    printf("\ntask1 took : %dms\n",time2-time1);
}
References driver::TimerDriver::getUptimeMS(), kArgs, basic::printf(), essential::Time::sleep(), and KernelArgs::timer.
Referenced by kernelMain().
task_X()
void task_X (void * arg)
function for shell task2 - prints x
Parameters
arg necessory argument as per KThread rule
Definition at line 20 of file kernel.cpp.
                       {
    (void) arg;
    int time1, time2;
    time1 = kArgs->timer->getUptimeMS();
    for(int i=0; i<100; i++){
        if(i%1==0) printf("X");
        essential::Time::sleep(40);
    }
    time2 = kArgs->timer->getUptimeMS();
    printf("\ntask2 took : %dms\n",time2-time1);
}
References driver::TimerDriver::getUptimeMS(), kArgs, basic::printf(), essential::Time::sleep(), and KernelArgs::timer.
Referenced by kernelMain().