OSOS Dev: driver::SerialDriver
driver::SerialDriver abstract
Driver for the COM1 serial port (0x3F8)
#include "kserial.hpp"
Public Member Functions
SerialDriver (hardware_communication::InterruptManager *interrupt_manager, SerialEventHandler *eventHandler)
~SerialDriver ()
void activate () override
Activates the serial driver by enabling its interrupts.
void deactivate () override
Deactivates the serial driver by disabling its interrupts.
uint32_t handleInterrupt (uint32_t esp) override
Handles the serial port interrupt (IRQ 4).
virtual uintptr_t handleInterrupt (uintptr_t esp)=0
int reset () override
Resets the serial driver. (Stub)
Protected Attributes
InterruptManager * interrupt_manager
uint8_t interruptNumber
Private Attributes
hardware_communication::Port8Bit dataPort
SerialEventHandler * eventHandler
hardware_communication::Port8Bit intEnablePort
hardware_communication::Port8Bit lineStatusPort
hardware_communication::Port8Bit modemControlPort
Detailed Description
Driver for the COM1 serial port (0x3F8)
Definition at line 21 of file kserial.hpp.
Constructor & Destructor Documentation
SerialDriver()
SerialDriver::SerialDriver (hardware_communication::InterruptManager * interrupt_manager, SerialEventHandler * eventHandler)
Definition at line 10 of file kserial.cpp.
:   InterruptHandler(0x24, interrupt_manager), // 0x24 = IRQ 4
    dataPort(0x3F8),
    intEnablePort(0x3F9),      // Data Port + 1
    modemControlPort(0x3BC),   // Data Port + 4
    lineStatusPort(0x3FD)      // Data Port + 5
{
    this->eventHandler = eventHandler;
}
References eventHandler.
~SerialDriver()
SerialDriver::~SerialDriver ()
Definition at line 20 of file kserial.cpp.
{}
Member Function Documentation
activate()
void SerialDriver::activate () override virtual
Activates the serial driver by enabling its interrupts.
Implements driver::Driver.
Definition at line 37 of file kserial.cpp.
{
    intEnablePort.write(0x01);
    modemControlPort.write(0x08);
    basic::printf("Serial Driver activated!\n");
}
References intEnablePort, modemControlPort, basic::printf(), and hardware_communication::Port8Bit::write().
Referenced by reset().
deactivate()
void SerialDriver::deactivate () override virtual
Deactivates the serial driver by disabling its interrupts.
Implements driver::Driver.
Definition at line 51 of file kserial.cpp.
{
    // Disable all serial port interrupts
    intEnablePort.write(0x00);
    // Disconnect from PIC
    modemControlPort.write(0x00);
    basic::printf("Serial Driver deactivated.\n");
}
References intEnablePort, modemControlPort, basic::printf(), and hardware_communication::Port8Bit::write().
handleInterrupt() [1/2]
uint32_t SerialDriver::handleInterrupt (uint32_t esp) override
Handles the serial port interrupt (IRQ 4).
Parameters
esp The stack pointer from the interrupt context.
Returns
The stack pointer.
Reads a character from the data port (which clears the interrupt) and forwards it to the event handler.
Definition at line 22 of file kserial.cpp.
{
    if (eventHandler == 0) {
        dataPort.read();
        return esp;
    }
    if (lineStatusPort.read() & 0x01){
        char data = dataPort.read();
        eventHandler->onDataReceived(data);
    }
    return esp;
}
References dataPort, esp, eventHandler, lineStatusPort, driver::SerialEventHandler::onDataReceived(), and hardware_communication::Port8Bit::read().
handleInterrupt() [2/2]
virtual uintptr_t hardware_communication::InterruptHandler::handleInterrupt (uintptr_t esp) pure virtual inherited
Referenced by hardware_communication::InterruptManager::handleInterrupt().
reset()
int SerialDriver::reset () override virtual
Resets the serial driver. (Stub)
Returns
Always returns 0.
Implements driver::Driver.
Definition at line 45 of file kserial.cpp.
{
    activate();
    return 0;
}
References activate().
Member Data Documentation
dataPort
hardware_communication::Port8Bit driver::SerialDriver::dataPort private
Definition at line 23 of file kserial.hpp.
Referenced by handleInterrupt().
eventHandler
SerialEventHandler* driver::SerialDriver::eventHandler private
Definition at line 27 of file kserial.hpp.
Referenced by SerialDriver(), and handleInterrupt().
intEnablePort
hardware_communication::Port8Bit driver::SerialDriver::intEnablePort private
Definition at line 24 of file kserial.hpp.
Referenced by activate(), and deactivate().
interrupt_manager
InterruptManager* hardware_communication::InterruptHandler::interrupt_manager protected inherited
Definition at line 28 of file kinterrupt.hpp.
Referenced by hardware_communication::InterruptHandler::InterruptHandler(), and hardware_communication::InterruptHandler::~InterruptHandler().
interruptNumber
uint8_t hardware_communication::InterruptHandler::interruptNumber protected inherited
Definition at line 27 of file kinterrupt.hpp.
Referenced by hardware_communication::InterruptHandler::InterruptHandler(), and hardware_communication::InterruptHandler::~InterruptHandler().
lineStatusPort
hardware_communication::Port8Bit driver::SerialDriver::lineStatusPort private
Definition at line 26 of file kserial.hpp.
Referenced by handleInterrupt().
modemControlPort
hardware_communication::Port8Bit driver::SerialDriver::modemControlPort private
Definition at line 25 of file kserial.hpp.
Referenced by activate(), and deactivate().
The documentation for this class was generated from the following files:
kserial.hpp
kserial.cpp