OSOS Dev: essential::Time
essential::Time
#include "ktime.hpp"
Static Public Member Functions
static uint32_t getFrequency ()
Get current timer frequency.
static uint64_t getUptimeMS ()
Get system uptime in milliseconds.
static void setTimerDriver (driver::TimerDriver *driver)
static void sleep (uint32_t ms)
sleep for milliseconds (Blocking)
Static Private Attributes
static driver::TimerDriver * activeTimerDriver = 0
Detailed Description
Definition at line 8 of file ktime.hpp.
Member Function Documentation
getFrequency()
uint32_t essential::Time::getFrequency () static
Get current timer frequency.
Definition at line 24 of file ktime.cpp.
{
        if (activeTimerDriver) {
            return activeTimerDriver->getFrequency();
        }
        return 0;
    }
References activeTimerDriver, and driver::TimerDriver::getFrequency().
getUptimeMS()
uint64_t essential::Time::getUptimeMS () static
Get system uptime in milliseconds.
Definition at line 17 of file ktime.cpp.
{
        if (activeTimerDriver) {
            return activeTimerDriver->getUptimeMS();
        }
        return 0;
    }
References activeTimerDriver, and driver::TimerDriver::getUptimeMS().
Referenced by KernelShell::process_command().
setTimerDriver()
void essential::Time::setTimerDriver (driver::TimerDriver * driver) static
Definition at line 7 of file ktime.cpp.
{
        activeTimerDriver = driver;
    }
References activeTimerDriver.
Referenced by kernelMain().
sleep()
void essential::Time::sleep (uint32_t ms) static
sleep for milliseconds (Blocking)
Definition at line 11 of file ktime.cpp.
{
        if (activeTimerDriver) {
            activeTimerDriver->sleep(ms);
        }
    }
References activeTimerDriver, and driver::TimerDriver::sleep().
Referenced by KernelShell::process_command(), task_o(), and task_X().
Member Data Documentation
activeTimerDriver
driver::TimerDriver * essential::Time::activeTimerDriver = 0 static private
Definition at line 10 of file ktime.hpp.
Referenced by getFrequency(), getUptimeMS(), setTimerDriver(), and sleep().
The documentation for this class was generated from the following files:
ktime.hpp
ktime.cpp