OSOS Dev: driver::DriverManager
driver::DriverManager
Manages a collection of Driver objects, facilitating their activation and organization.
#include "kdriver.hpp"
Public Member Functions
DriverManager ()
~DriverManager ()
void activateAll ()
Activates all drivers currently registered with the manager.
void addDriver (Driver *)
Adds a driver to the manager's list.
Private Attributes
Driver * drivers [MAX_NUMDRIVERS]
int numDrivers
Detailed Description
Manages a collection of Driver objects, facilitating their activation and organization.
Definition at line 19 of file kdriver.hpp.
Constructor & Destructor Documentation
DriverManager()
DriverManager::DriverManager ()
Definition at line 8 of file kdriver.cpp.
{
    numDrivers=0;
}
References numDrivers.
~DriverManager()
DriverManager::~DriverManager ()
Definition at line 13 of file kdriver.cpp.
{}
Member Function Documentation
activateAll()
void DriverManager::activateAll ()
Activates all drivers currently registered with the manager.
Definition at line 24 of file kdriver.cpp.
{
    for(int i=0; i<numDrivers; i++){
        printf("%p : ", drivers[i]);
        drivers[i]->activate();
    }
}
References driver::Driver::activate(), drivers, numDrivers, and basic::printf().
Referenced by kernelMain().
addDriver()
void DriverManager::addDriver (Driver * driver)
Adds a driver to the manager's list.
Parameters
driver A pointer to the driver object to be added.
Definition at line 15 of file kdriver.cpp.
{
    drivers[numDrivers]=driver;
    numDrivers++;
}
References drivers, and numDrivers.
Referenced by kernelMain(), and hardware_communication::PCI_Controller::recursiveSelDriver().
Member Data Documentation
drivers
Driver* driver::DriverManager::drivers[MAX_NUMDRIVERS] private
Definition at line 21 of file kdriver.hpp.
Referenced by activateAll(), and addDriver().
numDrivers
int driver::DriverManager::numDrivers private
Definition at line 22 of file kdriver.hpp.
Referenced by DriverManager(), activateAll(), and addDriver().
The documentation for this class was generated from the following files:
kdriver.hpp
kdriver.cpp