OSOS Dev: basic Namespace Reference
basic Namespace Reference
Classes
class LockGuard
class Mutex
class Spinlock
Functions
void clearScreen ()
Clears the entire text mode screen and resets the cursor to (0,0).
void disable_cursor ()
Disables the text mode cursor.
static void doubleToString (double d, char *buffer, int precision)
void enable_cursor (uint8_t cursor_start, uint8_t cursor_end)
Enables the text mode cursor and sets its shape.
void * memcpy (void *dest, const void *src, int num)
Copies 'num' bytes from source memory to destination memory.
void * memset (void *ptr, int value, int num)
Fills a block of memory with a specific value.
void os_yield ()
static double power (double base, int exp)
static void printCharStr (const char *str)
int printf (const char *format,...)
A custom implementation of the standard printf function for writing to both VGA text mode memory and the COM1 serial port.
static void printHex (uintptr_t n, int digits)
static void reverse (char *str, int length)
int stoi (const char *str, int base=10)
Converts a string to an integer.
char * strcat (char *dest, const char *src)
Appends the source string to the end of the destination string.
int strcmp (const char *s1, const char *s2)
Compares two strings lexicographically.
char * strcpy (char *dest, const char *src)
Copies the source string to the destination buffer.
int strlen (const char *str)
Calculates the length of a null-terminated string.
int strncmp (const char *s1, const char *s2, int n)
Compares up to 'n' characters of two strings.
static void ullToString (unsigned long long n, char *buffer, int base, int is_signed, int uppercase)
void update_cursor (int x, int y)
Updates the position of the text mode cursor.
Variables
static int cursor_x_ = 0
static int cursor_y_ = 0
static Mutex printfMutex
static Spinlock printfSpin
static Port8Bit vgaDataPort (0x3D5)
static Port8Bit vgaIndexPort (0x3D4)
Function Documentation
clearScreen()
void basic::clearScreen ()
Clears the entire text mode screen and resets the cursor to (0,0).
Definition at line 134 of file kiostream.cpp.
{
    unsigned short *video_memory = (unsigned short *)0xb8000;
    unsigned short blank = (0x07 << 8) | ' ';
    int screenSize = MAGIC_WIDTH * MAGIC_HEIGHT;
    for (int i = 0; i < screenSize; i++) {
        video_memory[i] = blank;
    }
    driver::MouseDriver::old_char_under_mouse_pointer = blank;
    cursor_x_ = -1;
    cursor_y_ = -1;
    update_cursor(cursor_x_, cursor_y_);
     #if defined(serialMode) && serialMode == 1
    const char* clear_sequence = "\e[2J\e[H";
    for (int i = 0; clear_sequence[i] != '\0'; i++) {
        write_serial_char(clear_sequence[i]);
    }
    #endif
}
References cursor_x_, cursor_y_, MAGIC_HEIGHT, MAGIC_WIDTH, driver::MouseDriver::old_char_under_mouse_pointer, and update_cursor().
Referenced by kernelMain(), and KernelShell::process_command().
disable_cursor()
void basic::disable_cursor ()
Disables the text mode cursor.
Definition at line 62 of file kiostream.cpp.
{
    vgaIndexPort.write(0x0A);
    vgaDataPort.write(0x20);
}
References vgaDataPort, vgaIndexPort, and hardware_communication::Port8Bit::write().
Referenced by kernelMain(), and kernelTail().
doubleToString()
static void basic::doubleToString (double d, char * buffer, int precision) static
Definition at line 202 of file kiostream.cpp.
{
    if (precision < 0) precision = 6;
    char *ptr = buffer;
    if (d < 0) { *ptr++ = '-'; d = -d; }
    unsigned long long int_part = (unsigned long long)d;
    double frac_part = d - (double)int_part;
    ullToString(int_part, ptr, 10, 0, 0);
    while (*ptr) ptr++;
    *ptr++ = '.';
    unsigned long long frac_as_ull = (unsigned long long)(frac_part * power(10, precision) + 0.5);
    char frac_buffer[32];
    ullToString(frac_as_ull, frac_buffer, 10, 0, 0);
    int frac_len = 0;
    while(frac_buffer[frac_len] != '\0') frac_len++;
    int padding = precision - frac_len;
    for (int i = 0; i < padding; i++) *ptr++ = '0';
    char* frac_ptr = frac_buffer;
    while(*frac_ptr) *ptr++ = *frac_ptr++;
    *ptr = '\0';
}
References power(), and ullToString().
Referenced by printf().
enable_cursor()
void basic::enable_cursor (uint8_t cursor_start, uint8_t cursor_end)
Enables the text mode cursor and sets its shape.
Parameters
cursor_start The starting scanline for the cursor block.
cursor_end The ending scanline for the cursor block.
Definition at line 43 of file kiostream.cpp.
{
    vgaIndexPort.write(0x0A);
    vgaDataPort.write((vgaDataPort.read() & 0xC0) | cursor_start);
    vgaIndexPort.write(0x0B);
    vgaDataPort.write((vgaDataPort.read() & 0xE0) | cursor_end);
}
References hardware_communication::Port8Bit::read(), vgaDataPort, vgaIndexPort, and hardware_communication::Port8Bit::write().
Referenced by kernelMain().
memcpy()
void * basic::memcpy (void * dest, const void * src, int num)
Copies 'num' bytes from source memory to destination memory.
Parameters
dest Pointer to the destination memory.
src Pointer to the source memory.
num Number of bytes to copy.
Returns
A pointer to the destination.
Definition at line 58 of file kstring.cpp.
    {
        char* d = (char*)dest;
        const char* s = (const char*)src;
        while (num--) {
            *d++ = *s++;
        }
        return dest;
    }
memset()
void * basic::memset (void * ptr, int value, int num)
Fills a block of memory with a specific value.
Parameters
ptr Pointer to the block of memory to fill.
value The value to be set.
num Number of bytes to be set to the value.
Returns
A pointer to the block of memory.
Definition at line 49 of file kstring.cpp.
    {
        unsigned char* p = (unsigned char*)ptr;
        while (num--) {
            *p++ = (unsigned char)value;
        }
        return ptr;
    }
os_yield()
void basic::os_yield ()
Definition at line 8 of file kmutex.hpp.
                    {
        asm volatile("int $0x80");// 0x80 is chosen arbitrarily as our "System Call" vector.
    }
Referenced by basic::Mutex::lock().
power()
static double basic::power (double base, int exp) static
Definition at line 195 of file kiostream.cpp.
{
    double res = 1.0;
    for (int i = 0; i < exp; ++i) res *= base;
    return res;
}
References base.
Referenced by doubleToString().
printCharStr()
static void basic::printCharStr (const char * str) static
Definition at line 68 of file kiostream.cpp.
{
    uint16_t *video_memory = (uint16_t *)0xb8000;
    const uint16_t color_attribute = 0x0700;
    int mouse_offset = driver::MouseDriver::__mouse_y_ * MAGIC_WIDTH + driver::MouseDriver::__mouse_x_;
    if (mouse_offset >= 0 && mouse_offset < (MAGIC_WIDTH * MAGIC_HEIGHT)) {
        video_memory[mouse_offset] = driver::MouseDriver::old_char_under_mouse_pointer;
    }
    for (int i = 0; str[i] != '\0'; i++)
    {
        #if defined(serialMode) && serialMode == 1
        write_serial_char(str[i]);
        #endif
        if (str[i] == '\n') {
            cursor_y_++;
            cursor_x_ = 0;
        }
        else if (str[i] == '\b') {
            if (cursor_x_ > 0) {
                cursor_x_--;
                int offset = cursor_y_ * MAGIC_WIDTH + cursor_x_;
                video_memory[offset] = color_attribute | ' ';
            }
        }
        else if (str[i] == '\r') {
            cursor_x_ = 0;
        }
        else if (str[i] == '\t') {
            cursor_x_ = cursor_x_ + (TAB_WIDTH - (cursor_x_ % TAB_WIDTH));
        }
        else {
            int offset = cursor_y_ * MAGIC_WIDTH + cursor_x_;
            video_memory[offset] = color_attribute | str[i];
            cursor_x_++;
        }
        if (cursor_x_ >= MAGIC_WIDTH) {
            cursor_y_++;
            cursor_x_ = 0;
        }
        if (cursor_y_ >= MAGIC_HEIGHT) {
            for (int y = 0; y < (MAGIC_HEIGHT - 1); y++) {
                for (int x = 0; x < MAGIC_WIDTH; x++) {
                    video_memory[y * MAGIC_WIDTH + x] = video_memory[(y + 1) * MAGIC_WIDTH + x];
                }
            }
            int last_line_offset_start = (MAGIC_HEIGHT - 1) * MAGIC_WIDTH;
            for (int x = 0; x < MAGIC_WIDTH; x++) {
                video_memory[last_line_offset_start + x] = color_attribute | ' ';
            }
            cursor_y_ = MAGIC_HEIGHT - 1;
            cursor_x_ = 0;
        }
    }
    if (mouse_offset >= 0 && mouse_offset < (MAGIC_WIDTH * MAGIC_HEIGHT)) {
        driver::MouseDriver::old_char_under_mouse_pointer = video_memory[mouse_offset];
        video_memory[mouse_offset] = driver::MouseDriver::mouse_block_video_mem_value(driver::MouseDriver::old_char_under_mouse_pointer, MOUSE_POINTER_COLOR);
    }
}
References driver::MouseDriver::__mouse_x_, driver::MouseDriver::__mouse_y_, cursor_x_, cursor_y_, MAGIC_HEIGHT, MAGIC_WIDTH, driver::MouseDriver::mouse_block_video_mem_value(), MOUSE_POINTER_COLOR, driver::MouseDriver::old_char_under_mouse_pointer, and TAB_WIDTH.
Referenced by printf(), and printHex().
printf()
int basic::printf (const char * format, ...)
A custom implementation of the standard printf function for writing to both VGA text mode memory and the COM1 serial port.
This function formats a string and prints it to the screen and serial console, handling various format specifiers, flags, width, precision, and length modifiers. It returns the total number of characters written.
Parameters
format The null-terminated format string.
... Variable arguments corresponding to the format specifiers in the format string.
Returns
The total number of characters written (to both screen and serial).
This function internally uses printCharStr, which routes every character to both the VGA buffer (0xb8000) and the serial port (COM1, 0x3F8) simultaneously.
Supported Format Specifiers:
c - Character
s - String
d, i - Signed decimal integer
u - Unsigned decimal integer
f - Floating point number (double)
x - Unsigned hexadecimal integer (lowercase)
X - Unsigned hexadecimal integer (uppercase)
b - Unsigned binary integer
o - Unsigned octal integer
p - Pointer address (formats as 0x prefixed hex)
%% - A literal '' character
Supported Flags:
'#' - Alternative form (e.g., 0x for hex, 0b for binary, 0 for octal).
'0' - Zero-padding for width (ignored if precision is specified or '-' flag is used).
Supported Width:
A number after '' specifies the minimum field width (e.g., %10d). Padded with spaces by default, or zeros if '0' flag is used.
Supported Precision:
A period followed by a number (e.g., %.4f, %.8X).
For floats: specifies the number of digits after the decimal point.
For integers: specifies the minimum number of digits to print (padded with leading zeros).
Supported Length Modifiers:
h - short (for d, i, u, x, X, o, b)
hh - char (for d, i, u, x, X, o, b)
l - long (for d, i, u, x, X, o, b)
ll - long long (for d, i, u, x, X, o, b)
Definition at line 243 of file kiostream.cpp.
{
    basic::LockGuard<basic::Mutex> guard(printfMutex); // i chose mutex lock (LockGuard will automatically unlocks)
    // basic::LockGuard<basic::Spinlock> guard(printfSpin);
    int chars_written = 0;
    va_list args;
    va_start(args, format);
    char buffer[128];
    char char_str[2] = {0, 0};
    for (int i = 0; format[i] != '\0'; i++)
    {
        if (format[i] == '%')
        {
            i++;
            int use_alternative_form = 0;
            int zero_pad = 0;
            int left_align = 0;
            int width = 0;
            int precision = -1;
            while(1) {
                if (format[i] == '-') { left_align = 1; i++; }
                else if (format[i] == '#') { use_alternative_form = 1; i++; }
                else if (format[i] == '0') { zero_pad = 1; i++; }
                else break;
            }
            // Standard Rule: If left alignment (-) is used, zero padding is ignored.
            if (left_align) zero_pad = 0;
            while (format[i] >= '0' && format[i] <= '9') {
                width = width * 10 + (format[i] - '0');
                i++;
            }
            if (format[i] == '.') {
                i++; precision = 0;
                while (format[i] >= '0' && format[i] <= '9') {
                    precision = precision * 10 + (format[i] - '0');
                    i++;
                }
            }
            int is_long = 0, is_long_long = 0, is_short = 0, is_char = 0;
            if (format[i] == 'l') { is_long = 1; i++; if (format[i] == 'l') { is_long_long = 1; is_long = 0; i++; }}
            else if (format[i] == 'h') { is_short = 1; i++; if (format[i] == 'h') { is_char = 1; is_short = 0; i++; }}
            switch (format[i])
            {
                case 'c':
                    char_str[0] = (char)va_arg(args, int);
                    printCharStr(char_str);
                    chars_written++;
                    break;
                case 's':
                {
                    const char *str = va_arg(args, char *);
                    if (!str) str = "(null)";
                    int len = 0; while (str[len]) len++;
                    int padding = (width > len) ? (width - len) : 0;
                    chars_written += len + padding;
                    // If Left Align: Print String -> Then Padding
                    if (left_align) {
                        printCharStr(str);
                        for(int k=0; k<padding; k++) printCharStr(" ");
                    }
                    // If Right Align: Print Padding -> Then String
                    else {
                        for(int k=0; k<padding; k++) printCharStr(" ");
                        printCharStr(str);
                    }
                    break;
                }
                case 'f':
                {
                    doubleToString(va_arg(args, double), buffer, precision);
                    int len = 0; while(buffer[len]) len++;
                    int padding = (width > len) ? (width - len) : 0;
                    chars_written += len + padding;
                    if (left_align) {
                        printCharStr(buffer);
                        for(int k=0; k<padding; k++) printCharStr(" ");
                    } else {
                        // Handle standard space padding vs zero padding
                        char padChar = (zero_pad && precision == -1) ? '0' : ' ';
                        for(int k=0; k<padding; k++) {
                            char p[2] = {padChar, 0};
                            printCharStr(p);
                        }
                        printCharStr(buffer);
                    }
                    break;
                }
                case 'd': case 'i': case 'u': case 'x': case 'X': case 'b': case 'o':
                {
                    unsigned long long val;
                    int base = 10;
                    int uppercase = 0;
                    char sign_char = 0;
                    if (format[i] == 'd' || format[i] == 'i') {
                        long long signed_val;
                        if (is_long_long) signed_val = va_arg(args, long long);
                        else if (is_long) signed_val = va_arg(args, long);
                        else if (is_char) signed_val = (signed char)va_arg(args, int);
                        else if (is_short) signed_val = (short)va_arg(args, int);
                        else signed_val = va_arg(args, int);
                        if (signed_val < 0) { sign_char = '-'; val = -signed_val; } else { val = signed_val; }
                    } else {
                        if (is_long_long) val = va_arg(args, unsigned long long);
                        else if (is_long) val = va_arg(args, unsigned long);
                        else if (is_char) val = (unsigned char)va_arg(args, unsigned int);
                        else if (is_short) val = (unsigned short)va_arg(args, unsigned int);
                        else val = va_arg(args, unsigned int);
                    }
                    switch(format[i]) {
                        case 'x': base = 16; break;
                        case 'X': base = 16; uppercase = 1; break;
                        case 'b': base = 2; break;
                        case 'o': base = 8; break;
                    }
                    ullToString(val, buffer, base, 0, uppercase);
                    const char* prefix = "";
                    if (use_alternative_form && val != 0) {
                        switch(format[i]) {
                            case 'x': prefix = "0x"; break;
                            case 'X': prefix = "0X"; break;
                            case 'b': prefix = "0b"; break;
                            case 'o': prefix = "0"; break;
                        }
                    }
                    int num_len = 0; while(buffer[num_len]) num_len++;
                    int prefix_len = 0; while(prefix[prefix_len]) prefix_len++;
                    int precision_pads = (precision > num_len) ? (precision - num_len) : 0;
                    int total_len = num_len + (sign_char ? 1 : 0) + prefix_len + precision_pads;
                    int width_pads = (width > total_len) ? (width - total_len) : 0;
                    chars_written += width_pads + total_len;
                    if (left_align) {
                        // Left Align format: [Sign][Prefix][PrecisionZeros][Number] [Spaces]
                        if (sign_char) { char_str[0] = sign_char; printCharStr(char_str); }
                        if (prefix_len > 0) printCharStr(prefix);
                        if (precision_pads > 0) for (int j = 0; j < precision_pads; j++) printCharStr("0");
                        printCharStr(buffer);
                        // Padding goes at the END
                        for (int j = 0; j < width_pads; j++) printCharStr(" ");
                    } else {
                        // Right Align format: [Spaces][Sign][Prefix][ZeroPads][Number]
                        // Note: If '0' flag is used, padding spaces become '0' and move AFTER sign/prefix
                        if (!zero_pad) {
                            for (int j = 0; j < width_pads; j++) printCharStr(" ");
                        }
                        if (sign_char) { char_str[0] = sign_char; printCharStr(char_str); }
                        if (prefix_len > 0) printCharStr(prefix);
                        if (zero_pad) {
                            for (int j = 0; j < width_pads; j++) printCharStr("0");
                        }
                        if (precision_pads > 0) for (int j = 0; j < precision_pads; j++) printCharStr("0");
                        printCharStr(buffer);
                    }
                    break;
                }
                case 'p':
                {
                    printCharStr("0x");
                    int hex_digits = sizeof(uintptr_t) * 2;
                    printHex((uintptr_t)va_arg(args, void *), hex_digits);
                    chars_written += 2 + hex_digits;
                    break;
                }
                case '%':
                    printCharStr("%"); chars_written++; break;
                default:
                    printCharStr("%"); char_str[0] = format[i]; printCharStr(char_str); chars_written += 2; break;
            }
        }
        else {
            char_str[0] = format[i]; printCharStr(char_str); chars_written++;
        }
    }
    va_end(args);
    update_cursor(cursor_x_, cursor_y_);
    return chars_written;
}
References base, cursor_x_, cursor_y_, doubleToString(), len, printCharStr(), printfMutex, printHex(), ullToString(), update_cursor(), va_arg, va_end, and va_start.
Referenced by driver::amd_am79c973::activate(), hardware_communication::InterruptManager::activate(), driver::KeyboardDriver::activate(), driver::MouseDriver::activate(), driver::SerialDriver::activate(), driver::TimerDriver::activate(), driver::DriverManager::activateAll(), memory::HeapManager::allocate(), memory::PhysicalMemoryManager::allocate_block(), hardware_communication::InterruptManager::deactivate(), driver::SerialDriver::deactivate(), hardware_communication::PCI_Controller::getDriver(), KernelShell::handle_key_logic(), driver::amd_am79c973::handleInterrupt(), hardware_communication::InterruptManager::handleInterrupt(), memory::PagingManager::init(), memory::PhysicalMemoryManager::init(), memory::HeapManager::init(), essential::GDT_Manager::installTable(), hardware_communication::InterruptManager::installTable(), kernelMain(), kernelTail(), memory::HeapManager::printHeapInfo(), essential::GDT_Manager::printLoadedTable(), hardware_communication::InterruptManager::printLoadedTable(), essential::GDT_Manager::printLoadedTableHeader(), hardware_communication::InterruptManager::printLoadedTableHeader(), memory::printMemoryMap(), memory::PagingManager::printPageDirectory(), KernelShell::process_command(), driver::amd_am79c973::receive(), hardware_communication::PCI_Controller::scanBus(), driver::amd_am79c973::send(), task_Net(), task_o(), and task_X().
printHex()
static void basic::printHex (uintptr_t n, int digits) static
Definition at line 230 of file kiostream.cpp.
{
    char buffer[32];
    ullToString(n, buffer, 16, 0, 1);
    int len = 0;
    while (buffer[len] != '\0') len++;
    for (int i = 0; i < digits - len; i++) printCharStr("0");
    printCharStr(buffer);
}
References len, printCharStr(), and ullToString().
Referenced by printf().
reverse()
static void basic::reverse (char * str, int length) static
Definition at line 159 of file kiostream.cpp.
{
    int start = 0;
    int end = length - 1;
    while (start < end) {
        char temp = str[start];
        str[start] = str[end];
        str[end] = temp;
        start++;
        end--;
    }
}
References end.
Referenced by ullToString().
stoi()
int basic::stoi (const char * str, int base = 10)
Converts a string to an integer.
Parameters
str The string to convert.
base The numerical base (e.g., 10 for decimal, 16 for hex). Defaults to 10.
Returns
The converted integer value.
Definition at line 68 of file kstring.cpp.
    {
        if (!str) return 0;
        int result = 0;
        int sign = 1;
        // Skip whitespace
        while (*str == ' ' || *str == '\t' || *str == '\n' || *str == '\r') {
            str++;
        }
        // Handle sign
        if (*str == '-') {
            sign = -1;
            str++;
        } else if (*str == '+') {
            str++;
        }
        // Handle Hex prefix (0x) if base is 16
        if (base == 16 && *str == '0' && (*(str + 1) == 'x' || *(str + 1) == 'X')) {
            str += 2;
        }
        // Convert digits
        while (*str) {
            int digit;
            char c = *str;
            if (c >= '0' && c <= '9') {
                digit = c - '0';
            } else if (c >= 'a' && c <= 'z') {
                digit = c - 'a' + 10;
            } else if (c >= 'A' && c <= 'Z') {
                digit = c - 'A' + 10;
            } else {
                break; // Invalid character (non-alphanumeric)
            }
            // Ensure the digit is valid for the current base
            if (digit >= base) {
                break;
            }
            result = result * base + digit;
            str++;
        }
        return result * sign;
    }
References base.
Referenced by KernelShell::process_command().
strcat()
char * basic::strcat (char * dest, const char * src)
Appends the source string to the end of the destination string.
Parameters
dest The string to append to.
src The string to add.
Returns
A pointer to the destination string.
Definition at line 41 of file kstring.cpp.
    {
        char* original_dest = dest;
        while (*dest != '\0') dest++; // Move to end of dest
        while ((*dest++ = *src++) != '\0'); // Copy src
        return original_dest;
    }
strcmp()
int basic::strcmp (const char * s1, const char * s2)
Compares two strings lexicographically.
Parameters
s1 The first string.
s2 The second string.
Returns
0 if equal, <0 if s1 < s2, >0 if s1 > s2.
Definition at line 14 of file kstring.cpp.
    {
        while (*s1 && (*s1 == *s2)) {
            s1++;
            s2++;
        }
        return *(const unsigned char*)s1 - *(const unsigned char*)s2;
    }
Referenced by KernelShell::process_command().
strcpy()
char * basic::strcpy (char * dest, const char * src)
Copies the source string to the destination buffer.
Parameters
dest The buffer to copy into.
src The string to copy from.
Returns
A pointer to the destination string.
Definition at line 34 of file kstring.cpp.
    {
        char* original_dest = dest;
        while ((*dest++ = *src++) != '\0');
        return original_dest;
    }
strlen()
int basic::strlen (const char * str)
Calculates the length of a null-terminated string.
Parameters
str The input string.
Returns
The number of characters preceding the null byte.
Definition at line 6 of file kstring.cpp.
    {
        int len = 0;
        while (str[len] != '\0')
            len++;
        return len;
    }
References len.
strncmp()
int basic::strncmp (const char * s1, const char * s2, int n)
Compares up to 'n' characters of two strings.
Parameters
s1 The first string.
s2 The second string.
n The maximum number of characters to compare.
Returns
0 if equal (or n reached), <0 if s1 < s2, >0 if s1 > s2.
Definition at line 23 of file kstring.cpp.
    {
        while (n > 0 && *s1 && (*s1 == *s2)) {
            s1++;
            s2++;
            n--;
        }
        if (n == 0) return 0;
        return *(const unsigned char*)s1 - *(const unsigned char*)s2;
    }
Referenced by KernelShell::process_command().
ullToString()
static void basic::ullToString (unsigned long long n, char * buffer, int base, int is_signed, int uppercase) static
Definition at line 172 of file kiostream.cpp.
{
    int i = 0;
    int isNegative = 0;
    if (n == 0) {
        buffer[i++] = '0';
        buffer[i] = '\0';
        return;
    }
    if (is_signed && (long long)n < 0) {
        isNegative = 1;
        n = -(long long)n;
    }
    while (n != 0) {
        int rem = n % base;
        buffer[i++] = (rem > 9) ? ((rem - 10) + (uppercase ? 'A' : 'a')) : (rem + '0');
        n = n / base;
    }
    if (isNegative) buffer[i++] = '-';
    buffer[i] = '\0';
    reverse(buffer, i);
}
References base, and reverse().
Referenced by doubleToString(), printf(), and printHex().
update_cursor()
void basic::update_cursor (int x, int y)
Updates the position of the text mode cursor.
Parameters
x The new x-coordinate (column).
y The new y-coordinate (row).
Definition at line 51 of file kiostream.cpp.
{
    cursor_x_=x;
    cursor_y_=y;
    uint16_t pos = y * 80 + x;
    vgaIndexPort.write(0x0F);
    vgaDataPort.write((uint8_t)(pos & 0xFF));
    vgaIndexPort.write(0x0E);
    vgaDataPort.write((uint8_t)((pos >> 8) & 0xFF));
}
References cursor_x_, cursor_y_, vgaDataPort, vgaIndexPort, and hardware_communication::Port8Bit::write().
Referenced by clearScreen(), MouseEventHandler_for_kernel::onMouseDown(), and printf().
Variable Documentation
cursor_x_
int basic::cursor_x_ = 0 static
Definition at line 14 of file kiostream.cpp.
Referenced by clearScreen(), printCharStr(), printf(), and update_cursor().
cursor_y_
int basic::cursor_y_ = 0 static
Definition at line 15 of file kiostream.cpp.
Referenced by clearScreen(), printCharStr(), printf(), and update_cursor().
printfMutex
Mutex basic::printfMutex static
Definition at line 240 of file kiostream.cpp.
Referenced by printf().
printfSpin
Spinlock basic::printfSpin static
Definition at line 241 of file kiostream.cpp.
vgaDataPort
Port8Bit basic::vgaDataPort(0x3D5) (0x3D5) static
Referenced by disable_cursor(), enable_cursor(), and update_cursor().
vgaIndexPort
Port8Bit basic::vgaIndexPort(0x3D4) (0x3D4) static
Referenced by disable_cursor(), enable_cursor(), and update_cursor().