OSOS Dev: KernelShell
KernelShell
A simple shell/terminal manager for the kernel.
#include "kernel.hpp"
Public Member Functions
KernelShell ()
~KernelShell ()
void handle_key (char c)
The single, centralized function for handling all key presses.
void process_command (const char *command)
Simple command processor.
Private Attributes
int m_buffer_index
char m_line_buffer [256]
hardware_communication::PCI_Controller pciController
Detailed Description
A simple shell/terminal manager for the kernel.
Definition at line 16 of file kernel.hpp.
Constructor & Destructor Documentation
KernelShell()
KernelShell::KernelShell () inline
Definition at line 23 of file kernel.hpp.
    {
        m_buffer_index = 0;
        m_line_buffer[0] = '\0';
    }
References m_buffer_index, and m_line_buffer.
~KernelShell()
KernelShell::~KernelShell () inline
Definition at line 28 of file kernel.hpp.
{}
Member Function Documentation
handle_key()
void KernelShell::handle_key (char c) inline
The single, centralized function for handling all key presses.
Parameters
c The character received from any input driver (keyboard or serial driver).
Definition at line 32 of file kernel.hpp.
    {
        if (c == 0) return;
        switch(c)
        {
            // PS/2 Keyboard sends '\n' (from keyboard driver)
            // Serial sends '\r' (from serial driver)
            case '\r':
            case '\n':
                basic::printf("\n");
                m_line_buffer[m_buffer_index] = '\0';
                if (m_buffer_index > 0) {
                    process_command(m_line_buffer);
                }
                // Reset for next line
                m_buffer_index = 0;
                m_line_buffer[0] = '\0';
                basic::printf("\nOSOS> "); // Print a new prompt
                break;
            case 8: // Backspace '\b'
                if (m_buffer_index > 0){
                    m_buffer_index--;
                    m_line_buffer[m_buffer_index] = '\0';
                    basic::printf("\b \b"); // '\b' only move cursor back in serial terminal (e.g. my Ubuntu terminal), so i am printing ' ' once and then again '\b'
                }
                break;
            // Handle printable characters
            default:
                if (c >= ' ' && c <= '~' && m_buffer_index < 254)
                {
                    m_line_buffer[m_buffer_index++] = c;
                    m_line_buffer[m_buffer_index] = '\0';
                    basic::printf("%c", c);
                }
                break;
        }
    }
References m_buffer_index, m_line_buffer, basic::printf(), and process_command().
Referenced by SerialEventHandler_for_kernel::onDataReceived(), and KeyboardEventHandler_for_kernel::onKeyDown().
process_command()
void KernelShell::process_command (const char * command) inline
Simple command processor.
Parameters
command The null-terminated command string to process.
Definition at line 75 of file kernel.hpp.
    {
        // Simple "strcmp"
        if (command[0] == 'h' && command[1] == 'e' && command[2] == 'l' && command[3] == 'p' && command[4] == '\0') {
            basic::printf("OSOS Kernel Shell. Type 'lspci' to list devices.");
        }
        else if (command[0] == 'l' && command[1] == 's' && command[2] == 'p' && command[3] == 'c' && command[4] == 'i' && command[5] == '\0') {
            basic::printf("Listing PCI devices...\n");
            pciController.scanBus(0);
        }
        else {
            basic::printf("Unknown command: '%s'", command);
        }
    }
References pciController, basic::printf(), and hardware_communication::PCI_Controller::scanBus().
Referenced by handle_key().
Member Data Documentation
m_buffer_index
int KernelShell::m_buffer_index private
Definition at line 19 of file kernel.hpp.
Referenced by KernelShell(), and handle_key().
m_line_buffer
char KernelShell::m_line_buffer[256] private
Definition at line 18 of file kernel.hpp.
Referenced by KernelShell(), and handle_key().
pciController
hardware_communication::PCI_Controller KernelShell::pciController private
Definition at line 20 of file kernel.hpp.
Referenced by process_command().
The documentation for this class was generated from the following file:
kernel.hpp