OSOS Dev: driver::TimerDriver
driver::TimerDriver abstract
Custom Driver for the 8253/8254 Programmable Interval Timer (PIT).
#include "ktimer.hpp"
Public Member Functions
TimerDriver (hardware_communication::InterruptManager *interrupt_manager, uint32_t frequency=1000)
Constructor for the Timer Driver.
~TimerDriver ()
void activate () override
Activates the timer driver and configures the hardware.
void deactivate () override
Deactivates the timer driver. (Stub)
uint32_t getFrequency () const
Gets the current frequency of the timer.
uint64_t getTicks () const
Gets the total number of ticks occurred since the driver was activated.
uint64_t getUptimeMS () const
Calculates the system uptime in milliseconds based on ticks and frequency.
uint32_t handleInterrupt (uint32_t esp) override
Handles the timer interrupt (IRQ 0).
virtual uintptr_t handleInterrupt (uintptr_t esp)=0
int reset () override
Resets the timer. (Stub)
void sleep (uint32_t milliseconds)
Pauses execution for a specific duration.
Protected Attributes
InterruptManager * interrupt_manager
uint8_t interruptNumber
Private Attributes
hardware_communication::Port8Bit commandPort
hardware_communication::Port8Bit dataPort
uint32_t frequency
volatile uint64_t ticks
Detailed Description
Custom Driver for the 8253/8254 Programmable Interval Timer (PIT).
Definition at line 18 of file ktimer.hpp.
Constructor & Destructor Documentation
TimerDriver()
TimerDriver::TimerDriver (hardware_communication::InterruptManager * interrupt_manager, uint32_t frequency = 1000)
Constructor for the Timer Driver.
Parameters
interrupt_manager Pointer to the InterruptManager.
frequency The desired frequency in Hz (e.g., 1000 for 1ms precision).
Definition at line 11 of file ktimer.cpp.
: hardware_communication::InterruptHandler(0x20, interrupt_manager), // IRQ 0 maps to 0x20
  dataPort(PIT_CHANNEL0_PORT),
  commandPort(PIT_COMMAND_PORT),
  ticks(0),
  frequency(frequency)
{
}
~TimerDriver()
TimerDriver::~TimerDriver ()
Definition at line 20 of file ktimer.cpp.
{}
Member Function Documentation
activate()
void TimerDriver::activate () override virtual
Activates the timer driver and configures the hardware.
Implements driver::Driver.
Definition at line 28 of file ktimer.cpp.
{
    // Calculate the divisor: 1193182 / Target Frequency
    uint32_t divisor = PIT_FREQUENCY_BASE / frequency;
    // Send the command byte 0x36 to Port 0x43:
    // Channel 0, Access mode: lo/hi byte, Mode 3 (Square Wave), Binary mode
    commandPort.write(0x36);
    // Send the divisor low byte
    dataPort.write((uint8_t)(divisor & 0xFF));
    // Send the divisor high byte
    dataPort.write((uint8_t)((divisor >> 8) & 0xFF));
    basic::printf("Timer Driver activated!\n");
}
References commandPort, dataPort, frequency, PIT_FREQUENCY_BASE, basic::printf(), and hardware_communication::Port8Bit::write().
deactivate()
void TimerDriver::deactivate () override virtual
Deactivates the timer driver. (Stub)
Implements driver::Driver.
Definition at line 81 of file ktimer.cpp.
{}
getFrequency()
uint32_t TimerDriver::getFrequency () const
Gets the current frequency of the timer.
Returns
The frequency in Hz.
Definition at line 64 of file ktimer.cpp.
{
    return this->frequency;
}
References frequency.
Referenced by essential::Time::getFrequency().
getTicks()
uint64_t TimerDriver::getTicks () const
Gets the total number of ticks occurred since the driver was activated.
Returns
The total tick count.
Definition at line 69 of file ktimer.cpp.
{
    return this->ticks;
}
References ticks.
getUptimeMS()
uint64_t TimerDriver::getUptimeMS () const
Calculates the system uptime in milliseconds based on ticks and frequency.
Returns
The uptime in milliseconds.
Definition at line 74 of file ktimer.cpp.
{
    if (frequency == 0) return 0;
    return (ticks * 1000) / frequency;
}
References frequency, and ticks.
Referenced by essential::Time::getUptimeMS(), task_o(), and task_X().
handleInterrupt() [1/2]
uint32_t TimerDriver::handleInterrupt (uint32_t esp) override
Handles the timer interrupt (IRQ 0).
Parameters
esp The stack pointer from the interrupt context.
Returns
The stack pointer.
Definition at line 22 of file ktimer.cpp.
{
    ticks++;
    return esp;
}
References esp, and ticks.
handleInterrupt() [2/2]
virtual uintptr_t hardware_communication::InterruptHandler::handleInterrupt (uintptr_t esp) pure virtual inherited
Referenced by hardware_communication::InterruptManager::handleInterrupt().
reset()
int TimerDriver::reset () override virtual
Resets the timer. (Stub)
Returns
Always returns 0.
Implements driver::Driver.
Definition at line 80 of file ktimer.cpp.
{ return 0; }
sleep()
void TimerDriver::sleep (uint32_t milliseconds)
Pauses execution for a specific duration.
Parameters
milliseconds The number of milliseconds to sleep.
Definition at line 46 of file ktimer.cpp.
{
    // Calculate how many ticks we need to wait
    uint64_t ticksToWait = (milliseconds * frequency) / 1000;
    uint64_t endTicks = ticks + ticksToWait;
    if (milliseconds < 10) { // 10 is just sweet number, 20ms is time quantum for thread scheduling
        while(ticks < endTicks) {
            asm volatile("hlt");
        }
    }
    else {
        while(ticks < endTicks) {
            os_yield();
        }
    }
}
References frequency, os_yield(), and ticks.
Referenced by essential::Time::sleep().
Member Data Documentation
commandPort
hardware_communication::Port8Bit driver::TimerDriver::commandPort private
Definition at line 20 of file ktimer.hpp.
Referenced by activate().
dataPort
hardware_communication::Port8Bit driver::TimerDriver::dataPort private
Definition at line 19 of file ktimer.hpp.
Referenced by activate().
frequency
uint32_t driver::TimerDriver::frequency private
Definition at line 23 of file ktimer.hpp.
Referenced by activate(), getFrequency(), getUptimeMS(), and sleep().
interrupt_manager
InterruptManager* hardware_communication::InterruptHandler::interrupt_manager protected inherited
Definition at line 30 of file kinterrupt.hpp.
Referenced by hardware_communication::InterruptHandler::InterruptHandler(), and hardware_communication::InterruptHandler::~InterruptHandler().
interruptNumber
uint8_t hardware_communication::InterruptHandler::interruptNumber protected inherited
Definition at line 29 of file kinterrupt.hpp.
Referenced by hardware_communication::InterruptHandler::InterruptHandler(), and hardware_communication::InterruptHandler::~InterruptHandler().
ticks
volatile uint64_t driver::TimerDriver::ticks private
Definition at line 22 of file ktimer.hpp.
Referenced by getTicks(), getUptimeMS(), handleInterrupt(), and sleep().
The documentation for this class was generated from the following files:
ktimer.hpp
ktimer.cpp