OSOS Dev: KernelShell
KernelShell
A simple shell/terminal manager for the kernel.
#include "kernel.hpp"
Public Member Functions
KernelShell (essential::TaskManager *osos_TaskManager_ptr, essential::Task *task1_ptr, essential::Task *task2_ptr)
~KernelShell ()
void handle_key (char c)
The single, centralized function for handling all key presses.
void process_command (const char *command)
Simple command processor.
Private Attributes
int m_buffer_index
char m_line_buffer [256]
essential::TaskManager * osos_TaskManager_ptr
hardware_communication::PCI_Controller pciController
essential::Task * task1_ptr
essential::Task * task2_ptr
Detailed Description
A simple shell/terminal manager for the kernel.
Definition at line 18 of file kernel.hpp.
Constructor & Destructor Documentation
KernelShell()
KernelShell::KernelShell (essential::TaskManager * osos_TaskManager_ptr, essential::Task * task1_ptr, essential::Task * task2_ptr) inline
Definition at line 28 of file kernel.hpp.
    {
        this->osos_TaskManager_ptr=osos_TaskManager_ptr;
        this->task1_ptr=task1_ptr;
        this->task2_ptr=task2_ptr;
        m_buffer_index = 0;
        m_line_buffer[0] = '\0';
    }
References m_buffer_index, m_line_buffer, osos_TaskManager_ptr, task1_ptr, and task2_ptr.
~KernelShell()
KernelShell::~KernelShell () inline
Definition at line 36 of file kernel.hpp.
{}
Member Function Documentation
handle_key()
void KernelShell::handle_key (char c) inline
The single, centralized function for handling all key presses.
Parameters
c The character received from any input driver (keyboard or serial driver).
Definition at line 40 of file kernel.hpp.
    {
        if (c == 0) return;
        switch(c)
        {
            // PS/2 Keyboard sends '\n' (from keyboard driver)
            // Serial sends '\r' (from serial driver)
            case '\r':
            case '\n':
                basic::printf("\n");
                m_line_buffer[m_buffer_index] = '\0';
                if (m_buffer_index > 0) {
                    process_command(m_line_buffer);
                }
                // Reset for next line
                m_buffer_index = 0;
                m_line_buffer[0] = '\0';
                basic::printf("\nOSOS> "); // Print a new prompt
                break;
            case 8: // Backspace '\b'
                if (m_buffer_index > 0){
                    m_buffer_index--;
                    m_line_buffer[m_buffer_index] = '\0';
                    basic::printf("\b \b"); // '\b' only move cursor back in serial terminal (e.g. my Ubuntu terminal), so i am printing ' ' once and then again '\b'
                }
                break;
            // Handle printable characters
            default:
                if (c >= ' ' && c <= '~' && m_buffer_index < 254)
                {
                    m_line_buffer[m_buffer_index++] = c;
                    m_line_buffer[m_buffer_index] = '\0';
                    basic::printf("%c", c);
                }
                break;
        }
    }
References m_buffer_index, m_line_buffer, basic::printf(), and process_command().
Referenced by SerialEventHandler_for_kernel::onDataReceived(), and KeyboardEventHandler_for_kernel::onKeyDown().
process_command()
void KernelShell::process_command (const char * command) inline
Simple command processor.
Parameters
command The null-terminated command string to process.
Definition at line 83 of file kernel.hpp.
    {
        if (basic::strcmp(command, "help") == 0) {
            basic::printf("OSOS Kernel Shell\n\
'lspci' : list PCI devices\n\
'task1' : start taskA\n\
'task2' : start taskB");
        }
        else if (basic::strcmp(command, "lspci") == 0) {
            basic::printf("Listing PCI devices...\n");
            pciController.scanBus(0);
        }
        else if (basic::strcmp(command, "task1") == 0) {
            basic::printf("Starting task1...\n");
            if (osos_TaskManager_ptr->addTask(task1_ptr)==false) {
                 basic::printf("Error: failed to start task1.\n");
            }
        }
        else if (basic::strcmp(command, "task2") == 0) {
            basic::printf("Starting task2...\n");
            if (osos_TaskManager_ptr->addTask(task2_ptr)==false) {
                 basic::printf("Error: failed to start task2.\n");
            }
        }
        else {
            basic::printf("Unknown command: '%s'", command);
        }
    }
References essential::TaskManager::addTask(), osos_TaskManager_ptr, pciController, basic::printf(), hardware_communication::PCI_Controller::scanBus(), basic::strcmp(), task1_ptr, and task2_ptr.
Referenced by handle_key().
Member Data Documentation
m_buffer_index
int KernelShell::m_buffer_index private
Definition at line 21 of file kernel.hpp.
Referenced by KernelShell(), and handle_key().
m_line_buffer
char KernelShell::m_line_buffer[256] private
Definition at line 20 of file kernel.hpp.
Referenced by KernelShell(), and handle_key().
osos_TaskManager_ptr
essential::TaskManager* KernelShell::osos_TaskManager_ptr private
Definition at line 23 of file kernel.hpp.
Referenced by KernelShell(), and process_command().
pciController
hardware_communication::PCI_Controller KernelShell::pciController private
Definition at line 22 of file kernel.hpp.
Referenced by process_command().
task1_ptr
essential::Task* KernelShell::task1_ptr private
Definition at line 24 of file kernel.hpp.
Referenced by KernelShell(), and process_command().
task2_ptr
essential::Task* KernelShell::task2_ptr private
Definition at line 25 of file kernel.hpp.
Referenced by KernelShell(), and process_command().
The documentation for this class was generated from the following file:
kernel.hpp