OSOS - Documentation: basic Namespace Reference
basic Namespace Reference
Functions
void __clearScreen ()
void __printMemoryMap (multiboot_info_t *mbi)
void disable_cursor ()
void enable_cursor (uint8_t cursor_start, uint8_t cursor_end)
int printf (const char *format,...)
void update_cursor (int x, int y)
Function Documentation
__clearScreen()
void basic::__clearScreen ()
Referenced by kernelMain().
__printMemoryMap()
void basic::__printMemoryMap (multiboot_info_t * mbi)
disable_cursor()
void basic::disable_cursor ()
Referenced by kernelMain().
enable_cursor()
void basic::enable_cursor (uint8_t cursor_start, uint8_t cursor_end)
Referenced by kernelMain().
printf()
int basic::printf (const char * format, ...)
Referenced by kernelMain(), and KeyboardEventHandler_for_kernel::onKeyDown().
update_cursor()
void basic::update_cursor (int x, int y)
Referenced by MouseEventHandler_for_kernel::onMouseDown().