OSOS Dev: hardware_communication::PCI_Controller
hardware_communication::PCI_Controller
Peripheral Component Interconnect Controller.
#include "kpci.hpp"
Public Member Functions
PCI_Controller ()
~PCI_Controller ()
bool deviceHasFunctions (uint16_t bus, uint16_t device)
PCI_DeviceDescriptor getDeviceDescriptor (uint16_t bus, uint16_t device, uint16_t function)
uint32_t read (uint16_t bus, uint16_t device, uint16_t function, uint32_t registerOffset)
void selectDrivers (driver::DriverManager *driver_manager)
void write (uint16_t bus, uint16_t device, uint16_t function, uint32_t registerOffset, uint32_t value)
Private Attributes
Port32Bit commandPort
Port32Bit dataPort
Detailed Description
Peripheral Component Interconnect Controller.
Definition at line 35 of file kpci.hpp.
Constructor & Destructor Documentation
PCI_Controller()
PCI_Controller::PCI_Controller ()
Definition at line 7 of file kpci.cpp.
: dataPort(0xCFC), commandPort(0xCF8) {}
~PCI_Controller()
PCI_Controller::~PCI_Controller ()
Definition at line 8 of file kpci.cpp.
{}
Member Function Documentation
deviceHasFunctions()
bool PCI_Controller::deviceHasFunctions (uint16_t bus, uint16_t device)
Definition at line 50 of file kpci.cpp.
{
    return read(bus, device, 0, 0x0E) & (1<<7);
}
References read().
Referenced by selectDrivers().
getDeviceDescriptor()
PCI_DeviceDescriptor PCI_Controller::getDeviceDescriptor (uint16_t bus, uint16_t device, uint16_t function)
Definition at line 70 of file kpci.cpp.
{
    PCI_DeviceDescriptor result;
    result.bus =        bus;
    result.device =     device;
    result.function =   function;
    result.vendorId =   read(bus, device, function, 0x00);
    result.deviceId =   read(bus, device, function, 0x02);
    result.classId =        read(bus, device, function, 0x0B);
    result.subclassId =     read(bus, device, function, 0x0A);
    result.interfaceId =    read(bus, device, function, 0x09);
    result.revision =   read(bus, device, function, 0x08);
    result.interrupt =  read(bus, device, function, 0x3C);
    return result;
}
References hardware_communication::PCI_DeviceDescriptor::bus, hardware_communication::PCI_DeviceDescriptor::classId, hardware_communication::PCI_DeviceDescriptor::device, hardware_communication::PCI_DeviceDescriptor::deviceId, hardware_communication::PCI_DeviceDescriptor::function, hardware_communication::PCI_DeviceDescriptor::interfaceId, hardware_communication::PCI_DeviceDescriptor::interrupt, read(), hardware_communication::PCI_DeviceDescriptor::revision, hardware_communication::PCI_DeviceDescriptor::subclassId, and hardware_communication::PCI_DeviceDescriptor::vendorId.
Referenced by selectDrivers().
read()
uint32_t PCI_Controller::read (uint16_t bus, uint16_t device, uint16_t function, uint32_t registerOffset)
Definition at line 11 of file kpci.cpp.
{
    uint32_t address; // address is actually exact location = which bus, which device and which registerOffset
    uint32_t lbus  = (uint32_t)bus;
    uint32_t lslot = (uint32_t)device;
    uint32_t lfunc = (uint32_t)function;
    // Create configuration address as per Figure 1
    address = 0x1<<31
            | (lbus << 16)
            | (lslot << 11)
            | (lfunc << 8)
            | (registerOffset & 0xFC) ;
    // Write out the address
    commandPort.write(address);
    // Read in the data
    uint32_t result = dataPort.read() >> (8 * (registerOffset % 4));
    return result;
}
References commandPort, dataPort, hardware_communication::Port32Bit::read(), and hardware_communication::Port32Bit::write().
Referenced by deviceHasFunctions(), and getDeviceDescriptor().
selectDrivers()
void PCI_Controller::selectDrivers (driver::DriverManager * driver_manager)
Definition at line 55 of file kpci.cpp.
{
    for(int bus=0; bus<8; bus++){
        for(int device=0; device<32; device++){
            int numFunctions = deviceHasFunctions(bus, device) ? 8 : 1;
            for(int function=0; function<numFunctions; function++){
                PCI_DeviceDescriptor dev = getDeviceDescriptor(bus, device, function);
                if(dev.vendorId == 0x0000 || dev.vendorId == 0xFFFF) continue;
                basic::printf("PCI BUS %#3x, DEVICE %#3x, FUNCTION %#3x ",bus&0xFF, device&0xFF, function&0xFF);
                basic::printf("= VENDOR %#5hx, DEVICE %#5hx\n", dev.vendorId, dev.deviceId);
            }
        }
    }
}
References deviceHasFunctions(), hardware_communication::PCI_DeviceDescriptor::deviceId, getDeviceDescriptor(), basic::printf(), and hardware_communication::PCI_DeviceDescriptor::vendorId.
Referenced by kernelMain().
write()
void PCI_Controller::write (uint16_t bus, uint16_t device, uint16_t function, uint32_t registerOffset, uint32_t value)
Definition at line 33 of file kpci.cpp.
{
    uint32_t address;
    uint32_t lbus  = (uint32_t)bus;
    uint32_t lslot = (uint32_t)device;
    uint32_t lfunc = (uint32_t)function;
    address = 0x1<<31
            | (lbus << 16)
            | (lslot << 11)
            | (lfunc << 8)
            | (registerOffset & 0xFC) ;
    commandPort.write(address);
    dataPort.write(value);
}
References commandPort, dataPort, and hardware_communication::Port32Bit::write().
Member Data Documentation
commandPort
Port32Bit hardware_communication::PCI_Controller::commandPort private
Definition at line 38 of file kpci.hpp.
Referenced by read(), and write().
dataPort
Port32Bit hardware_communication::PCI_Controller::dataPort private
Definition at line 37 of file kpci.hpp.
Referenced by read(), and write().
The documentation for this class was generated from the following files:
kpci.hpp
kpci.cpp