OSOS Dev: driver::KeyboardDriver
driver::KeyboardDriver abstract
Custom Driver for the PS/2 keyboard, handling scancodes and managing keyboard state (Shift, Caps Lock).
#include "kkeyboard.hpp"
Public Member Functions
KeyboardDriver (hardware_communication::InterruptManager *interrupt_manager, KeyboardEventHandler *keyboardEventHandler)
Constructs a new KeyboardDriver object.
~KeyboardDriver ()
void activate () override
Activates the keyboard driver.
void deactivate () override
Deactivates the keyboard driver. (Stub)
uint32_t handleInterrupt (uint32_t esp) override
Handles the keyboard interrupt (IRQ 1).
virtual uintptr_t handleInterrupt (uintptr_t esp)=0
int reset () override
Resets the keyboard. (Stub)
Protected Attributes
InterruptManager * interrupt_manager
uint8_t interruptNumber
Private Attributes
bool caps_on
hardware_communication::Port8Bit commandPort
hardware_communication::Port8Bit dataPort
KeyboardEventHandler * keyboardEventHandler
uint8_t led_byte_to_send
bool shift_pressed
bool waiting_for_led_ack
Detailed Description
Custom Driver for the PS/2 keyboard, handling scancodes and managing keyboard state (Shift, Caps Lock).
Definition at line 21 of file kkeyboard.hpp.
Constructor & Destructor Documentation
KeyboardDriver()
KeyboardDriver::KeyboardDriver (hardware_communication::InterruptManager * interrupt_manager, KeyboardEventHandler * keyboardEventHandler)
Constructs a new KeyboardDriver object.
Parameters
interrupt_manager Pointer to the interrupt manager.
keyboardEventHandler Pointer to the event handler that will process key events.
Definition at line 11 of file kkeyboard.cpp.
: hardware_communication::InterruptHandler(0x21, interrupt_manager),
  dataPort(0x60),
  commandPort(0x64),
  shift_pressed(false),
  caps_on(false),
  waiting_for_led_ack(false)
{
    this->keyboardEventHandler=keyboardEventHandler;
}
References keyboardEventHandler.
~KeyboardDriver()
KeyboardDriver::~KeyboardDriver ()
Definition at line 22 of file kkeyboard.cpp.
{}
Member Function Documentation
activate()
void KeyboardDriver::activate () override virtual
Activates the keyboard driver.
Implements driver::Driver.
Definition at line 163 of file kkeyboard.cpp.
{
    while(commandPort.read() & 1) dataPort.read();
    commandPort.write(0xAE); // activate communication for keyboard
    commandPort.write(0x20); // get current state
    uint8_t status = (dataPort.read() | 1) & ~0x10; // set LSB and clear 5th bit
    commandPort.write(0x60); // set state
    dataPort.write(status);
    dataPort.write(0xF4);
    basic::printf("Keyboard Driver activated!\n");
}
References commandPort, dataPort, basic::printf(), hardware_communication::Port8Bit::read(), and hardware_communication::Port8Bit::write().
deactivate()
void KeyboardDriver::deactivate () override virtual
Deactivates the keyboard driver. (Stub)
Implements driver::Driver.
Definition at line 177 of file kkeyboard.cpp.
{}
handleInterrupt() [1/2]
uint32_t KeyboardDriver::handleInterrupt (uint32_t esp) override
Handles the keyboard interrupt (IRQ 1).
Parameters
esp The stack pointer from the interrupt context.
Returns
The stack pointer.
Definition at line 24 of file kkeyboard.cpp.
{
    // Unshifted keys
    static const char scancode_no_shift[] = {
        0,   0, '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', '-', '=', '\b',
        '\t', 'q', 'w', 'e', 'r', 't', 'y', 'u', 'i', 'o', 'p', '[', ']', '\n',
        0, 'a', 's', 'd', 'f', 'g', 'h', 'j', 'k', 'l', ';', '\'', '`', 0,
        '\\', 'z', 'x', 'c', 'v', 'b', 'n', 'm', ',', '.', '/', 0, '*', 0,
        ' ', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0,
    };
    // Shifted keys
    static const char scancode_shifted[] = {
        0,   0, '!', '@', '#', '$', '%', '^', '&', '*', '(', ')', '_', '+', '\b',
        '\t', 'Q', 'W', 'E', 'R', 'T', 'Y', 'U', 'I', 'O', 'P', '{', '}', '\n',
        0, 'A', 'S', 'D', 'F', 'G', 'H', 'J', 'K', 'L', ':', '"', '~', 0,
        '|', 'Z', 'X', 'C', 'V', 'B', 'N', 'M', '<', '>', '?', 0, '*', 0,
        ' ', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0,
    };
    uint8_t scancode = dataPort.read();
    if(keyboardEventHandler==0) return esp; //if dont have any handler just return
    if (this->waiting_for_led_ack) {
        if (scancode == 0xFA) { // Got ACK
            dataPort.write(this->led_byte_to_send);
            this->waiting_for_led_ack = false;
        }
        // If we get something else, the keyboard is out of sync.
        // We'll just drop out of the ACK-waiting state and process
        // the scancode normally (by falling through).
        else {
             this->waiting_for_led_ack = false;
        }
        // If we got the ACK, we're done for this interrupt.
        if (scancode == 0xFA) {
            return esp;
        }
    }
    // Check for key release
    if (scancode & 0x80) {
        scancode -= 0x80;
        switch(scancode) {
            case 0x2A: // Left Shift Release
            case 0x36: // Right Shift Release
                this->shift_pressed = false;
                break;
            // Handle release of all other keys
            default: {
                char ascii = 0;
                if (scancode < sizeof(scancode_no_shift)) {
                    char base_char = scancode_no_shift[scancode];
                    // Determine the character that was released based on the keyboard state
                    if (base_char >= 'a' && base_char <= 'z') {
                        if (this->shift_pressed ^ this->caps_on) {
                            ascii = scancode_shifted[scancode];
                        } else {
                            ascii = base_char;
                        }
                    } else {
                        if (this->shift_pressed) {
                            ascii = scancode_shifted[scancode];
                        } else {
                            ascii = base_char;
                        }
                    }
                    if (ascii != 0) {
                        keyboardEventHandler->onKeyUp(ascii);
                    }
                }
                break;
            }
        }
    }
    // Check for key press
    else {
        switch(scancode) {
            case 0x2A: // Left Shift Press
            case 0x36: // Right Shift Press
                this->shift_pressed = true;
                break;
            case 0x3A: // Caps Lock Press
                this->caps_on = !this->caps_on; // Toggle the state
                // Prepare to send LED update
                this->led_byte_to_send = 0;
                if (this->caps_on) this->led_byte_to_send |= 0x04; // Bit 2 for Caps Lock LED
                dataPort.write(0xED); // Send "Set LEDs" command
                this->waiting_for_led_ack = true; // Set state to wait for ACK
                break;
            default: {
                // It's a printable key
                char ascii = 0;
                if (scancode < sizeof(scancode_no_shift)) {
                    char base_char = scancode_no_shift[scancode];
                    // Check if it's an alphabet character
                    if (base_char >= 'a' && base_char <= 'z') {
                        // It's a letter. Apply Shift XOR Caps Lock
                        // (shift ^ caps) = true means capitalize
                        if (this->shift_pressed ^ this->caps_on) {
                            ascii = scancode_shifted[scancode]; // Uppercase
                        } else {
                            ascii = base_char; // Lowercase
                        }
                    } else {
                        // It's not a letter (number, symbol, etc.)
                        // Only Shift applies
                        if (this->shift_pressed) {
                            ascii = scancode_shifted[scancode];
                        } else {
                            ascii = base_char;
                        }
                    }
                    keyboardEventHandler->onKeyDown(ascii);
                }
                break;
            }
        }
    }
    return esp;
}
References caps_on, dataPort, esp, keyboardEventHandler, led_byte_to_send, driver::KeyboardEventHandler::onKeyDown(), driver::KeyboardEventHandler::onKeyUp(), hardware_communication::Port8Bit::read(), shift_pressed, waiting_for_led_ack, and hardware_communication::Port8Bit::write().
handleInterrupt() [2/2]
virtual uintptr_t hardware_communication::InterruptHandler::handleInterrupt (uintptr_t esp) pure virtual inherited
Referenced by hardware_communication::InterruptManager::handleInterrupt().
reset()
int KeyboardDriver::reset () override virtual
Resets the keyboard. (Stub)
Returns
Always returns 0.
Implements driver::Driver.
Definition at line 175 of file kkeyboard.cpp.
{return 0;}
Member Data Documentation
caps_on
bool driver::KeyboardDriver::caps_on private
Definition at line 25 of file kkeyboard.hpp.
Referenced by handleInterrupt().
commandPort
hardware_communication::Port8Bit driver::KeyboardDriver::commandPort private
Definition at line 23 of file kkeyboard.hpp.
Referenced by activate().
dataPort
hardware_communication::Port8Bit driver::KeyboardDriver::dataPort private
Definition at line 22 of file kkeyboard.hpp.
Referenced by activate(), and handleInterrupt().
interrupt_manager
InterruptManager* hardware_communication::InterruptHandler::interrupt_manager protected inherited
Definition at line 28 of file kinterrupt.hpp.
Referenced by hardware_communication::InterruptHandler::InterruptHandler(), and hardware_communication::InterruptHandler::~InterruptHandler().
interruptNumber
uint8_t hardware_communication::InterruptHandler::interruptNumber protected inherited
Definition at line 27 of file kinterrupt.hpp.
Referenced by hardware_communication::InterruptHandler::InterruptHandler(), and hardware_communication::InterruptHandler::~InterruptHandler().
keyboardEventHandler
KeyboardEventHandler* driver::KeyboardDriver::keyboardEventHandler private
Definition at line 28 of file kkeyboard.hpp.
Referenced by KeyboardDriver(), and handleInterrupt().
led_byte_to_send
uint8_t driver::KeyboardDriver::led_byte_to_send private
Definition at line 27 of file kkeyboard.hpp.
Referenced by handleInterrupt().
shift_pressed
bool driver::KeyboardDriver::shift_pressed private
Definition at line 24 of file kkeyboard.hpp.
Referenced by handleInterrupt().
waiting_for_led_ack
bool driver::KeyboardDriver::waiting_for_led_ack private
Definition at line 26 of file kkeyboard.hpp.
Referenced by handleInterrupt().
The documentation for this class was generated from the following files:
kkeyboard.hpp
kkeyboard.cpp