OSOS Dev: driver::amd_am79c973
driver::amd_am79c973 abstract
#include "kamd79c973.hpp"
Classes
struct BufferDescriptor
struct InitializationBlock
Public Member Functions
amd_am79c973 (hardware_communication::PCI_DeviceDescriptor *dev, hardware_communication::InterruptManager *interrupts)
~amd_am79c973 ()
void activate ()
void deactivate ()
uint32_t getIPAddress ()
uint64_t getMACAddress ()
uint32_t handleInterrupt (uint32_t esp)
virtual uintptr_t handleInterrupt (uintptr_t esp)=0
void receive ()
int reset ()
void send (uint8_t *buffer, int count)
void setHandler (RawDataHandler *handler)
void setIPAddress (uint32_t)
Protected Attributes
InterruptManager * interrupt_manager
uint8_t interruptNumber
Private Member Functions
struct driver::amd_am79c973::InitializationBlock __attribute__ ((packed))
struct driver::amd_am79c973::BufferDescriptor __attribute__ ((packed))
Private Attributes
hardware_communication::Port16Bit busControlRegisterDataPort
uint8_t currentRecvBuffer
uint8_t currentSendBuffer
RawDataHandler * handler
InitializationBlock initBlock
hardware_communication::Port16Bit MACAddress0Port
hardware_communication::Port16Bit MACAddress2Port
hardware_communication::Port16Bit MACAddress4Port
BufferDescriptor * recvBufferDescr
uint8_t recvBufferDescrMemory [2048+15]
uint8_t recvBuffers [2 *1024+15][8]
hardware_communication::Port16Bit registerAddressPort
hardware_communication::Port16Bit registerDataPort
hardware_communication::Port16Bit resetPort
BufferDescriptor * sendBufferDescr
uint8_t sendBufferDescrMemory [2048+15]
uint8_t sendBuffers [2 *1024+15][8]
Detailed Description
Definition at line 26 of file kamd79c973.hpp.
Class Documentation
driver::amd_am79c973::BufferDescriptor
struct driver::amd_am79c973::BufferDescriptor
Definition at line 42 of file kamd79c973.hpp.
Class Members
uint32_t address
uint32_t avail
uint32_t flags
uint32_t flags2
driver::amd_am79c973::InitializationBlock
struct driver::amd_am79c973::InitializationBlock
Definition at line 28 of file kamd79c973.hpp.
Class Members
uint64_t logicalAddress
uint16_t mode
unsigned numRecvBuffers: 4
unsigned numSendBuffers: 4
uint64_t physicalAddress: 48
uint32_t recvBufferDescrAddress
unsigned reserved1: 4
unsigned reserved2: 4
uint16_t reserved3
uint32_t sendBufferDescrAddress
Constructor & Destructor Documentation
amd_am79c973()
amd_am79c973::amd_am79c973 (hardware_communication::PCI_DeviceDescriptor * dev, hardware_communication::InterruptManager * interrupts)
Definition at line 33 of file kamd79c973.cpp.
:   hardware_communication::InterruptHandler(dev->interrupt + 0x20, interrupt_manager),
    MACAddress0Port(dev->portBase[0]),
    MACAddress2Port(dev->portBase[0] + 0x02),
    MACAddress4Port(dev->portBase[0] + 0x04),
    registerDataPort(dev->portBase[0] + 0x10),
    registerAddressPort(dev->portBase[0] + 0x12),
    resetPort(dev->portBase[0] + 0x14),
    busControlRegisterDataPort(dev->portBase[0] + 0x16)
{
    this->handler = 0;
    currentSendBuffer = 0;
    currentRecvBuffer = 0;
    uint64_t MAC0 = MACAddress0Port.read() % 256;
    uint64_t MAC1 = MACAddress0Port.read() / 256;
    uint64_t MAC2 = MACAddress2Port.read() % 256;
    uint64_t MAC3 = MACAddress2Port.read() / 256;
    uint64_t MAC4 = MACAddress4Port.read() % 256;
    uint64_t MAC5 = MACAddress4Port.read() / 256;
    uint64_t MAC = MAC5 << 40
                 | MAC4 << 32
                 | MAC3 << 24
                 | MAC2 << 16
                 | MAC1 << 8
                 | MAC0;
    // 32 bit mode
    registerAddressPort.write(20);
    busControlRegisterDataPort.write(0x102);
    // STOP reset
    registerAddressPort.write(0);
    registerDataPort.write(0x04);
    // initBlock
    initBlock.mode = 0x0000; // promiscuous mode = false
    initBlock.reserved1 = 0;
    initBlock.numSendBuffers = 3;
    initBlock.reserved2 = 0;
    initBlock.numRecvBuffers = 3;
    initBlock.physicalAddress = MAC;
    initBlock.reserved3 = 0;
    initBlock.logicalAddress = 0;
    sendBufferDescr = (BufferDescriptor*)((((uint32_t)&sendBufferDescrMemory[0]) + 15) & ~((uint32_t)0xF));
    initBlock.sendBufferDescrAddress = (uint32_t)sendBufferDescr;
    recvBufferDescr = (BufferDescriptor*)((((uint32_t)&recvBufferDescrMemory[0]) + 15) & ~((uint32_t)0xF));
    initBlock.recvBufferDescrAddress = (uint32_t)recvBufferDescr;
    for(uint8_t i = 0; i < 8; i++)
    {
        sendBufferDescr[i].address = (((uint32_t)&sendBuffers[i]) + 15 ) & ~(uint32_t)0xF;
        sendBufferDescr[i].flags = 0x7FF
                                 | 0xF000;
        sendBufferDescr[i].flags2 = 0;
        sendBufferDescr[i].avail = 0;
        recvBufferDescr[i].address = (((uint32_t)&recvBuffers[i]) + 15 ) & ~(uint32_t)0xF;
        recvBufferDescr[i].flags = 0xF7FF
                                 | 0x80000000;
        recvBufferDescr[i].flags2 = 0;
        sendBufferDescr[i].avail = 0;
    }
    registerAddressPort.write(1);
    registerDataPort.write(  (uint32_t)(&initBlock) & 0xFFFF );
    registerAddressPort.write(2);
    registerDataPort.write(  ((uint32_t)(&initBlock) >> 16) & 0xFFFF );
}
References driver::amd_am79c973::BufferDescriptor::address, driver::amd_am79c973::BufferDescriptor::avail, busControlRegisterDataPort, currentRecvBuffer, currentSendBuffer, driver::amd_am79c973::BufferDescriptor::flags, driver::amd_am79c973::BufferDescriptor::flags2, handler, initBlock, driver::amd_am79c973::InitializationBlock::logicalAddress, MACAddress0Port, MACAddress2Port, MACAddress4Port, driver::amd_am79c973::InitializationBlock::mode, driver::amd_am79c973::InitializationBlock::numRecvBuffers, driver::amd_am79c973::InitializationBlock::numSendBuffers, driver::amd_am79c973::InitializationBlock::physicalAddress, hardware_communication::Port16Bit::read(), recvBufferDescr, driver::amd_am79c973::InitializationBlock::recvBufferDescrAddress, recvBufferDescrMemory, recvBuffers, registerAddressPort, registerDataPort, driver::amd_am79c973::InitializationBlock::reserved1, driver::amd_am79c973::InitializationBlock::reserved2, driver::amd_am79c973::InitializationBlock::reserved3, sendBufferDescr, driver::amd_am79c973::InitializationBlock::sendBufferDescrAddress, sendBufferDescrMemory, sendBuffers, and hardware_communication::Port16Bit::write().
~amd_am79c973()
amd_am79c973::~amd_am79c973 ()
Definition at line 106 of file kamd79c973.cpp.
{}
Member Function Documentation
__attribute__() [1/2]
struct driver::amd_am79c973::InitializationBlock driver::amd_am79c973::__attribute__ ((packed)) private
__attribute__() [2/2]
struct driver::amd_am79c973::BufferDescriptor driver::amd_am79c973::__attribute__ ((packed)) private
activate()
void amd_am79c973::activate () virtual
Implements driver::Driver.
Definition at line 108 of file kamd79c973.cpp.
{
    registerAddressPort.write(0);
    registerDataPort.write(0x41);
    registerAddressPort.write(4);
    uint32_t temp = registerDataPort.read();
    registerAddressPort.write(4);
    registerDataPort.write(temp | 0xC00);
    registerAddressPort.write(0);
    registerDataPort.write(0x42);
    printf("Network Driver activated!\n");
}
References basic::printf(), hardware_communication::Port16Bit::read(), registerAddressPort, registerDataPort, and hardware_communication::Port16Bit::write().
deactivate()
void amd_am79c973::deactivate () virtual
Implements driver::Driver.
Definition at line 131 of file kamd79c973.cpp.
{}
getIPAddress()
uint32_t amd_am79c973::getIPAddress ()
Definition at line 227 of file kamd79c973.cpp.
{
    return initBlock.logicalAddress;
}
References initBlock, and driver::amd_am79c973::InitializationBlock::logicalAddress.
Referenced by net::EtherFrameProvider::getIPAddress().
getMACAddress()
uint64_t amd_am79c973::getMACAddress ()
Definition at line 217 of file kamd79c973.cpp.
{
    return initBlock.physicalAddress;
}
References initBlock, and driver::amd_am79c973::InitializationBlock::physicalAddress.
Referenced by net::EtherFrameProvider::getMACAddress(), net::EtherFrameProvider::onRawDataReceived(), and net::EtherFrameProvider::send().
handleInterrupt() [1/2]
uint32_t amd_am79c973::handleInterrupt (uint32_t esp)
Definition at line 133 of file kamd79c973.cpp.
{
    registerAddressPort.write(0);
    uint32_t temp = registerDataPort.read();
    if((temp & 0x8000) == 0x8000) printf("AMD am79c973 ERROR\n");
    if((temp & 0x2000) == 0x2000) printf("AMD am79c973 COLLISION ERROR\n");
    if((temp & 0x1000) == 0x1000) printf("AMD am79c973 MISSED FRAME\n");
    if((temp & 0x0800) == 0x0800) printf("AMD am79c973 MEMORY ERROR\n");
    if((temp & 0x0400) == 0x0400) receive();
    if((temp & 0x0200) == 0x0200) printf(" SENT");
    // acknoledge
    registerAddressPort.write(0);
    registerDataPort.write(temp);
    if((temp & 0x0100) == 0x0100) printf("AMD am79c973 INIT DONE\n");
    return esp;
}
References esp, basic::printf(), hardware_communication::Port16Bit::read(), receive(), registerAddressPort, registerDataPort, and hardware_communication::Port16Bit::write().
handleInterrupt() [2/2]
virtual uintptr_t hardware_communication::InterruptHandler::handleInterrupt (uintptr_t esp) pure virtual inherited
Referenced by hardware_communication::InterruptManager::handleInterrupt().
receive()
void amd_am79c973::receive ()
Definition at line 179 of file kamd79c973.cpp.
{
    printf("\nRECV: ");
    for(; (recvBufferDescr[currentRecvBuffer].flags & 0x80000000) == 0;
        currentRecvBuffer = (currentRecvBuffer + 1) % 8)
    {
        if(!(recvBufferDescr[currentRecvBuffer].flags & 0x40000000)
         && (recvBufferDescr[currentRecvBuffer].flags & 0x03000000) == 0x03000000)
        {
            uint32_t size = recvBufferDescr[currentRecvBuffer].flags & 0xFFF;
            if(size > 64) // remove checksum
                size -= 4;
            uint8_t* buffer = (uint8_t*)(recvBufferDescr[currentRecvBuffer].address);
            for(uint32_t i = 14+20; i < (size>64?64:size); i++)
            {
                printf("%x",buffer[i]);
                printf(" ");
            }
            if(handler != 0)
                if(handler->onRawDataReceived(buffer, size))
                    send(buffer, size);
        }
        recvBufferDescr[currentRecvBuffer].flags2 = 0;
        recvBufferDescr[currentRecvBuffer].flags = 0x8000F7FF;
    }
}
References address, currentRecvBuffer, flags, driver::amd_am79c973::BufferDescriptor::flags, driver::amd_am79c973::BufferDescriptor::flags2, handler, driver::RawDataHandler::onRawDataReceived(), basic::printf(), recvBufferDescr, send(), and size.
Referenced by handleInterrupt().
reset()
int amd_am79c973::reset () virtual
Implements driver::Driver.
Definition at line 124 of file kamd79c973.cpp.
{
    resetPort.read();
    resetPort.write(0);
    return 10;
}
References hardware_communication::Port16Bit::read(), resetPort, and hardware_communication::Port16Bit::write().
send()
void amd_am79c973::send (uint8_t * buffer, int count)
Definition at line 155 of file kamd79c973.cpp.
{
    int sendDescriptor = currentSendBuffer;
    currentSendBuffer = (currentSendBuffer + 1) % 8;
    if(size > 1518) size = 1518;
    for(uint8_t *src = buffer + size -1,
                *dst = (uint8_t*)(sendBufferDescr[sendDescriptor].address + size -1);
                src >= buffer; src--, dst--) *dst = *src;
    printf("\nSEND: ");
    for(int i = 14+20; i < (size>64?64:size); i++)
    {
        printf("%x",buffer[i]);
    }
    sendBufferDescr[sendDescriptor].avail = 0;
    sendBufferDescr[sendDescriptor].flags2 = 0;
    sendBufferDescr[sendDescriptor].flags = 0x8300F000 | ((uint16_t)((-size) & 0xFFF));
    registerAddressPort.write(0);
    registerDataPort.write(0x48);
}
References driver::amd_am79c973::BufferDescriptor::address, driver::amd_am79c973::BufferDescriptor::avail, currentSendBuffer, driver::amd_am79c973::BufferDescriptor::flags, driver::amd_am79c973::BufferDescriptor::flags2, basic::printf(), registerAddressPort, registerDataPort, sendBufferDescr, size, and hardware_communication::Port16Bit::write().
Referenced by receive(), net::EtherFrameProvider::send(), and driver::RawDataHandler::send().
setHandler()
void amd_am79c973::setHandler (RawDataHandler * handler)
Definition at line 212 of file kamd79c973.cpp.
{
    this->handler = handler;
}
References handler.
Referenced by driver::RawDataHandler::RawDataHandler(), and driver::RawDataHandler::~RawDataHandler().
setIPAddress()
void amd_am79c973::setIPAddress (uint32_t ip)
Definition at line 222 of file kamd79c973.cpp.
{
    initBlock.logicalAddress = ip;
}
References initBlock, and driver::amd_am79c973::InitializationBlock::logicalAddress.
Member Data Documentation
busControlRegisterDataPort
hardware_communication::Port16Bit driver::amd_am79c973::busControlRegisterDataPort private
Definition at line 56 of file kamd79c973.hpp.
Referenced by amd_am79c973().
currentRecvBuffer
uint8_t driver::amd_am79c973::currentRecvBuffer private
Definition at line 68 of file kamd79c973.hpp.
Referenced by amd_am79c973(), and receive().
currentSendBuffer
uint8_t driver::amd_am79c973::currentSendBuffer private
Definition at line 63 of file kamd79c973.hpp.
Referenced by amd_am79c973(), and send().
handler
RawDataHandler* driver::amd_am79c973::handler private
Definition at line 70 of file kamd79c973.hpp.
Referenced by amd_am79c973(), receive(), and setHandler().
initBlock
InitializationBlock driver::amd_am79c973::initBlock private
Definition at line 58 of file kamd79c973.hpp.
Referenced by amd_am79c973(), getIPAddress(), getMACAddress(), and setIPAddress().
interrupt_manager
InterruptManager* hardware_communication::InterruptHandler::interrupt_manager protected inherited
Definition at line 29 of file kinterrupt.hpp.
Referenced by hardware_communication::InterruptHandler::InterruptHandler(), and hardware_communication::InterruptHandler::~InterruptHandler().
interruptNumber
uint8_t hardware_communication::InterruptHandler::interruptNumber protected inherited
Definition at line 28 of file kinterrupt.hpp.
Referenced by hardware_communication::InterruptHandler::InterruptHandler(), and hardware_communication::InterruptHandler::~InterruptHandler().
MACAddress0Port
hardware_communication::Port16Bit driver::amd_am79c973::MACAddress0Port private
Definition at line 50 of file kamd79c973.hpp.
Referenced by amd_am79c973().
MACAddress2Port
hardware_communication::Port16Bit driver::amd_am79c973::MACAddress2Port private
Definition at line 51 of file kamd79c973.hpp.
Referenced by amd_am79c973().
MACAddress4Port
hardware_communication::Port16Bit driver::amd_am79c973::MACAddress4Port private
Definition at line 52 of file kamd79c973.hpp.
Referenced by amd_am79c973().
recvBufferDescr
BufferDescriptor* driver::amd_am79c973::recvBufferDescr private
Definition at line 65 of file kamd79c973.hpp.
Referenced by amd_am79c973(), and receive().
recvBufferDescrMemory
uint8_t driver::amd_am79c973::recvBufferDescrMemory[2048+15] private
Definition at line 66 of file kamd79c973.hpp.
Referenced by amd_am79c973().
recvBuffers
uint8_t driver::amd_am79c973::recvBuffers[2 *1024+15][8] private
Definition at line 67 of file kamd79c973.hpp.
Referenced by amd_am79c973().
registerAddressPort
hardware_communication::Port16Bit driver::amd_am79c973::registerAddressPort private
Definition at line 54 of file kamd79c973.hpp.
Referenced by amd_am79c973(), activate(), handleInterrupt(), and send().
registerDataPort
hardware_communication::Port16Bit driver::amd_am79c973::registerDataPort private
Definition at line 53 of file kamd79c973.hpp.
Referenced by amd_am79c973(), activate(), handleInterrupt(), and send().
resetPort
hardware_communication::Port16Bit driver::amd_am79c973::resetPort private
Definition at line 55 of file kamd79c973.hpp.
Referenced by reset().
sendBufferDescr
BufferDescriptor* driver::amd_am79c973::sendBufferDescr private
Definition at line 60 of file kamd79c973.hpp.
Referenced by amd_am79c973(), and send().
sendBufferDescrMemory
uint8_t driver::amd_am79c973::sendBufferDescrMemory[2048+15] private
Definition at line 61 of file kamd79c973.hpp.
Referenced by amd_am79c973().
sendBuffers
uint8_t driver::amd_am79c973::sendBuffers[2 *1024+15][8] private
Definition at line 62 of file kamd79c973.hpp.
Referenced by amd_am79c973().
The documentation for this class was generated from the following files:
kamd79c973.hpp
kamd79c973.cpp