OSOS - Documentation: hardware_communication::Port8Bit
hardware_communication::Port8Bit
#include "kport.hpp"
Public Member Functions
Port8Bit (uint16_t portnumber)
virtual ~Port8Bit () override
uint8_t read ()
virtual void write (uint8_t data)
Protected Attributes
uint16_t portnumber
Detailed Description
Definition at line 30 of file kport.hpp.
Constructor & Destructor Documentation
Port8Bit()
hardware_communication::Port8Bit::Port8Bit (uint16_t portnumber) explicit
Definition at line 10 of file kport.cpp.
:Port(portnumber){}
~Port8Bit()
hardware_communication::Port8Bit::~Port8Bit () override virtual
Definition at line 11 of file kport.cpp.
{}
Member Function Documentation
read()
uint8_t hardware_communication::Port8Bit::read ()
Definition at line 16 of file kport.cpp.
{
    uint8_t result;
    __asm__ volatile("inb %1, %0" :"=a"(result) : "Nd"(portnumber));
    return result;
}
Referenced by basic::enable_cursor().
write()
void hardware_communication::Port8Bit::write (uint8_t data) virtual
Reimplemented in hardware_communication::Port8BitSlow.
Definition at line 13 of file kport.cpp.
{
    __asm__ volatile("outb %0, %1" : : "a"(data), "Nd"(portnumber));
}
Referenced by basic::disable_cursor(), basic::enable_cursor(), and basic::update_cursor().
Member Data Documentation
portnumber
uint16_t hardware_communication::Port::portnumber protected inherited
Definition at line 13 of file kport.hpp.
Referenced by hardware_communication::Port::Port().
The documentation for this class was generated from the following files:
libk_header/hardware_communication/kport.hpp
libk_src/hardware_communication/kport.cpp