OSOS Dev: memory::HeapManager
memory::HeapManager
#include "kheap.hpp"
Public Member Functions
HeapManager ()
void * allocate (size_t size)
Allocate memory from this specific heap.
void free (void *ptr)
Free memory back to this specific heap.
void init (void *startAddress, size_t sizeTotal)
Initialize this specific heap instance.
void printHeapInfo ()
Print debug info for this heap.
Private Attributes
MemoryBlockHeader * head
Detailed Description
Definition at line 15 of file kheap.hpp.
Constructor & Destructor Documentation
HeapManager()
memory::HeapManager::HeapManager () inline
Definition at line 20 of file kheap.hpp.
: head(nullptr) {}
Member Function Documentation
allocate()
void * memory::HeapManager::allocate (size_t size)
Allocate memory from this specific heap.
Definition at line 19 of file kheap.cpp.
{
        MemoryBlockHeader* current = head;
        while (current != nullptr) {
            if (current->is_free && current->size >= size) {
                if (current->size > size + sizeof(MemoryBlockHeader) + 1) {
                    MemoryBlockHeader* newBlock = (MemoryBlockHeader*)((uintptr_t)current + sizeof(MemoryBlockHeader) + size);
                    newBlock->size = current->size - size - sizeof(MemoryBlockHeader);
                    newBlock->is_free = true;
                    newBlock->next = current->next;
                    newBlock->prev = current;
                    current->size = size;
                    current->is_free = false;
                    current->next = newBlock;
                    if (newBlock->next != nullptr) {
                        newBlock->next->prev = newBlock;
                    }
                } else {
                    current->is_free = false;
                }
                return (void*)((uintptr_t)current + sizeof(MemoryBlockHeader));
            }
            current = current->next;
        }
        basic::printf("Heap OOM: Cannot allocate %d bytes\n", size);
        return nullptr;
    }
References head, memory::MemoryBlockHeader::is_free, memory::MemoryBlockHeader::next, memory::MemoryBlockHeader::prev, basic::printf(), and memory::MemoryBlockHeader::size.
Referenced by malloc(), operator new(), and operator new[]().
free()
void memory::HeapManager::free (void * ptr)
Free memory back to this specific heap.
Definition at line 52 of file kheap.cpp.
{
        if (!ptr) return;
        // move pointer back to get the header
        MemoryBlockHeader* block = (MemoryBlockHeader*)((uintptr_t)ptr - sizeof(MemoryBlockHeader));
        // mark it as free
        block->is_free = true;
        // merge with next block if it is free
        if (block->next != nullptr && block->next->is_free) {
            block->size += block->next->size + sizeof(MemoryBlockHeader);
            block->next = block->next->next;
            if (block->next != nullptr) {
                block->next->prev = block;
            }
        }
        // merge with previous block if it is free
        if (block->prev != nullptr && block->prev->is_free) {
            block->prev->size += block->size + sizeof(MemoryBlockHeader);
            block->prev->next = block->next;
            if (block->next != nullptr) {
                block->next->prev = block->prev;
            }
        }
    }
References memory::MemoryBlockHeader::is_free, memory::MemoryBlockHeader::next, memory::MemoryBlockHeader::prev, and memory::MemoryBlockHeader::size.
Referenced by free(), operator delete(), operator delete(), operator delete[](), and operator delete[]().
init()
void memory::HeapManager::init (void * startAddress, size_t sizeTotal)
Initialize this specific heap instance.
Parameters
startAddress Virtual address where this heap begins.
sizeTotal Total size of the heap (in bytes).
Definition at line 9 of file kheap.cpp.
{
        head = (MemoryBlockHeader*)startAddress;
        head->size = sizeTotal - sizeof(MemoryBlockHeader);
        head->is_free = true;
        head->next = nullptr;
        head->prev = nullptr;
        basic::printf("Heap Initialized at 0x%x (Size: %d bytes)\n", startAddress, sizeTotal);
    }
References head, memory::MemoryBlockHeader::is_free, memory::MemoryBlockHeader::next, memory::MemoryBlockHeader::prev, basic::printf(), and memory::MemoryBlockHeader::size.
Referenced by kernelMain().
printHeapInfo()
void memory::HeapManager::printHeapInfo ()
Print debug info for this heap.
Definition at line 80 of file kheap.cpp.
{
        MemoryBlockHeader* current = head;
        size_t total_free = 0;
        int i=0;
        while (current != nullptr) {
            if (current->is_free) total_free += current->size;
            basic::printf("Block %-2d: %s, Size(B): %-7d, Addr: 0x%x\n", i++, current->is_free ? "FREE" : "USED", current->size, current);
            current = current->next;
        }
        basic::printf("Total Free Heap: %d B\n", total_free);
    }
References head, memory::MemoryBlockHeader::is_free, memory::MemoryBlockHeader::next, basic::printf(), and memory::MemoryBlockHeader::size.
Referenced by KernelShell::process_command().
Member Data Documentation
head
MemoryBlockHeader* memory::HeapManager::head private
Definition at line 17 of file kheap.hpp.
Referenced by allocate(), init(), and printHeapInfo().
The documentation for this class was generated from the following files:
kheap.hpp
kheap.cpp