OSOS Dev: memory::PagingManager
memory::PagingManager
Manages Virtual Memory via x86 Paging. Supports switching between multiple Page Directories for multitasking.
#include "kpaging.hpp"
Static Public Member Functions
static void * getPhysicalAddress (void *virtualAddress)
Resolves a Virtual Address to its Physical Address using the CURRENTLY active Page Directory.
static void init ()
Initializes the Paging system. Creates the Master Kernel Directory, maps Kernel memory (0-16MB), and enables paging.
static void printPageDirectory ()
Prints the currently active Page Directory entries.
static void switchPageDirectory (uint32_t *newDirectory)
Loads a specific Page Directory into the CR3 register. This effectively switches the "Memory View" for the CPU.
Static Public Attributes
static uint32_t * activePageDirectory = nullptr
static uint32_t * kernelPageDirectory = nullptr
Detailed Description
Manages Virtual Memory via x86 Paging. Supports switching between multiple Page Directories for multitasking.
Definition at line 10 of file kpaging.hpp.
Member Function Documentation
getPhysicalAddress()
void * memory::PagingManager::getPhysicalAddress (void * virtualAddress) static
Resolves a Virtual Address to its Physical Address using the CURRENTLY active Page Directory.
Definition at line 81 of file kpaging.cpp.
{
        uintptr_t vAddr = (uintptr_t)virtualAddress;
        uint32_t pdIndex = vAddr >> 22;
        uint32_t ptIndex = (vAddr >> 12) & 0x03FF;
        uint32_t offset  = vAddr & 0x0FFF;
        // Check Page Directory Entry
        // We use activePageDirectory because that's what the CPU is seeing right now
        if ((activePageDirectory[pdIndex] & 0x1) == 0) {
            return nullptr;
        }
        // Get the Page Table address (mask out flags)
        uint32_t* pageTable = (uint32_t*)(activePageDirectory[pdIndex] & 0xFFFFF000);
        // Check Page Table Entry
        if ((pageTable[ptIndex] & 0x1) == 0) {
            return nullptr;
        }
        uint32_t physicalFrame = pageTable[ptIndex] & 0xFFFFF000;
        return (void*)(uintptr_t)(physicalFrame + offset);
    }
References activePageDirectory.
init()
void memory::PagingManager::init () static
Initializes the Paging system. Creates the Master Kernel Directory, maps Kernel memory (0-16MB), and enables paging.
Definition at line 23 of file kpaging.cpp.
{
        basic::printf("Initializing Paging...\n");
        kernelPageDirectory = (uint32_t*)memory::PhysicalMemoryManager::allocate_block();
        // Clear it (Set all to "Not Present"), Attributes: Supervisor (User=0), RW=1, Present=0 -> 0x00000002
        for(int i = 0; i < 1024; i++) {
            kernelPageDirectory[i] = 0x00000002;
        }
        // Identity Map the first 16MB of RAM (Kernel Space). This ensures the Kernel code, PMM bitmap, and these Tables are accessible.
        uint32_t currentPhysicalAddress = 0;
        for (int pdIndex = 0; pdIndex < 4; pdIndex++) {
            // Allocate a Page Table for this 4MB region
            uint32_t* pt = (uint32_t*)memory::PhysicalMemoryManager::allocate_block();
            // Fill the table (1024 entries * 4KB = 4MB)
            for(int ptIndex = 0; ptIndex < 1024; ptIndex++) {
                // Attributes: Supervisor, RW, Present (0x3)
                pt[ptIndex] = currentPhysicalAddress | 3;
                currentPhysicalAddress += 4096;
            }
            // Install the Table into the Kernel Directory
            kernelPageDirectory[pdIndex] = (uint32_t)pt | 3;
        }
        // Map the Heap Area (16MB to 24MB) = 8MB Heap
        // We continue from where 'currentPhysicalAddress' left off (at 16MB).
        // pdIndex 4 covers 16MB-20MB
        // pdIndex 5 covers 20MB-24MB
        for (int i = 0; i < 2; i++) {
            uint32_t* pt = (uint32_t*)memory::PhysicalMemoryManager::allocate_block();
            for(int ptIndex = 0; ptIndex < 1024; ptIndex++) {
                pt[ptIndex] = currentPhysicalAddress | 3;
                currentPhysicalAddress += 4096;
            }
            // Register at index 4 + i (Indices 4 and 5)
            kernelPageDirectory[4 + i] = (uint32_t)pt | 3;
        }
        // Activate the Kernel Directory
        switchPageDirectory(kernelPageDirectory);
        // Turn on the CPU Paging Unit
        asm_enablePagingMode();
        basic::printf("Paging Enabled! (Mapped 0-24MB)\n");
    }
References memory::PhysicalMemoryManager::allocate_block(), memory::asm_enablePagingMode(), kernelPageDirectory, basic::printf(), and switchPageDirectory().
Referenced by kernelMain().
printPageDirectory()
void memory::PagingManager::printPageDirectory () static
Prints the currently active Page Directory entries.
Definition at line 106 of file kpaging.cpp.
{
        if (!activePageDirectory) return;
        basic::printf("\n--- Active Page Directory Entries ---\n");
        for (int i = 0; i < 1024; i++) {
            // Check Present Bit (Bit 0)
            if (activePageDirectory[i] & 1) {
                basic::printf("Index %d: Mapped to Table at 0x%x (Flags: 0x%x)\n",
                    i,
                    activePageDirectory[i] & 0xFFFFF000,
                    activePageDirectory[i] & 0xFFF
                );
            }
        }
        basic::printf("-------------------------------------\n");
    }
References activePageDirectory, and basic::printf().
Referenced by KernelShell::process_command().
switchPageDirectory()
void memory::PagingManager::switchPageDirectory (uint32_t * newDirectory) static
Loads a specific Page Directory into the CR3 register. This effectively switches the "Memory View" for the CPU.
Parameters
newDirectory Pointer to the Page Directory to load.
Definition at line 76 of file kpaging.cpp.
{
        activePageDirectory = newDirectory;
        asm_loadPageDirectory(activePageDirectory);
    }
References activePageDirectory, and memory::asm_loadPageDirectory().
Referenced by init().
Member Data Documentation
activePageDirectory
uint32_t * memory::PagingManager::activePageDirectory = nullptr static
Definition at line 29 of file kpaging.hpp.
Referenced by getPhysicalAddress(), printPageDirectory(), and switchPageDirectory().
kernelPageDirectory
uint32_t * memory::PagingManager::kernelPageDirectory = nullptr static
Definition at line 26 of file kpaging.hpp.
Referenced by init().
The documentation for this class was generated from the following files:
kpaging.hpp
kpaging.cpp