OSOS - Documentation: hardware_communication::InterruptManager
hardware_communication::InterruptManager
Manages the Interrupt Descriptor Table (IDT) and Programmable Interrupt Controllers (PICs), dispatching interrupts to registered handlers.
#include "kinterrupt.hpp"
Public Member Functions
InterruptManager (essential::GDT *gdt)
~InterruptManager ()
void installTable ()
Static Public Member Functions
static void activate ()
static void deactivate ()
static uintptr_t handleInterrupt (uint8_t interruptNumber, uintptr_t esp)
static void printLoadedTable ()
static void printLoadedTableHeader ()
Public Attributes
uint32_t base
uint16_t limit
Protected Member Functions
void setIDTEntry (uint8_t interruptNumber, uint16_t codeSegmentSelectorOffset, void(*handler)(), uint8_t DescriptorPrivilegeLever, uint8_t DescriptorType)
Protected Attributes
InterruptHandler * handlers [256]
IDT_row interruptDescriptorTable [256]
Static Protected Attributes
static hardware_communication::Port8BitSlow picMasterCommand
static hardware_communication::Port8BitSlow picMasterData
static hardware_communication::Port8BitSlow picSlaveCommand
static hardware_communication::Port8BitSlow picSlaveData
Detailed Description
Manages the Interrupt Descriptor Table (IDT) and Programmable Interrupt Controllers (PICs), dispatching interrupts to registered handlers.
Definition at line 47 of file kinterrupt.hpp.
Constructor & Destructor Documentation
InterruptManager()
hardware_communication::InterruptManager::InterruptManager (essential::GDT * gdt)
~InterruptManager()
hardware_communication::InterruptManager::~InterruptManager ()
Member Function Documentation
activate()
static void hardware_communication::InterruptManager::activate () static
Referenced by kernelMain().
deactivate()
static void hardware_communication::InterruptManager::deactivate () static
handleInterrupt()
static uintptr_t hardware_communication::InterruptManager::handleInterrupt (uint8_t interruptNumber, uintptr_t esp) static
installTable()
void hardware_communication::InterruptManager::installTable ()
Referenced by kernelMain().
printLoadedTable()
static void hardware_communication::InterruptManager::printLoadedTable () static
printLoadedTableHeader()
static void hardware_communication::InterruptManager::printLoadedTableHeader () static
Referenced by kernelMain().
setIDTEntry()
void hardware_communication::InterruptManager::setIDTEntry (uint8_t interruptNumber, uint16_t codeSegmentSelectorOffset, void(*)() handler, uint8_t DescriptorPrivilegeLever, uint8_t DescriptorType) protected
Member Data Documentation
base
uint32_t hardware_communication::InterruptManager::base
Definition at line 53 of file kinterrupt.hpp.
handlers
InterruptHandler* hardware_communication::InterruptManager::handlers[256] protected
Definition at line 58 of file kinterrupt.hpp.
interruptDescriptorTable
IDT_row hardware_communication::InterruptManager::interruptDescriptorTable[256] protected
Definition at line 55 of file kinterrupt.hpp.
limit
uint16_t hardware_communication::InterruptManager::limit
Definition at line 52 of file kinterrupt.hpp.
picMasterCommand
hardware_communication::Port8BitSlow hardware_communication::InterruptManager::picMasterCommand static protected
Definition at line 66 of file kinterrupt.hpp.
picMasterData
hardware_communication::Port8BitSlow hardware_communication::InterruptManager::picMasterData static protected
Definition at line 67 of file kinterrupt.hpp.
picSlaveCommand
hardware_communication::Port8BitSlow hardware_communication::InterruptManager::picSlaveCommand static protected
Definition at line 68 of file kinterrupt.hpp.
picSlaveData
hardware_communication::Port8BitSlow hardware_communication::InterruptManager::picSlaveData static protected
Definition at line 69 of file kinterrupt.hpp.
The documentation for this class was generated from the following file:
/home/shreekar/Desktop/Building_own_OS/OSOS/libk_header/hardware_communication/kinterrupt.hpp