OSOS Dev: essential::KernelThreadManager
essential::KernelThreadManager
Manages multitasking and scheduling of threads.
#include "kmultitasking.hpp"
Public Member Functions
KernelThreadManager (GDT_Manager *gdt_manager)
Initializes the KernelThread Manager.
~KernelThreadManager ()
bool addThread (KernelThread *thread)
Adds a kernel thread to the scheduling queue.
void killCurrentThread ()
Removes the currently running thread from the scheduling queue.
CPUState * scheduleThreads (CPUState *cpustate)
The core scheduling function called by the timer interrupt.
Static Public Member Functions
static void onThreadExit ()
A static helper function used as the return address for threads.
Public Attributes
GDT_Manager * gdt_manager
Private Attributes
int currentThread
The index of the currently running thread in the threads array.
int numThreads
The current number of active threads.
KernelThread * threads [256]
Array of pointers to all active threads.
Detailed Description
Manages multitasking and scheduling of threads.
Implements a simple Round-Robin scheduler to switch between registered threads.
Definition at line 68 of file kmultitasking.hpp.
Constructor & Destructor Documentation
KernelThreadManager()
KernelThreadManager::KernelThreadManager (GDT_Manager * gdt_manager)
Initializes the KernelThread Manager.
Definition at line 36 of file kmultitasking.cpp.
{
    this->gdt_manager=gdt_manager;
    numThreads = 0;
    currentThread = -1;
    activeTaskManager = this;
}
References activeTaskManager, currentThread, gdt_manager, and numThreads.
~KernelThreadManager()
KernelThreadManager::~KernelThreadManager ()
Definition at line 44 of file kmultitasking.cpp.
{}
Member Function Documentation
addThread()
bool KernelThreadManager::addThread (KernelThread * thread)
Adds a kernel thread to the scheduling queue.
Calls reset() on the thread to prepare its stack.
Parameters
thread Pointer to the KernelThread object to add.
Returns
true if the thread was added successfully, false if the queue is full or thread is already running.
Definition at line 46 of file kmultitasking.cpp.
{
    // Prevent adding the same thread object twice
    for(int i = 0; i < numThreads; i++) {
        if(threads[i] == thread) {
            return false; // KernelThread is already running
        }
    }
    thread->reset();
    if (numThreads >= 256)
        return false;
    threads[numThreads++] = thread;
    return true;
}
References numThreads, essential::KernelThread::reset(), and threads.
Referenced by kernelMain(), and KernelShell::process_command().
killCurrentThread()
void KernelThreadManager::killCurrentThread ()
Removes the currently running thread from the scheduling queue.
This is typically called when a thread finishes execution.
Definition at line 62 of file kmultitasking.cpp.
{
    if (numThreads <= 0) return;
    threads[currentThread] = threads[numThreads - 1];
    numThreads--;
    currentThread = -1;
}
References currentThread, numThreads, and threads.
Referenced by onThreadExit().
onThreadExit()
void KernelThreadManager::onThreadExit () static
A static helper function used as the return address for threads.
When a thread function returns (finishes), the CPU pops this address from the stack. This function effectively calls killCurrentThread() and halts the CPU until the next scheduler tick.
Definition at line 70 of file kmultitasking.cpp.
{
    if (activeTaskManager != nullptr)
        activeTaskManager->killCurrentThread();
    while(true)
        asm("hlt");
}
References activeTaskManager, and killCurrentThread().
Referenced by essential::KernelThread::reset().
scheduleThreads()
CPUState * KernelThreadManager::scheduleThreads (CPUState * cpustate)
The core scheduling function called by the timer interrupt.
Saves the current thread's state (passed in cpustate) and selects the next thread to run. Uses a Round-Robin algorithm with a time quantum.
Parameters
cpustate The register state of the thread that was just interrupted.
Returns
The register state of the next thread to run (which the interrupt handler will restore).
Definition at line 78 of file kmultitasking.cpp.
{
    const int TIME_QUANTUM = 1;
    static int tick_counter = 0;
    if(numThreads <= 0)
        return cpustate;
    if(currentThread >= 0)
        threads[currentThread]->cpustate = cpustate;
    tick_counter++;
    if (tick_counter < TIME_QUANTUM) {
        return cpustate;
    }
    tick_counter = 0;
    // Round Robin Logic for thread scheduling
    if(++currentThread >= numThreads)
        currentThread = 0;
    if(numThreads>1 && currentThread==0) currentThread = 1; // 0th thread is init function from `kernel.cpp`
    return threads[currentThread]->cpustate;
}
References essential::KernelThread::cpustate, currentThread, numThreads, and threads.
Referenced by hardware_communication::InterruptManager::handleInterrupt().
Member Data Documentation
currentThread
int essential::KernelThreadManager::currentThread private
The index of the currently running thread in the threads array.
Definition at line 77 of file kmultitasking.hpp.
Referenced by KernelThreadManager(), killCurrentThread(), and scheduleThreads().
gdt_manager
GDT_Manager* essential::KernelThreadManager::gdt_manager
Definition at line 80 of file kmultitasking.hpp.
Referenced by essential::KernelThread::KernelThread(), and KernelThreadManager().
numThreads
int essential::KernelThreadManager::numThreads private
The current number of active threads.
Definition at line 74 of file kmultitasking.hpp.
Referenced by KernelThreadManager(), addThread(), killCurrentThread(), and scheduleThreads().
threads
KernelThread* essential::KernelThreadManager::threads[256] private
Array of pointers to all active threads.
Definition at line 71 of file kmultitasking.hpp.
Referenced by addThread(), killCurrentThread(), and scheduleThreads().
The documentation for this class was generated from the following files:
kmultitasking.hpp
kmultitasking.cpp