.TH "hardware_communication::Port" 3 "Thu Oct 23 2025 23:53:37" "OSOS - 32-bit Operating System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hardware_communication::Port
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'kport\&.hpp'\fP
.PP
Inherited by \fBhardware_communication::Port16Bit\fP, \fBhardware_communication::Port32Bit\fP, and \fBhardware_communication::Port8Bit\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~Port\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBPort\fP (uint16_t \fBportnumber\fP)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "uint16_t \fBportnumber\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB11\fP of file \fBkport\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "hardware_communication::Port::Port (uint16_t portnumber)\fC [explicit]\fP, \fC [protected]\fP"

.PP
Definition at line \fB3\fP of file \fBkport\&.cpp\fP\&..PP
.nf
3                                                    {
4     this\->portnumber = portnumber;
5 }
.fi

.PP
References \fBportnumber\fP\&.
.SS "hardware_communication::Port::~Port ()\fC [virtual]\fP"

.PP
Definition at line \fB6\fP of file \fBkport\&.cpp\fP\&..PP
.nf
6 {}
.fi

.SH "Member Data Documentation"
.PP 
.SS "uint16_t hardware_communication::Port::portnumber\fC [protected]\fP"

.PP
Definition at line \fB13\fP of file \fBkport\&.hpp\fP\&.
.PP
Referenced by \fBPort()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OSOS - 32-bit Operating System from the source code\&.
