.TH "libk_src/hardware_communication/kinterrupt.cpp" 3 "Thu Oct 23 2025 23:53:37" "OSOS - 32-bit Operating System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libk_src/hardware_communication/kinterrupt.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'hardware_communication/kinterrupt\&.hpp'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "static \fBhardware_communication::InterruptManager\fP * \fBinstalled_interrupt_manager\fP =nullptr"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBhardware_communication::InterruptManager\fP* installed_interrupt_manager =nullptr\fC [static]\fP"

.PP
Definition at line \fB90\fP of file \fBkinterrupt\&.cpp\fP\&.
.PP
Referenced by \fBhardware_communication::InterruptManager::handleInterrupt()\fP, and \fBhardware_communication::InterruptManager::installTable()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OSOS - 32-bit Operating System from the source code\&.
