.TH "libk_src/hardware_communication/kport.cpp" 3 "Thu Oct 23 2025 23:53:37" "OSOS - 32-bit Operating System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libk_src/hardware_communication/kport.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'hardware_communication/kport\&.hpp'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for OSOS - 32-bit Operating System from the source code\&.
