OSOS Dev: memory::PhysicalMemoryManager
memory::PhysicalMemoryManager
#include "kpmm.hpp"
Static Public Member Functions
static void * allocate_block ()
static void free_block (void *address)
static uint32_t get_free_memory_kb ()
static void init (multiboot_info_t *mbi)
Static Private Member Functions
static bool is_used (uint32_t block_index)
static void mark_free (uint32_t block_index)
static void mark_used (uint32_t block_index)
Static Private Attributes
static uint8_t * memory_bitmap = nullptr
static uint32_t total_blocks = 0
static uint32_t used_blocks = 0
Detailed Description
Definition at line 19 of file kpmm.hpp.
Member Function Documentation
allocate_block()
void * memory::PhysicalMemoryManager::allocate_block () static
Definition at line 160 of file kpmm.cpp.
{
    // Iterate through bitmap to find a free bit (0)
    // Optimization: We could store the last known free index to speed this up
    for (uint32_t i = 0; i < total_blocks; i++) {
        if (!is_used(i)) {
            mark_used(i);
            used_blocks++;
            // Convert block index -> Physical Address
            return (void*)(uintptr_t)(i * PAGE_SIZE);
        }
    }
    printf("OOM: Out of Memory!\n");
    return nullptr;
}
References is_used(), mark_used(), memory::PAGE_SIZE, basic::printf(), total_blocks, and used_blocks.
Referenced by memory::PagingManager::init().
free_block()
void memory::PhysicalMemoryManager::free_block (void * address) static
Definition at line 176 of file kpmm.cpp.
{
    uintptr_t addr = (uintptr_t)address;
    uint32_t block_index = addr / PAGE_SIZE;
    if (is_used(block_index)) {
        mark_free(block_index);
        used_blocks--;
    }
}
References is_used(), mark_free(), memory::PAGE_SIZE, and used_blocks.
get_free_memory_kb()
uint32_t memory::PhysicalMemoryManager::get_free_memory_kb () static
Definition at line 187 of file kpmm.cpp.
{
    // This is a rough calculation based on current tracking
    // For exact numbers, you should count '0' bits in the loop
    return (total_blocks - used_blocks) * 4;
}
References total_blocks, and used_blocks.
Referenced by KernelShell::process_command().
init()
void memory::PhysicalMemoryManager::init (multiboot_info_t * mbi) static
Definition at line 96 of file kpmm.cpp.
{
    // placing it at the address of 'end', ensuring it doesn't overwrite kernel code.
    memory_bitmap = (uint8_t*)&end;
    // Mark EVERYTHING as used (1) initially.
    // We only free what Multiboot tells us is actually RAM.
    for (int i = 0; i < (int)BITMAP_SIZE; i++) {
        memory_bitmap[i] = 0xFF;
    }
    // Parse Multiboot Map to unlock available RAM
    uintptr_t mmap_start = mbi->mmap_addr;
    uintptr_t mmap_end = mbi->mmap_addr + mbi->mmap_length;
    for (multiboot_memory_map_t *mmap = (multiboot_memory_map_t *)mmap_start;
         (uintptr_t)mmap < mmap_end;
         mmap = (multiboot_memory_map_t *)((uintptr_t)mmap + mmap->size + sizeof(mmap->size)))
    {
        if (mmap->type == MULTIBOOT_MEMORY_AVAILABLE) {
            // Calculate which 4KB blocks this region covers
            uint32_t start_block = mmap->addr / PAGE_SIZE;
            uint32_t num_blocks = mmap->len / PAGE_SIZE;
            // Calculate total blocks supported by our bitmap size
            uint32_t max_supported_blocks = BITMAP_SIZE * 8;
            // If memory starts beyond 4GB, ignore it
            if (start_block >= max_supported_blocks) {
                continue;
            }
            // If memory starts inside 4GB but extends beyond it, cap it.
            if (start_block + num_blocks > max_supported_blocks) {
                num_blocks = max_supported_blocks - start_block;
            }
            // Mark them as free
            for (uint32_t i = 0; i < num_blocks; i++) {
                mark_free(start_block + i);
            }
            // Track total system size roughly
            if (start_block + num_blocks > total_blocks) {
                total_blocks = start_block + num_blocks;
            }
        }
    }
    // Protect Critical Regions
    // Mark the first 4MB as USED. This covers:
    // - Real Mode IVT (0x0)
    // - BIOS Data Area
    // - Video Memory (0xB8000)
    // - Your Kernel Code (loaded at 1MB usually)
    // - GRUB Modules
    uint32_t reserved_blocks = (4 * 1024 * 1024) / PAGE_SIZE; // 1024 blocks
    for (uint32_t i = 0; i < reserved_blocks; i++) {
        mark_used(i);
    }
    printf("PMM Initialized. Total Blocks: %d\n", total_blocks);
}
References memory::BITMAP_SIZE, end, mark_free(), mark_used(), memory_bitmap, memory::PAGE_SIZE, basic::printf(), and total_blocks.
Referenced by kernelMain().
is_used()
bool memory::PhysicalMemoryManager::is_used (uint32_t block_index) static private
Definition at line 86 of file kpmm.cpp.
{
    uint32_t index = block_index / 8;
    uint32_t offset = block_index % 8;
    return (memory_bitmap[index] & (1 << offset)) != 0;
}
References memory_bitmap.
Referenced by allocate_block(), and free_block().
mark_free()
void memory::PhysicalMemoryManager::mark_free (uint32_t block_index) static private
Definition at line 80 of file kpmm.cpp.
{
    uint32_t index = block_index / 8;
    uint32_t offset = block_index % 8;
    memory_bitmap[index] &= ~(1 << offset);
}
References memory_bitmap.
Referenced by free_block(), and init().
mark_used()
void memory::PhysicalMemoryManager::mark_used (uint32_t block_index) static private
Definition at line 74 of file kpmm.cpp.
{
    uint32_t index = block_index / 8;
    uint32_t offset = block_index % 8;
    memory_bitmap[index] |= (1 << offset);
}
References memory_bitmap.
Referenced by allocate_block(), and init().
Member Data Documentation
memory_bitmap
uint8_t * memory::PhysicalMemoryManager::memory_bitmap = nullptr static private
Definition at line 22 of file kpmm.hpp.
Referenced by init(), is_used(), mark_free(), and mark_used().
total_blocks
uint32_t memory::PhysicalMemoryManager::total_blocks = 0 static private
Definition at line 25 of file kpmm.hpp.
Referenced by allocate_block(), get_free_memory_kb(), and init().
used_blocks
uint32_t memory::PhysicalMemoryManager::used_blocks = 0 static private
Definition at line 26 of file kpmm.hpp.
Referenced by allocate_block(), free_block(), and get_free_memory_kb().
The documentation for this class was generated from the following files:
kpmm.hpp
kpmm.cpp