OSOS Dev: hardware_communication::InterruptManager
hardware_communication::InterruptManager
Manages the Interrupt Descriptor Table (IDT) and Programmable Interrupt Controllers (PICs), dispatching interrupts to registered handlers.
#include "kinterrupt.hpp"
Public Member Functions
InterruptManager (essential::GDT_Manager *gdt, essential::KThreadManager *thread_manager)
~InterruptManager ()
void installTable ()
Loads the Interrupt Descriptor Table (IDT) into the CPU's IDTR register.
Static Public Member Functions
static void activate ()
Enables interrupts globally by executing the 'sti' instruction.
static void deactivate ()
Disables interrupts globally by executing the 'cli' instruction.
static uintptr_t handleInterrupt (uint8_t interruptNumber, uintptr_t esp)
The central interrupt dispatching function called by assembly stubs.
static void printLoadedTable ()
Prints the details of all entries in the currently loaded IDT.
static void printLoadedTableHeader ()
Prints the header information (base, limit, count) of the currently loaded IDT.
Public Attributes
uint32_t base
uint16_t limit
Protected Member Functions
void setIDTEntry (uint8_t interruptNumber, uint16_t codeSegmentSelectorOffset, void(*handler)(), uint8_t DescriptorPrivilegeLever, uint8_t DescriptorType)
Populates a specific entry in the Interrupt Descriptor Table (IDT).
Protected Attributes
InterruptHandler * handlers [256]
IDT_Row interruptDescriptorTable [256]
essential::KThreadManager * thread_manager
Static Protected Attributes
static hardware_communication::Port8BitSlow picMasterCommand
static hardware_communication::Port8BitSlow picMasterData
static hardware_communication::Port8BitSlow picSlaveCommand
static hardware_communication::Port8BitSlow picSlaveData
Detailed Description
Manages the Interrupt Descriptor Table (IDT) and Programmable Interrupt Controllers (PICs), dispatching interrupts to registered handlers.
Definition at line 51 of file kinterrupt.hpp.
Constructor & Destructor Documentation
InterruptManager()
InterruptManager::InterruptManager (essential::GDT_Manager * gdt, essential::KThreadManager * thread_manager)
Definition at line 27 of file kinterrupt.cpp.
{
    this->thread_manager = thread_manager;
    // ICW1: Start Initialization Sequence. Both PICs are told to listen for 3 more bytes of config data.
    picMasterCommand.write(0x11);
    picSlaveCommand.write(0x11);
    // ICW2: Vector Remapping.
    // Master is told to remap its IRQs (0-7) to CPU vectors 0x20-0x27.
    picMasterData.write(0x20);
    // Slave is told to remap its IRQs (8-15) to CPU vectors 0x28-0x2F.
    picSlaveData.write(0x28);
    // ICW3: Chaining Configuration.
    // Master is told a slave is connected on its IRQ 2 line (0x04 = bit 2 set).
    picMasterData.write(0x04);
    // Slave is told its identity is 2.
    picSlaveData.write(0x02);
    // ICW4: Environment Information.
    // Both are told to operate in standard "8086/88" mode.
    picMasterData.write(0x01);
    picSlaveData.write(0x01);
    // OCW1: Interrupt Masking.
    // This is the final step, enabling all interrupts by writing a mask of all zeros.
    picMasterData.write(0x00);
    picSlaveData.write(0x00);
    base=(uintptr_t)&interruptDescriptorTable;
    limit = sizeof(interruptDescriptorTable) - 1;
    uint16_t kernelCSselectorOffset = gdt->kernel_CS_selector();
    uint8_t IDT_INTERRUPT_GATE=0xE;
    for(int i=0; i<256; i++){
        setIDTEntry(i, kernelCSselectorOffset, &ignoreInterrupt, 0, IDT_INTERRUPT_GATE);
    }
    // Set handlers for hardware interrupts
    setIDTEntry(0x20, kernelCSselectorOffset, &handleIRQ0x00, 0, IDT_INTERRUPT_GATE); // Timer
    setIDTEntry(0x21, kernelCSselectorOffset, &handleIRQ0x01, 0, IDT_INTERRUPT_GATE); // Keyboard
    setIDTEntry(0x24, kernelCSselectorOffset, &handleIRQ0x04, 0, IDT_INTERRUPT_GATE); // Serial (COM1)
    setIDTEntry(0x2B, kernelCSselectorOffset, &handleIRQ0x0B, 0, IDT_INTERRUPT_GATE); // Network card
    setIDTEntry(0x2C, kernelCSselectorOffset, &handleIRQ0x0C, 0, IDT_INTERRUPT_GATE); // PS/2 Mouse
    setIDTEntry(0x80, kernelCSselectorOffset, &handleIRQ0x0C, 0, IDT_INTERRUPT_GATE); // syscall to force schedule thread
}
References base, handleIRQ0x00(), handleIRQ0x01(), handleIRQ0x04(), handleIRQ0x0B(), handleIRQ0x0C(), ignoreInterrupt(), interruptDescriptorTable, essential::GDT_Manager::kernel_CS_selector(), limit, picMasterCommand, picMasterData, picSlaveCommand, picSlaveData, setIDTEntry(), thread_manager, and hardware_communication::Port8BitSlow::write().
~InterruptManager()
InterruptManager::~InterruptManager ()
Definition at line 74 of file kinterrupt.cpp.
{}
Member Function Documentation
activate()
void InterruptManager::activate () static
Enables interrupts globally by executing the 'sti' instruction.
Definition at line 112 of file kinterrupt.cpp.
{
    __asm__ volatile ("sti");
    basic::printf("Interrupts Activated\n");
}
References basic::printf().
Referenced by kernelMain().
deactivate()
void InterruptManager::deactivate () static
Disables interrupts globally by executing the 'cli' instruction.
Definition at line 118 of file kinterrupt.cpp.
{
    __asm__ volatile ("cli");
    basic::printf("Interrupts Deactivated\n");
}
References basic::printf().
handleInterrupt()
uintptr_t InterruptManager::handleInterrupt (uint8_t interruptNumber, uintptr_t esp) static
The central interrupt dispatching function called by assembly stubs.
Parameters
interruptNumber The number of the interrupt that occurred.
esp The stack pointer (Extended Stack Pointer) from the context of the interrupted process.
Returns
The updated stack pointer, typically the same as the input unless the handler modified the stack frame.
Definition at line 178 of file kinterrupt.cpp.
{
    // using the global pointer "installed_interrupt_manager" to access the current interrupt manager
    if(installed_interrupt_manager->handlers[interruptNumber]!=nullptr){
        esp = installed_interrupt_manager->handlers[interruptNumber]->handleInterrupt(esp);
    }
    if(interruptNumber==0x20){ //0x20 is Hardware Timer Interrupt
        esp = (uintptr_t)installed_interrupt_manager->thread_manager->scheduleThreads((essential::CPUState*)esp, false);
    }
    else if (interruptNumber == 0x80) {
        // 2. os_yield(): FORCE a context switch immediately
        esp = (uintptr_t)installed_interrupt_manager->thread_manager->scheduleThreads((essential::CPUState*)esp, true);
    }
    // Hardware interrupts must still be acknowledged to the PIC
    if (0x20 <=interruptNumber && interruptNumber <= 0x2F) {
        picMasterCommand.write(0x20);
        if (0x28 <= interruptNumber) picSlaveCommand.write(0x20);
    }
    else {
        basic::printf("UNHANDLED INTERRUPT %#hx\n",interruptNumber);
    }
    return esp;
}
References esp, hardware_communication::InterruptHandler::handleInterrupt(), handlers, installed_interrupt_manager, picMasterCommand, picSlaveCommand, basic::printf(), essential::KThreadManager::scheduleThreads(), thread_manager, and hardware_communication::Port8BitSlow::write().
installTable()
void InterruptManager::installTable ()
Loads the Interrupt Descriptor Table (IDT) into the CPU's IDTR register.
Definition at line 96 of file kinterrupt.cpp.
{
    installed_interrupt_manager=this;
    struct IDT_Pointer {
        uint16_t limit;
        uint32_t base;
    } __attribute__((packed));
    IDT_Pointer idt_ptr;
    idt_ptr.limit = this->limit;
    idt_ptr.base = this->base;
    __asm__ volatile ("lidt %0" : : "m"(idt_ptr)); // "m" will put address of `idt_ptr` in place of `%0`
    basic::printf("IDT Installed\n");
}
References hardware_communication::__attribute__, base, base, installed_interrupt_manager, limit, limit, and basic::printf().
Referenced by kernelMain().
printLoadedTable()
void InterruptManager::printLoadedTable () static
Prints the details of all entries in the currently loaded IDT.
Definition at line 125 of file kinterrupt.cpp.
{
    struct IDT_Pointer {
        uint16_t limit;
        uint32_t base;
    } __attribute__((packed));
    IDT_Pointer idt_ptr;
    __asm__ volatile ("sidt %0" : "=m"(idt_ptr));
    basic::printf("---\n");
    basic::printf("INFO about : Currently Loaded IDT\n");
    basic::printf("Base Address: %#x\n", idt_ptr.base);
    basic::printf("Limit: %#x (%d bytes)\n", idt_ptr.limit, idt_ptr.limit);
    basic::printf("Entries: %d\n", (idt_ptr.limit + 1) / sizeof(IDT_Row));
    basic::printf("---\n");
    basic::printf(" Idx | Handler Address | Selector | Access Flags\n");
    IDT_Row* current_idt = (IDT_Row*)idt_ptr.base;
    uint32_t num_entries = (idt_ptr.limit + 1) / sizeof(IDT_Row);
    for (uint32_t i = 0; i < num_entries; i++) {
        uint32_t handler_address = (current_idt[i].handlerAddressHighbits << 16) | current_idt[i].handlerAddressLowbits;
        if (handler_address != 0) {
            basic::printf(" %3d | %#015x | %#08x | %#012x\n",
                   i,
                   handler_address,
                   current_idt[i].kernelCodeSegmentSelector,
                   current_idt[i].access
            );
        }
    }
    basic::printf("---\n");
}
References hardware_communication::__attribute__, access, base, hardware_communication::IDT_Row::handlerAddressHighbits, handlerAddressLowbits, kernelCodeSegmentSelector, limit, and basic::printf().
printLoadedTableHeader()
void InterruptManager::printLoadedTableHeader () static
Prints the header information (base, limit, count) of the currently loaded IDT.
Definition at line 161 of file kinterrupt.cpp.
{
    struct IDT_Pointer {
        uint16_t limit;
        uint32_t base;
    } __attribute__((packed));
    IDT_Pointer idt_ptr;
    __asm__ volatile ("sidt %0" : "=m"(idt_ptr));
    basic::printf("---\n");
    basic::printf("INFO about : Currently Loaded IDT\n");
    basic::printf("Base Address: %#x\n", idt_ptr.base);
    basic::printf("Limit: %#x (%d bytes)\n", idt_ptr.limit, idt_ptr.limit);
    basic::printf("Entries: %d\n", (idt_ptr.limit + 1) / sizeof(IDT_Row));
    basic::printf("---\n");
}
References hardware_communication::__attribute__, base, limit, and basic::printf().
setIDTEntry()
void InterruptManager::setIDTEntry (uint8_t interruptNumber, uint16_t codeSegmentSelectorOffset, void(*)() handler, uint8_t DescriptorPrivilegeLever, uint8_t DescriptorType) protected
Populates a specific entry in the Interrupt Descriptor Table (IDT).
Parameters
interruptNumber The index of the IDT entry to set (0-255).
codeSegmentSelectorOffset The segment selector for the interrupt handler code.
handler A function pointer to the assembly stub that handles the interrupt.
DescriptorPrivilegeLever The DPL (Descriptor Privilege Level) for the interrupt gate.
DescriptorType The type of the descriptor (e.g., 0xE for 32-bit Interrupt Gate).
Definition at line 77 of file kinterrupt.cpp.
{
    const uint8_t IDT_DESC_PRESET= 0x80;
    interruptDescriptorTable[interruptNumber].handlerAddressLowbits=(uint32_t)handler & 0xFFFF;
    interruptDescriptorTable[interruptNumber].handlerAddressHighbits=((uint32_t)handler >> 16) & 0xFFFF;
    interruptDescriptorTable[interruptNumber].reserved=0;
    interruptDescriptorTable[interruptNumber].access=IDT_DESC_PRESET | DescriptorType | ((DescriptorPrivilegeLever & 3) << 5);
    interruptDescriptorTable[interruptNumber].kernelCodeSegmentSelector=codeSegmentSelectorOffset;
}
References hardware_communication::IDT_Row::access, hardware_communication::IDT_Row::handlerAddressHighbits, hardware_communication::IDT_Row::handlerAddressLowbits, interruptDescriptorTable, hardware_communication::IDT_Row::kernelCodeSegmentSelector, and hardware_communication::IDT_Row::reserved.
Referenced by InterruptManager().
Member Data Documentation
base
uint32_t hardware_communication::InterruptManager::base
Definition at line 57 of file kinterrupt.hpp.
Referenced by InterruptManager(), and installTable().
handlers
InterruptHandler* hardware_communication::InterruptManager::handlers[256] protected
Definition at line 60 of file kinterrupt.hpp.
Referenced by hardware_communication::InterruptHandler::InterruptHandler(), hardware_communication::InterruptHandler::~InterruptHandler(), and handleInterrupt().
interruptDescriptorTable
IDT_Row hardware_communication::InterruptManager::interruptDescriptorTable[256] protected
Definition at line 59 of file kinterrupt.hpp.
Referenced by InterruptManager(), and setIDTEntry().
limit
uint16_t hardware_communication::InterruptManager::limit
Definition at line 56 of file kinterrupt.hpp.
Referenced by InterruptManager(), and installTable().
picMasterCommand
Port8BitSlow InterruptManager::picMasterCommand static protected
Definition at line 76 of file kinterrupt.hpp.
Referenced by InterruptManager(), and handleInterrupt().
picMasterData
Port8BitSlow InterruptManager::picMasterData static protected
Definition at line 77 of file kinterrupt.hpp.
Referenced by InterruptManager().
picSlaveCommand
Port8BitSlow InterruptManager::picSlaveCommand static protected
Definition at line 78 of file kinterrupt.hpp.
Referenced by InterruptManager(), and handleInterrupt().
picSlaveData
Port8BitSlow InterruptManager::picSlaveData static protected
Definition at line 79 of file kinterrupt.hpp.
Referenced by InterruptManager().
thread_manager
essential::KThreadManager* hardware_communication::InterruptManager::thread_manager protected
Definition at line 61 of file kinterrupt.hpp.
Referenced by InterruptManager(), and handleInterrupt().
The documentation for this class was generated from the following files:
kinterrupt.hpp
kinterrupt.cpp