OSOS Dev: hardware_communication::Port16Bit
hardware_communication::Port16Bit final
Represents a 16-bit (word-sized) I/O Port.
#include "kport.hpp"
Public Member Functions
Port16Bit (uint16_t portnumber)
~Port16Bit () override
uint16_t read ()
Reads a 16-bit value from the I/O port.
void write (uint16_t data)
Writes a 16-bit value to the I/O port.
Protected Attributes
uint16_t portnumber
Detailed Description
Represents a 16-bit (word-sized) I/O Port.
Definition at line 45 of file kport.hpp.
Constructor & Destructor Documentation
Port16Bit()
Port16Bit::Port16Bit (uint16_t portnumber) explicit
Definition at line 38 of file kport.cpp.
:Port(portnumber){}
~Port16Bit()
Port16Bit::~Port16Bit () override
Definition at line 39 of file kport.cpp.
{}
Member Function Documentation
read()
uint16_t Port16Bit::read ()
Reads a 16-bit value from the I/O port.
Returns
The 16-bit value read from the port.
Definition at line 46 of file kport.cpp.
{
    uint16_t result;
    __asm__ volatile("inw %1, %0" :"=a"(result) : "Nd"(portnumber));
    return result;
}
References hardware_communication::Port::portnumber.
Referenced by driver::amd_am79c973::amd_am79c973(), driver::amd_am79c973::activate(), driver::amd_am79c973::handleInterrupt(), and driver::amd_am79c973::reset().
write()
void Port16Bit::write (uint16_t data)
Writes a 16-bit value to the I/O port.
Parameters
data The 16-bit value to write.
Definition at line 41 of file kport.cpp.
{
    __asm__ volatile("outw %0, %1" : : "a"(data), "Nd"(portnumber));
}
References hardware_communication::Port::portnumber.
Referenced by driver::amd_am79c973::amd_am79c973(), driver::amd_am79c973::activate(), driver::amd_am79c973::handleInterrupt(), driver::amd_am79c973::reset(), and driver::amd_am79c973::send().
Member Data Documentation
portnumber
uint16_t hardware_communication::Port::portnumber protected inherited
Definition at line 11 of file kport.hpp.
Referenced by hardware_communication::Port::Port(), hardware_communication::Port8Bit::read(), read(), hardware_communication::Port32Bit::read(), write(), hardware_communication::Port32Bit::write(), hardware_communication::Port8Bit::write(), and hardware_communication::Port8BitSlow::write().
The documentation for this class was generated from the following files:
kport.hpp
kport.cpp