OSOS Dev: hardware_communication::Port8BitSlow
hardware_communication::Port8BitSlow final
Represents a Port8Bit with a forced delay on writes.
#include "kport.hpp"
Public Member Functions
Port8BitSlow (uint16_t portnumber)
Constructs a new Port8BitSlow object.
~Port8BitSlow () override
Destroys the Port8BitSlow object.
uint8_t read ()
Reads an 8-bit value from the I/O port.
void write (uint8_t data) override
Writes an 8-bit value to the I/O port with a delay.
Protected Attributes
uint16_t portnumber
Detailed Description
Represents a Port8Bit with a forced delay on writes.
Definition at line 29 of file kport.hpp.
Constructor & Destructor Documentation
Port8BitSlow()
hardware_communication::Port8BitSlow::Port8BitSlow (uint16_t portnumber) explicit
Constructs a new Port8BitSlow object.
Parameters
portnumber The 16-bit address of the I/O port.
Definition at line 42 of file kport.cpp.
:Port8Bit(portnumber){}
~Port8BitSlow()
hardware_communication::Port8BitSlow::~Port8BitSlow () override
Destroys the Port8BitSlow object.
Definition at line 44 of file kport.cpp.
{}
Member Function Documentation
read()
uint8_t hardware_communication::Port8Bit::read () inherited
Reads an 8-bit value from the I/O port.
Returns
The 8-bit value read from the port.
Definition at line 31 of file kport.cpp.
{
    uint8_t result;
    __asm__ volatile("inb %1, %0" :"=a"(result) : "Nd"(portnumber));
    return result;
}
References hardware_communication::Port::portnumber.
Referenced by driver::KeyboardDriver::activate(), driver::MouseDriver::activate(), basic::enable_cursor(), driver::KeyboardDriver::handleInterrupt(), driver::MouseDriver::handleInterrupt(), driver::SerialDriver::handleInterrupt(), and basic::is_serial_ready().
write()
void hardware_communication::Port8BitSlow::write (uint8_t data) override virtual
Writes an 8-bit value to the I/O port with a delay.
Parameters
data The 8-bit value to write.
Reimplemented from hardware_communication::Port8Bit.
Definition at line 48 of file kport.cpp.
{
    __asm__ volatile("outb %0, %1 \n jmp 1f \n 1: jmp 1f\n 1:" : : "a"(data), "Nd"(portnumber));
}
References hardware_communication::Port::portnumber.
Referenced by hardware_communication::InterruptManager::InterruptManager(), and hardware_communication::InterruptManager::handleInterrupt().
Member Data Documentation
portnumber
uint16_t hardware_communication::Port::portnumber protected inherited
Definition at line 12 of file kport.hpp.
Referenced by hardware_communication::Port::Port(), hardware_communication::Port8Bit::read(), hardware_communication::Port16Bit::read(), hardware_communication::Port32Bit::read(), hardware_communication::Port16Bit::write(), hardware_communication::Port32Bit::write(), hardware_communication::Port8Bit::write(), and write().
The documentation for this class was generated from the following files:
kport.hpp
kport.cpp