OSOS Dev: concurrency::KThreadManager
concurrency::KThreadManager
Manages multitasking and scheduling of threads.
#include "kmultitasking.hpp"
Public Member Functions
KThreadManager (essential::GDT_Manager *gdt_manager)
Initializes the KThread Manager.
~KThreadManager ()
bool addThread (KThread *thread)
Adds a kernel thread to the scheduling queue.
void killCurrentThread ()
Removes the currently running thread from the scheduling queue.
CPUState * scheduleThreads (CPUState *cpustate, bool forceSwitch=false)
The core scheduling function called by the timer interrupt.
Static Public Member Functions
static void onThreadExit ()
A static helper function used as the return address for threads.
Public Attributes
essential::GDT_Manager * gdt_manager
Private Attributes
int currentThread
The index of the currently running thread in the threads array.
int numThreads
The current number of active threads.
KThread * threads [256]
Array of pointers to all active threads.
Detailed Description
Manages multitasking and scheduling of threads.
Implements a simple Round-Robin scheduler to switch between registered threads.
Definition at line 72 of file kmultitasking.hpp.
Constructor & Destructor Documentation
KThreadManager()
KThreadManager::KThreadManager (essential::GDT_Manager * gdt_manager)
Initializes the KThread Manager.
Definition at line 41 of file kmultitasking.cpp.
{
    this->gdt_manager=gdt_manager;
    numThreads = 0;
    currentThread = -1;
    activeKThreadManager = this;
}
References activeKThreadManager, currentThread, gdt_manager, and numThreads.
~KThreadManager()
KThreadManager::~KThreadManager ()
Definition at line 49 of file kmultitasking.cpp.
{}
Member Function Documentation
addThread()
bool KThreadManager::addThread (KThread * thread)
Adds a kernel thread to the scheduling queue.
Calls reset() on the thread to prepare its stack.
Parameters
thread Pointer to the KThread object to add.
Returns
true if the thread was added successfully, false if the queue is full or thread is already running.
Definition at line 51 of file kmultitasking.cpp.
{
    // Prevent adding the same thread object twice
    for(int i = 0; i < numThreads; i++) {
        if(threads[i] == thread) {
            return false; // KThread is already running
        }
    }
    thread->reset();
    if (numThreads >= 256)
        return false;
    threads[numThreads++] = thread;
    return true;
}
References numThreads, concurrency::KThread::reset(), and threads.
Referenced by concurrency::KThread::start().
killCurrentThread()
void KThreadManager::killCurrentThread ()
Removes the currently running thread from the scheduling queue.
This is typically called when a thread finishes execution.
Definition at line 67 of file kmultitasking.cpp.
{
    if (numThreads <= 0) return;
    threads[currentThread] = threads[numThreads - 1];
    numThreads--;
    currentThread = -1;
}
References currentThread, numThreads, and threads.
Referenced by onThreadExit().
onThreadExit()
void KThreadManager::onThreadExit () static
A static helper function used as the return address for threads.
When a thread function returns (finishes), the CPU pops this address from the stack. This function effectively calls killCurrentThread() and halts the CPU until the next scheduler tick.
Definition at line 75 of file kmultitasking.cpp.
{
    if (activeKThreadManager != nullptr)
        activeKThreadManager->killCurrentThread();
    while(true)
        asm("hlt");
}
References activeKThreadManager, and killCurrentThread().
Referenced by concurrency::KThread::reset().
scheduleThreads()
CPUState * KThreadManager::scheduleThreads (CPUState * cpustate, bool forceSwitch = false)
The core scheduling function called by the timer interrupt.
Saves the current thread's state (passed in cpustate) and selects the next thread to run. Uses a Round-Robin algorithm with a time quantum.
Parameters
cpustate The register state of the thread that was just interrupted.
forceSwitch if true then just schedule thread without looking at time quantum
Returns
The register state of the next thread to run (which the interrupt handler will restore).
Definition at line 84 of file kmultitasking.cpp.
{
    const int TIME_QUANTUM = 20;
    static int tick_counter = 0;
    if(numThreads <= 0) return cpustate;
    if(currentThread >= 0)
        threads[currentThread]->cpustate = cpustate;
    tick_counter++;
    if (tick_counter < TIME_QUANTUM && !forceSwitch) {
        return cpustate;
    }
    tick_counter = 0;
    // Round Robin Logic
    if(++currentThread >= numThreads)
        currentThread = 0;
    return threads[currentThread]->cpustate;
}
References concurrency::KThread::cpustate, currentThread, numThreads, and threads.
Referenced by hardware_communication::InterruptManager::handleInterrupt().
Member Data Documentation
currentThread
int concurrency::KThreadManager::currentThread private
The index of the currently running thread in the threads array.
Definition at line 81 of file kmultitasking.hpp.
Referenced by KThreadManager(), killCurrentThread(), and scheduleThreads().
gdt_manager
essential::GDT_Manager* concurrency::KThreadManager::gdt_manager
Definition at line 84 of file kmultitasking.hpp.
Referenced by concurrency::KThread::KThread(), and KThreadManager().
numThreads
int concurrency::KThreadManager::numThreads private
The current number of active threads.
Definition at line 78 of file kmultitasking.hpp.
Referenced by KThreadManager(), addThread(), killCurrentThread(), and scheduleThreads().
threads
KThread* concurrency::KThreadManager::threads[256] private
Array of pointers to all active threads.
Definition at line 75 of file kmultitasking.hpp.
Referenced by addThread(), killCurrentThread(), and scheduleThreads().
The documentation for this class was generated from the following files:
kmultitasking.hpp
kmultitasking.cpp