OSOS Dev: kernel.cpp File Reference
kernel.cpp File Reference
#include "kernel.hpp"
Functions
void kernel_idle_loop ()
This is required for multitasking to protect stack which CPU is using which there is no task to do.
void kernelMain (multiboot_info_t *mbi, uint32_t magicnumber)
The main entry point for the C++ kernel.
void taskA ()
taskA for testing multitasking
void taskB ()
taskB for testing multitasking
Function Documentation
kernel_idle_loop()
void kernel_idle_loop ()
This is required for multitasking to protect stack which CPU is using which there is no task to do.
Definition at line 4 of file kernel.cpp.
{
    while(true) {
        asm("hlt"); // Wait for interrupts (saves CPU)
    }
}
Referenced by kernelMain().
kernelMain()
void kernelMain (multiboot_info_t * mbi, uint32_t magicnumber)
The main entry point for the C++ kernel.
Parameters
mbi Pointer to the Multiboot information structure provided by GRUB.
magicnumber The magic number passed by GRUB to verify boot.
Definition at line 31 of file kernel.cpp.
{
    essential::__callConstructors();
    basic::enable_cursor(0,15);
    basic::clearScreen();
    essential::GDT_Manager osos_GDT;
    osos_GDT.installTable();
    essential::GDT_Manager::printLoadedTableHeader();
    essential::TaskManager osos_TaskManager;
    essential::Task idleTask(&osos_GDT, &kernel_idle_loop);
    osos_TaskManager.addTask(&idleTask);
    essential::Task task1(&osos_GDT, &taskA);
    essential::Task task2(&osos_GDT, &taskB);
    // central kernel shell
    KernelShell shell(&osos_TaskManager, &task1, &task2);
    hardware_communication::InterruptManager osos_InterruptManager(&osos_GDT, &osos_TaskManager);
    // object of drivers so that they will handle their corresponding Interrupts
    driver::DriverManager driverManager;
        KeyboardEventHandler_for_kernel keyboardEventHandler_for_kernel(&shell);
        driver::KeyboardDriver keyboard(&osos_InterruptManager,&keyboardEventHandler_for_kernel);
        driverManager.addDriver(&keyboard);
        MouseEventHandler_for_kernel mouseEventHandler_for_kernel;
        driver::MouseDriver mouse(&osos_InterruptManager, &mouseEventHandler_for_kernel);
        driverManager.addDriver(&mouse);
        SerialEventHandler_for_kernel serialEventHandler_for_kernel(&shell);
        driver::SerialDriver serialIO(&osos_InterruptManager, &serialEventHandler_for_kernel);
        driverManager.addDriver(&serialIO);
        hardware_communication::PCI_Controller pciController;
        pciController.selectDrivers(&driverManager, &osos_InterruptManager);
    driverManager.activateAll();
    osos_InterruptManager.installTable();
    hardware_communication::InterruptManager::printLoadedTableHeader();
    basic::printf("\nHELLO FROM OSOS...\nEnter 'help' to see working commands :)\n");
    basic::printf("OSOS> ");
    hardware_communication::InterruptManager::activate();
    while (true){asm("hlt");};
    basic::disable_cursor();
    essential::__cxa_finalize(0);
    (void)mbi;
    (void)magicnumber;
}
References essential::__callConstructors(), essential::__cxa_finalize(), hardware_communication::InterruptManager::activate(), driver::DriverManager::activateAll(), driver::DriverManager::addDriver(), essential::TaskManager::addTask(), basic::clearScreen(), basic::disable_cursor(), basic::enable_cursor(), essential::GDT_Manager::installTable(), hardware_communication::InterruptManager::installTable(), kernel_idle_loop(), basic::printf(), essential::GDT_Manager::printLoadedTableHeader(), hardware_communication::InterruptManager::printLoadedTableHeader(), hardware_communication::PCI_Controller::selectDrivers(), taskA(), and taskB().
taskA()
void taskA ()
taskA for testing multitasking
Definition at line 11 of file kernel.cpp.
{
    for(int i=0; i<100; i++){
        basic::printf("A");
        for(long long i=0; i<100000; i++){basic::printf("");} //for some short delay
    }
}
References basic::printf().
Referenced by kernelMain().
taskB()
void taskB ()
taskB for testing multitasking
Definition at line 20 of file kernel.cpp.
{
    for(int i=0; i<100; i++){
        basic::printf("B");
        for(long long i=0; i<100000; i++){basic::printf("");} //for some short delay
    }
}
References basic::printf().
Referenced by kernelMain().