OSOS Dev: driver::MouseEventHandler
driver::MouseEventHandler abstract
Base class (interface) for handling mouse events (movement and button clicks).
#include "kmouse.hpp"
Public Member Functions
MouseEventHandler ()
virtual ~MouseEventHandler ()
virtual void onMouseDown (uint8_t button)=0
virtual void onMouseMove (int8_t delta_x, int8_t delta_y)=0
virtual void onMouseUp (uint8_t button)=0
Detailed Description
Base class (interface) for handling mouse events (movement and button clicks).
Definition at line 31 of file kmouse.hpp.
Constructor & Destructor Documentation
MouseEventHandler()
MouseEventHandler::MouseEventHandler ()
Definition at line 5 of file kmouse.cpp.
{}
~MouseEventHandler()
MouseEventHandler::~MouseEventHandler () virtual
Definition at line 6 of file kmouse.cpp.
{}
Member Function Documentation
onMouseDown()
virtual void driver::MouseEventHandler::onMouseDown (uint8_t button) pure virtual
Implemented in MouseEventHandler_for_kernel.
Referenced by driver::MouseDriver::handleInterrupt().
onMouseMove()
virtual void driver::MouseEventHandler::onMouseMove (int8_t delta_x, int8_t delta_y) pure virtual
Implemented in MouseEventHandler_for_kernel.
Referenced by driver::MouseDriver::handleInterrupt().
onMouseUp()
virtual void driver::MouseEventHandler::onMouseUp (uint8_t button) pure virtual
Implemented in MouseEventHandler_for_kernel.
Referenced by driver::MouseDriver::handleInterrupt().
The documentation for this class was generated from the following files:
kmouse.hpp
kmouse.cpp