OSOS Dev: essential::Task
essential::Task
Represents a single unit of execution (a thread or process) in the OS.
#include "kmultitasking.hpp"
Public Member Functions
Task (GDT_Manager *gdt_manager, void(*entrypoint)())
Constructs a new Task.
~Task ()
void reset ()
Resets or initializes the task's stack frame.
Private Attributes
CPUState * cpustate
Pointer to the saved register state inside the stack. Used by the scheduler to restore this task's context.
void(* m_entrypoint)()
The function to execute when the task starts.
uint16_t m_segmentSelector
The Code Segment selector to run this task in (Kernel vs User).
uint8_t stack [4096]
The dedicated kernel stack for this task.
Detailed Description
Represents a single unit of execution (a thread or process) in the OS.
Each Task maintains its own private stack memory (4KB) and a pointer to its saved CPU state.
Definition at line 32 of file kmultitasking.hpp.
Constructor & Destructor Documentation
Task()
Task::Task (GDT_Manager * gdt_manager, void(*)() entrypoint)
Constructs a new Task.
Parameters
gdt_manager Pointer to the GDT Manager to retrieve the correct Code Segment selector.
entrypoint The function pointer where execution should begin.
Definition at line 7 of file kmultitasking.cpp.
{
    this->m_entrypoint = entrypoint;
    this->m_segmentSelector = gdt_manager->kernel_CS_selector();
}
References essential::GDT_Manager::kernel_CS_selector(), m_entrypoint, and m_segmentSelector.
~Task()
Task::~Task ()
Definition at line 12 of file kmultitasking.cpp.
{}
Member Function Documentation
reset()
void Task::reset ()
Resets or initializes the task's stack frame.
This function sets up a "fake" interrupt stack frame at the top of the stack array. It sets the instruction pointer (EIP) to the entrypoint and the stack pointer (ESP) to the onTaskExit handler. This must be called before the task is run for the first time.
Definition at line 14 of file kmultitasking.cpp.
{
    cpustate = (CPUState*) (stack + 4096 - sizeof(CPUState));
    cpustate->eax = 0; cpustate->ebx = 0; cpustate->ecx = 0; cpustate->edx = 0;
    cpustate->esi = 0; cpustate->edi = 0; cpustate->ebp = 0;
    cpustate->gs = 0x10;
    cpustate->fs = 0x10;
    cpustate->es = 0x10;
    cpustate->ds = 0x10;
    cpustate->error = 0;
    cpustate->eip = (uint32_t)m_entrypoint;
    cpustate->cs = m_segmentSelector;
    cpustate->eflags = 0x202;
    cpustate->esp = (uint32_t)TaskManager::onTaskExit;
}
References cpustate, essential::CPUState::cs, essential::CPUState::ds, essential::CPUState::eax, essential::CPUState::ebp, essential::CPUState::ebx, essential::CPUState::ecx, essential::CPUState::edi, essential::CPUState::edx, essential::CPUState::eflags, essential::CPUState::eip, essential::CPUState::error, essential::CPUState::es, essential::CPUState::esi, essential::CPUState::esp, essential::CPUState::fs, essential::CPUState::gs, m_entrypoint, m_segmentSelector, essential::TaskManager::onTaskExit(), and stack.
Referenced by essential::TaskManager::addTask().
Member Data Documentation
cpustate
CPUState* essential::Task::cpustate private
Pointer to the saved register state inside the stack. Used by the scheduler to restore this task's context.
Definition at line 40 of file kmultitasking.hpp.
Referenced by reset(), and essential::TaskManager::schedule().
m_entrypoint
void(* essential::Task::m_entrypoint) () private
The function to execute when the task starts.
Definition at line 43 of file kmultitasking.hpp.
Referenced by Task(), and reset().
m_segmentSelector
uint16_t essential::Task::m_segmentSelector private
The Code Segment selector to run this task in (Kernel vs User).
Definition at line 46 of file kmultitasking.hpp.
Referenced by Task(), and reset().
stack
uint8_t essential::Task::stack[4096] private
The dedicated kernel stack for this task.
Definition at line 36 of file kmultitasking.hpp.
Referenced by reset().
The documentation for this class was generated from the following files:
kmultitasking.hpp
kmultitasking.cpp