OSOS - Documentation: /home/shreekar/Desktop/Building_own_OS/OSOS/libk_src/basic/kiostream.cpp File Reference
kiostream.cpp File Reference
#include "basic/kiostream.hpp"
#include "driver/kmouse.hpp"
Macros
#define MAGIC_HEIGHT 25
#define MAGIC_WIDTH 80
#define TAB_WIDTH 4
Functions
static void doubleToString (double d, char *buffer, int precision)
Converts a double-precision floating point number to a string.
static double power (double base, int exp)
Calculates the power of a number.
static void printCharStr (const char *str)
Internal function to print a null-terminated string to video memory.
static void printHex (uintptr_t n, int digits)
Prints a hexadecimal number with leading zeros.
static void reverse (char *str, int length)
Reverses a string in place.
static void ullToString (unsigned long long n, char *buffer, int base, int is_signed, int uppercase)
Converts an unsigned long long integer to a string.
Variables
static int cursor_x_ = 0
static int cursor_y_ = 0
static hardware_communication::Port8Bit vgaDataPort (0x3D5)
static hardware_communication::Port8Bit vgaIndexPort (0x3D4)
Macro Definition Documentation
MAGIC_HEIGHT
#define MAGIC_HEIGHT 25
Definition at line 8 of file kiostream.cpp.
MAGIC_WIDTH
#define MAGIC_WIDTH 80
Definition at line 7 of file kiostream.cpp.
TAB_WIDTH
#define TAB_WIDTH 4
Definition at line 9 of file kiostream.cpp.
Function Documentation
doubleToString()
static void doubleToString (double d, char * buffer, int precision) static
Converts a double-precision floating point number to a string.
Parameters
d The double to convert.
buffer The output buffer to store the string.
precision The number of digits after the decimal point.
Definition at line 216 of file kiostream.cpp.
{
    if (precision < 0)
        precision = 6;
    char *ptr = buffer;
    if (d < 0)
    {
        *ptr++ = '-';
        d = -d;
    }
    unsigned long long int_part = (unsigned long long)d;
    double frac_part = d - (double)int_part;
    ullToString(int_part, ptr, 10, 0, 0);
    while (*ptr) ptr++;
    *ptr++ = '.';
    unsigned long long frac_as_ull = (unsigned long long)(frac_part * power(10, precision) + 0.5);
    char frac_buffer[32];
    ullToString(frac_as_ull, frac_buffer, 10, 0, 0);
    int frac_len = 0;
    while(frac_buffer[frac_len] != '\0') frac_len++;
    int padding = precision - frac_len;
    for (int i = 0; i < padding; i++)
        *ptr++ = '0';
    char* frac_ptr = frac_buffer;
    while(*frac_ptr) *ptr++ = *frac_ptr++;
    *ptr = '\0';
}
References power(), and ullToString().
Referenced by basic::printf().
power()
static double power (double base, int exp) static
Calculates the power of a number.
Parameters
base The base.
exp The exponent.
Returns
The result of base raised to the power of exp.
Definition at line 204 of file kiostream.cpp.
{
    double res = 1.0;
    for (int i = 0; i < exp; ++i)
        res *= base;
    return res;
}
References base.
Referenced by doubleToString().
printCharStr()
static void printCharStr (const char * str) static
Internal function to print a null-terminated string to video memory.
Parameters
str The string to print.
Definition at line 50 of file kiostream.cpp.
{
    uint16_t *video_memory = (uint16_t *)0xb8000;
    // FOR TEXT : Attribute for Gray-White (0x7) text on a Black (0x0) background (last 2 bytes (LSBs) are not used for color).
    const uint16_t color_attribute = 0x0700;
    // --- MOUSE-SAFE PRINTING: remove mouse ---
    int mouse_offset = driver::MouseDriver::__mouse_y_ * MAGIC_WIDTH + driver::MouseDriver::__mouse_x_;
    if(mouse_offset>=0) video_memory[mouse_offset] = driver::MouseDriver::old_char_under_mouse_pointer;
    for (int i = 0; str[i] != '\0'; i++)
    {
        if (str[i] == '\n')
        {
            cursor_y_++;
            cursor_x_ = 0;
        }
        else if (str[i] == '\b')
        {
            if (cursor_x_ > 0)
            {
                cursor_x_--;
                int offset = cursor_y_ * MAGIC_WIDTH + cursor_x_;
                video_memory[offset] = color_attribute | ' ';
            }
        }
        else if (str[i] == '\r')
        {
            cursor_x_ = 0;
        }
        else if (str[i] == '\t')
        {
            cursor_x_ = cursor_x_ + (TAB_WIDTH - (cursor_x_ % TAB_WIDTH));
        }
        else
        {
            int offset = cursor_y_ * MAGIC_WIDTH + cursor_x_;
            video_memory[offset] = color_attribute | str[i];
            cursor_x_++;
        }
        if (cursor_x_ >= MAGIC_WIDTH)
        {
            cursor_y_++;
            cursor_x_ = 0;
        }
        if (cursor_y_ >= MAGIC_HEIGHT)
        {
            for (int y = 0; y < (MAGIC_HEIGHT - 1); y++)
            {
                for (int x = 0; x < MAGIC_WIDTH; x++)
                {
                    int current_offset = y * MAGIC_WIDTH + x;
                    int next_line_offset = (y + 1) * MAGIC_WIDTH + x;
                    video_memory[current_offset] = video_memory[next_line_offset];
                }
            }
            int last_line_offset_start = (MAGIC_HEIGHT - 1) * MAGIC_WIDTH;
            for (int x = 0; x < MAGIC_WIDTH; x++)
            {
                video_memory[last_line_offset_start + x] = color_attribute | ' ';
            }
            cursor_y_ = MAGIC_HEIGHT - 1;
            cursor_x_ = 0;
        }
    }
    // --- MOUSE-SAFE PRINTING: add mouse again---
    driver::MouseDriver::old_char_under_mouse_pointer = video_memory[mouse_offset];
    if(mouse_offset>=0) video_memory[mouse_offset] = driver::MouseDriver::mouse_block_video_mem_value(driver::MouseDriver::old_char_under_mouse_pointer, MOUSE_POINTER_COLOR);
}
References driver::MouseDriver::__mouse_x_, driver::MouseDriver::__mouse_y_, cursor_x_, cursor_y_, MAGIC_HEIGHT, MAGIC_WIDTH, driver::MouseDriver::mouse_block_video_mem_value(), MOUSE_POINTER_COLOR, driver::MouseDriver::old_char_under_mouse_pointer, and TAB_WIDTH.
Referenced by basic::printf(), and printHex().
printHex()
static void printHex (uintptr_t n, int digits) static
Prints a hexadecimal number with leading zeros.
Parameters
n The number to print.
digits The total number of digits to print (padded with zeros).
Definition at line 257 of file kiostream.cpp.
{
    char buffer[32];
    ullToString(n, buffer, 16, 0, 1); // Use uppercase for pointers typically
    int len = 0;
    while (buffer[len] != '\0') {
        len++;
    }
    for (int i = 0; i < digits - len; i++) {
        printCharStr("0");
    }
    printCharStr(buffer);
}
References len, printCharStr(), and ullToString().
Referenced by basic::printf().
reverse()
static void reverse (char * str, int length) static
Reverses a string in place.
Parameters
str The string to reverse.
length The length of the string.
Definition at line 146 of file kiostream.cpp.
{
    int start = 0;
    int end = length - 1;
    while (start < end)
    {
        char temp = str[start];
        str[start] = str[end];
        str[end] = temp;
        start++;
        end--;
    }
}
Referenced by ullToString().
ullToString()
static void ullToString (unsigned long long n, char * buffer, int base, int is_signed, int uppercase) static
Converts an unsigned long long integer to a string.
Parameters
n The number to convert.
buffer The output buffer to store the string.
base The numerical base (e.g., 2, 8, 10, 16).
is_signed Whether the original number was signed (for handling negative sign).
uppercase Whether to use uppercase letters for bases > 10.
Definition at line 166 of file kiostream.cpp.
{
    int i = 0;
    int isNegative = 0;
    if (n == 0)
    {
        buffer[i++] = '0';
        buffer[i] = '\0';
        return;
    }
    if (is_signed && (long long)n < 0)
    {
        isNegative = 1;
        n = -(long long)n;
    }
    while (n != 0)
    {
        int rem = n % base;
        buffer[i++] = (rem > 9) ? ((rem - 10) + (uppercase ? 'A' : 'a')) : (rem + '0');
        n = n / base;
    }
    if (isNegative)
    {
        buffer[i++] = '-';
    }
    buffer[i] = '\0';
    reverse(buffer, i);
}
References base, and reverse().
Referenced by doubleToString(), basic::printf(), and printHex().
Variable Documentation
cursor_x_
int cursor_x_ = 0 static
Definition at line 4 of file kiostream.cpp.
Referenced by basic::__clearScreen(), printCharStr(), basic::printf(), and basic::update_cursor().
cursor_y_
int cursor_y_ = 0 static
Definition at line 5 of file kiostream.cpp.
Referenced by basic::__clearScreen(), printCharStr(), basic::printf(), and basic::update_cursor().
vgaDataPort
hardware_communication::Port8Bit vgaDataPort(0x3D5) (0x3D5) static
Referenced by basic::disable_cursor(), basic::enable_cursor(), and basic::update_cursor().
vgaIndexPort
hardware_communication::Port8Bit vgaIndexPort(0x3D4) (0x3D4) static
Referenced by basic::disable_cursor(), basic::enable_cursor(), and basic::update_cursor().