.TH "libk_header/basic Directory Reference" 3 "Fri Oct 24 2025 00:21:12" "OSOS - Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libk_header/basic Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBkiostream\&.hpp\fP"
.br
.ti -1c
.RI "file \fBkmemory\&.hpp\fP"
.br
.ti -1c
.RI "file \fBmultiboot\&.hpp\fP"
.br
.in -1c
