.TH "/home/shreekar/Desktop/Building_own_OS/OSOS/kernel_src Directory Reference" 3 "Fri Oct 24 2025 10:32:01" "OSOS - Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/shreekar/Desktop/Building_own_OS/OSOS/kernel_src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBkernel\&.cpp\fP"
.br
.in -1c
