.TH "libk_src/driver Directory Reference" 3 "Thu Oct 23 2025 23:59:22" "OSOS - 32-bit Operating System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libk_src/driver Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBkdriver\&.cpp\fP"
.br
.ti -1c
.RI "file \fBkkeyboard\&.cpp\fP"
.br
.ti -1c
.RI "file \fBkmouse\&.cpp\fP"
.br
.in -1c
