.TH "/home/shreekar/Desktop/Building_own_OS/OSOS Directory Reference" 3 "Fri Oct 24 2025 10:32:01" "OSOS - Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/shreekar/Desktop/Building_own_OS/OSOS Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBkernel_src\fP"
.br
.ti -1c
.RI "directory \fBlibk_header\fP"
.br
.ti -1c
.RI "directory \fBlibk_src\fP"
.br
.in -1c
