.TH "driver::MouseEventHandler" 3 "Thu Oct 23 2025 23:59:22" "OSOS - 32-bit Operating System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
driver::MouseEventHandler
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'kmouse\&.hpp'\fP
.PP
Inherited by \fBMouseEventHandler_for_kernel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMouseEventHandler\fP ()"
.br
.ti -1c
.RI "virtual \fB~MouseEventHandler\fP ()"
.br
.ti -1c
.RI "virtual void \fBonMouseDown\fP (uint8_t button)=0"
.br
.ti -1c
.RI "virtual void \fBonMouseMove\fP (int8_t delta_x, int8_t delta_y)=0"
.br
.ti -1c
.RI "virtual void \fBonMouseUp\fP (uint8_t button)=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB29\fP of file \fBkmouse\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "driver::MouseEventHandler::MouseEventHandler ()"

.PP
Definition at line \fB5\fP of file \fBkmouse\&.cpp\fP\&..PP
.nf
5 {}
.fi

.SS "driver::MouseEventHandler::~MouseEventHandler ()\fC [virtual]\fP"

.PP
Definition at line \fB6\fP of file \fBkmouse\&.cpp\fP\&..PP
.nf
6 {}
.fi

.SH "Member Function Documentation"
.PP 
.SS "virtual void driver::MouseEventHandler::onMouseDown (uint8_t button)\fC [pure virtual]\fP"

.PP
Implemented in \fBMouseEventHandler_for_kernel\fP\&.
.SS "virtual void driver::MouseEventHandler::onMouseMove (int8_t delta_x, int8_t delta_y)\fC [pure virtual]\fP"

.PP
Implemented in \fBMouseEventHandler_for_kernel\fP\&.
.PP
Referenced by \fBdriver::MouseDriver::handleInterrupt()\fP\&.
.SS "virtual void driver::MouseEventHandler::onMouseUp (uint8_t button)\fC [pure virtual]\fP"

.PP
Implemented in \fBMouseEventHandler_for_kernel\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OSOS - 32-bit Operating System from the source code\&.
