.TH "driver::DriverManager" 3 "Thu Oct 23 2025 23:59:22" "OSOS - 32-bit Operating System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
driver::DriverManager
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'kdriver\&.hpp'\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDriverManager\fP ()"
.br
.ti -1c
.RI "\fB~DriverManager\fP ()"
.br
.ti -1c
.RI "void \fBactivateAll\fP ()"
.br
.ti -1c
.RI "void \fBaddDriver\fP (\fBDriver\fP *)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBDriver\fP * \fBdrivers\fP [\fBMAX_NUMDRIVERS\fP]"
.br
.ti -1c
.RI "int \fBnumDrivers\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB17\fP of file \fBkdriver\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "driver::DriverManager::DriverManager ()"

.PP
Definition at line \fB7\fP of file \fBkdriver\&.cpp\fP\&..PP
.nf
7                                   {
8     numDrivers=0;
9 }
.fi

.SS "driver::DriverManager::~DriverManager ()"

.PP
Definition at line \fB10\fP of file \fBkdriver\&.cpp\fP\&..PP
.nf
10 {}
.fi

.SH "Member Function Documentation"
.PP 
.SS "void driver::DriverManager::activateAll ()"

.PP
Definition at line \fB17\fP of file \fBkdriver\&.cpp\fP\&..PP
.nf
17                                      {
18     for(int i=0; i<numDrivers; i++){
19         drivers[i]\->activate();
20     }
21 }
.fi

.PP
Referenced by \fBkernelMain()\fP\&.
.SS "void driver::DriverManager::addDriver (\fBdriver::Driver\fP * driver)"

.PP
Definition at line \fB12\fP of file \fBkdriver\&.cpp\fP\&..PP
.nf
12                                                        {
13     drivers[numDrivers]=driver;
14     numDrivers++;
15 }
.fi

.PP
Referenced by \fBkernelMain()\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBDriver\fP* driver::DriverManager::drivers[\fBMAX_NUMDRIVERS\fP]\fC [private]\fP"

.PP
Definition at line \fB19\fP of file \fBkdriver\&.hpp\fP\&.
.SS "int driver::DriverManager::numDrivers\fC [private]\fP"

.PP
Definition at line \fB20\fP of file \fBkdriver\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OSOS - 32-bit Operating System from the source code\&.
