.TH "driver::Driver" 3 "Thu Oct 23 2025 23:59:22" "OSOS - 32-bit Operating System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
driver::Driver
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'kdriver\&.hpp'\fP
.PP
Inherited by \fBdriver::KeyboardDriver\fP, and \fBdriver::MouseDriver\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDriver\fP ()"
.br
.ti -1c
.RI "virtual \fB~Driver\fP ()"
.br
.ti -1c
.RI "virtual void \fBactivate\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBdeactivate\fP ()=0"
.br
.ti -1c
.RI "virtual int \fBreset\fP ()=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBkdriver\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "driver::Driver::Driver ()"

.PP
Definition at line \fB3\fP of file \fBkdriver\&.cpp\fP\&..PP
.nf
3 {}
.fi

.SS "driver::Driver::~Driver ()\fC [virtual]\fP"

.PP
Definition at line \fB4\fP of file \fBkdriver\&.cpp\fP\&..PP
.nf
4 {}
.fi

.SH "Member Function Documentation"
.PP 
.SS "virtual void driver::Driver::activate ()\fC [pure virtual]\fP"

.PP
Implemented in \fBdriver::KeyboardDriver\fP, and \fBdriver::MouseDriver\fP\&.
.SS "virtual void driver::Driver::deactivate ()\fC [pure virtual]\fP"

.PP
Implemented in \fBdriver::KeyboardDriver\fP, and \fBdriver::MouseDriver\fP\&.
.SS "virtual int driver::Driver::reset ()\fC [pure virtual]\fP"

.PP
Implemented in \fBdriver::KeyboardDriver\fP, and \fBdriver::MouseDriver\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OSOS - 32-bit Operating System from the source code\&.
