.TH "driver::KeyboardEventHandler" 3 "Fri Oct 24 2025 00:08:28" "OSOS - 32-bit Operating System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
driver::KeyboardEventHandler
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'kkeyboard\&.hpp'\fP
.PP
Inherited by \fBKeyboardEventHandler_for_kernel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBKeyboardEventHandler\fP ()"
.br
.ti -1c
.RI "virtual \fB~KeyboardEventHandler\fP ()"
.br
.ti -1c
.RI "virtual void \fBonKeyDown\fP (char ascii)=0"
.br
.ti -1c
.RI "virtual void \fBonKeyUp\fP (char ascii)=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB9\fP of file \fBkkeyboard\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "driver::KeyboardEventHandler::KeyboardEventHandler ()"

.PP
Definition at line \fB6\fP of file \fBkkeyboard\&.cpp\fP\&..PP
.nf
6 {}
.fi

.SS "driver::KeyboardEventHandler::~KeyboardEventHandler ()\fC [virtual]\fP"

.PP
Definition at line \fB7\fP of file \fBkkeyboard\&.cpp\fP\&..PP
.nf
7 {}
.fi

.SH "Member Function Documentation"
.PP 
.SS "virtual void driver::KeyboardEventHandler::onKeyDown (char ascii)\fC [pure virtual]\fP"

.PP
Implemented in \fBKeyboardEventHandler_for_kernel\fP\&.
.SS "virtual void driver::KeyboardEventHandler::onKeyUp (char ascii)\fC [pure virtual]\fP"

.PP
Implemented in \fBKeyboardEventHandler_for_kernel\fP\&.
.PP
Referenced by \fBdriver::KeyboardDriver::handleInterrupt()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OSOS - 32-bit Operating System from the source code\&.
