.TH "driver::Driver" 3 "Fri Oct 24 2025 10:32:01" "OSOS - Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
driver::Driver \- Base class (interface) for all hardware drivers in the operating system\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'kdriver\&.hpp'\fP
.PP
Inherited by \fBdriver::KeyboardDriver\fP, and \fBdriver::MouseDriver\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDriver\fP ()"
.br
.RI "Default constructor for the base \fBDriver\fP class\&. "
.ti -1c
.RI "virtual \fB~Driver\fP ()"
.br
.RI "Default destructor for the base \fBDriver\fP class\&. "
.ti -1c
.RI "virtual void \fBactivate\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBdeactivate\fP ()=0"
.br
.ti -1c
.RI "virtual int \fBreset\fP ()=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Base class (interface) for all hardware drivers in the operating system\&. 
.PP
Definition at line \fB6\fP of file \fBkdriver\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "driver::Driver::Driver ()"

.PP
Default constructor for the base \fBDriver\fP class\&. 
.PP
Definition at line \fB4\fP of file \fBkdriver\&.cpp\fP\&..PP
.nf
4 {}
.fi

.SS "driver::Driver::~Driver ()\fC [virtual]\fP"

.PP
Default destructor for the base \fBDriver\fP class\&. 
.PP
Definition at line \fB6\fP of file \fBkdriver\&.cpp\fP\&..PP
.nf
6 {}
.fi

.SH "Member Function Documentation"
.PP 
.SS "virtual void driver::Driver::activate ()\fC [pure virtual]\fP"

.PP
Implemented in \fBdriver::KeyboardDriver\fP, and \fBdriver::MouseDriver\fP\&.
.SS "virtual void driver::Driver::deactivate ()\fC [pure virtual]\fP"

.PP
Implemented in \fBdriver::KeyboardDriver\fP, and \fBdriver::MouseDriver\fP\&.
.SS "virtual int driver::Driver::reset ()\fC [pure virtual]\fP"

.PP
Implemented in \fBdriver::KeyboardDriver\fP, and \fBdriver::MouseDriver\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OSOS - Documentation from the source code\&.
