.TH "driver::DriverManager" 3 "Fri Oct 24 2025 10:32:01" "OSOS - Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
driver::DriverManager \- Manages a collection of \fBDriver\fP objects, facilitating their activation and organization\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'kdriver\&.hpp'\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDriverManager\fP ()"
.br
.RI "Constructs a new \fBDriverManager\fP object, initializing the driver count to zero\&. "
.ti -1c
.RI "\fB~DriverManager\fP ()"
.br
.RI "Destroys the \fBDriverManager\fP object\&. "
.ti -1c
.RI "void \fBactivateAll\fP ()"
.br
.RI "Activates all drivers currently registered with the manager\&. "
.ti -1c
.RI "void \fBaddDriver\fP (\fBDriver\fP *)"
.br
.RI "Adds a driver to the manager's list\&. "
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBDriver\fP * \fBdrivers\fP [\fBMAX_NUMDRIVERS\fP]"
.br
.ti -1c
.RI "int \fBnumDrivers\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Manages a collection of \fBDriver\fP objects, facilitating their activation and organization\&. 
.PP
Definition at line \fB18\fP of file \fBkdriver\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "driver::DriverManager::DriverManager ()"

.PP
Constructs a new \fBDriverManager\fP object, initializing the driver count to zero\&. 
.PP
Definition at line \fB10\fP of file \fBkdriver\&.cpp\fP\&..PP
.nf
10                                   {
11     numDrivers=0;
12 }
.fi

.SS "driver::DriverManager::~DriverManager ()"

.PP
Destroys the \fBDriverManager\fP object\&. 
.PP
Definition at line \fB14\fP of file \fBkdriver\&.cpp\fP\&..PP
.nf
14 {}
.fi

.SH "Member Function Documentation"
.PP 
.SS "void driver::DriverManager::activateAll ()"

.PP
Activates all drivers currently registered with the manager\&. 
.PP
Definition at line \fB24\fP of file \fBkdriver\&.cpp\fP\&..PP
.nf
24                                      {
25     for(int i=0; i<numDrivers; i++){
26         drivers[i]\->activate();
27     }
28 }
.fi

.PP
Referenced by \fBkernelMain()\fP\&.
.SS "void driver::DriverManager::addDriver (\fBdriver::Driver\fP * driver)"

.PP
Adds a driver to the manager's list\&. 
.PP
\fBParameters\fP
.RS 4
\fIdriver\fP A pointer to the driver object to be added\&. 
.RE
.PP

.PP
Definition at line \fB18\fP of file \fBkdriver\&.cpp\fP\&..PP
.nf
18                                                        {
19     drivers[numDrivers]=driver;
20     numDrivers++;
21 }
.fi

.PP
Referenced by \fBkernelMain()\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBDriver\fP* driver::DriverManager::drivers[\fBMAX_NUMDRIVERS\fP]\fC [private]\fP"

.PP
Definition at line \fB20\fP of file \fBkdriver\&.hpp\fP\&.
.SS "int driver::DriverManager::numDrivers\fC [private]\fP"

.PP
Definition at line \fB21\fP of file \fBkdriver\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OSOS - Documentation from the source code\&.
