.TH "essential::GDT_row" 3 "Fri Oct 24 2025 00:21:12" "OSOS - Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
essential::GDT_row
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'kgdt\&.hpp'\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGDT_row\fP ()"
.br
.ti -1c
.RI "\fBGDT_row\fP (uint32_t \fBbase\fP, uint32_t \fBlimit\fP, uint8_t access_byte, uint8_t gran_byte)"
.br
.ti -1c
.RI "\fB~GDT_row\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBaccess\fP"
.br
.ti -1c
.RI "uint8_t \fBbase_high\fP"
.br
.ti -1c
.RI "uint16_t \fBbase_low\fP"
.br
.ti -1c
.RI "uint8_t \fBbase_middle\fP"
.br
.ti -1c
.RI "uint8_t \fBgranularity\fP"
.br
.ti -1c
.RI "uint16_t \fBlimit_low\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB34\fP of file \fBkgdt\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "essential::GDT_row::GDT_row (uint32_t base, uint32_t limit, uint8_t access_byte, uint8_t gran_byte)"

.PP
Definition at line \fB8\fP of file \fBkgdt\&.cpp\fP\&..PP
.nf
8                                                                                                {
9     this\->limit_low   = (limit & 0xFFFF);
10     this\->base_low    = (base & 0xFFFF);
11     this\->base_middle = (base >> 16) & 0xFF;
12     this\->base_high   = (base >> 24) & 0xFF;
13 
14     // The upper 4 bits of the 20\-bit limit go into the lower 4 bits of the granularity byte\&.
15     this\->granularity = ((limit >> 16) & 0x0F);
16     // The granularity flags (G, D/B, L, AVL) go into the upper 4 bits\&.
17     this\->granularity |= (gran_byte & 0xF0);
18     // Set the access flags for this segment\&.
19     this\->access = access_byte;
20 }
.fi

.PP
References \fBaccess\fP, \fBbase_high\fP, \fBbase_low\fP, \fBbase_middle\fP, \fBgranularity\fP, and \fBlimit_low\fP\&.
.SS "essential::GDT_row::GDT_row ()"

.PP
Definition at line \fB6\fP of file \fBkgdt\&.cpp\fP\&..PP
.nf
6 : limit_low(0), base_low(0), base_middle(0), access(0), granularity(0), base_high(0) {}
.fi

.SS "essential::GDT_row::~GDT_row ()"

.PP
Definition at line \fB22\fP of file \fBkgdt\&.cpp\fP\&..PP
.nf
22 {}
.fi

.SH "Member Data Documentation"
.PP 
.SS "uint8_t essential::GDT_row::access\fC [private]\fP"

.PP
Definition at line \fB39\fP of file \fBkgdt\&.hpp\fP\&.
.PP
Referenced by \fBessential::GDT::printLoadedTable()\fP\&.
.SS "uint8_t essential::GDT_row::base_high\fC [private]\fP"

.PP
Definition at line \fB41\fP of file \fBkgdt\&.hpp\fP\&.
.PP
Referenced by \fBessential::GDT::printLoadedTable()\fP\&.
.SS "uint16_t essential::GDT_row::base_low\fC [private]\fP"

.PP
Definition at line \fB37\fP of file \fBkgdt\&.hpp\fP\&.
.PP
Referenced by \fBessential::GDT::printLoadedTable()\fP\&.
.SS "uint8_t essential::GDT_row::base_middle\fC [private]\fP"

.PP
Definition at line \fB38\fP of file \fBkgdt\&.hpp\fP\&.
.PP
Referenced by \fBessential::GDT::printLoadedTable()\fP\&.
.SS "uint8_t essential::GDT_row::granularity\fC [private]\fP"

.PP
Definition at line \fB40\fP of file \fBkgdt\&.hpp\fP\&.
.PP
Referenced by \fBessential::GDT::printLoadedTable()\fP\&.
.SS "uint16_t essential::GDT_row::limit_low\fC [private]\fP"

.PP
Definition at line \fB36\fP of file \fBkgdt\&.hpp\fP\&.
.PP
Referenced by \fBessential::GDT::printLoadedTable()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OSOS - Documentation from the source code\&.
