.TH "essential::GDT" 3 "Fri Oct 24 2025 10:32:01" "OSOS - Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
essential::GDT \- Manages the Global Descriptor Table (\fBGDT\fP), holding segment descriptors for the CPU\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'kgdt\&.hpp'\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGDT\fP ()"
.br
.RI "Constructs a new \fBGDT\fP object and initializes the standard kernel/user segments\&. "
.ti -1c
.RI "\fB~GDT\fP ()"
.br
.RI "Destroys the \fBGDT\fP object\&. "
.ti -1c
.RI "void \fBinstallTable\fP ()"
.br
.RI "Loads this \fBGDT\fP into the CPU's GDTR and reloads all segment registers\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static uint16_t \fBkernel_CS_selector\fP ()"
.br
.RI "(Static) Gets the kernel code segment selector\&. "
.ti -1c
.RI "static uint16_t \fBkernel_DS_selector\fP ()"
.br
.RI "(Static) Gets the kernel data segment selector\&. "
.ti -1c
.RI "static void \fBprintLoadedTable\fP ()"
.br
.RI "(Static) Prints the details of all entries in the currently loaded \fBGDT\fP\&. "
.ti -1c
.RI "static void \fBprintLoadedTableHeader\fP ()"
.br
.RI "(Static) Prints the header information (base, limit, count) of the currently loaded \fBGDT\fP\&. "
.ti -1c
.RI "static uint16_t \fBuser_CS_selector\fP ()"
.br
.RI "(Static) Gets the user code segment selector\&. "
.ti -1c
.RI "static uint16_t \fBuser_DS_selector\fP ()"
.br
.RI "(Static) Gets the user data segment selector\&. "
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "uintptr_t \fBbase\fP"
.br
.ti -1c
.RI "\fBGDT_row\fP \fBkernel_CS\fP"
.br
.ti -1c
.RI "\fBGDT_row\fP \fBkernel_DS\fP"
.br
.ti -1c
.RI "uint16_t \fBlimit\fP"
.br
.ti -1c
.RI "\fBGDT_row\fP \fBnullSegment\fP"
.br
.ti -1c
.RI "\fBGDT_row\fP \fBuser_CS\fP"
.br
.ti -1c
.RI "\fBGDT_row\fP \fBuser_DS\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Manages the Global Descriptor Table (\fBGDT\fP), holding segment descriptors for the CPU\&. 
.PP
Definition at line \fB53\fP of file \fBkgdt\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "essential::GDT::GDT ()"

.PP
Constructs a new \fBGDT\fP object and initializes the standard kernel/user segments\&. 
.PP
Definition at line \fB30\fP of file \fBkgdt\&.cpp\fP\&..PP
.nf
32     : nullSegment(), // First entry must be a null descriptor\&.
33       kernel_CS(0, 0xFFFFFFFF, GDT_ACCESS_CODE_PL0, GDT_GRAN_FLAGS),
34       kernel_DS(0, 0xFFFFFFFF, GDT_ACCESS_DATA_PL0, GDT_GRAN_FLAGS),
35       user_CS(0, 0xFFFFFFFF, GDT_ACCESS_CODE_PL3, GDT_GRAN_FLAGS),
36       user_DS(0, 0xFFFFFFFF, GDT_ACCESS_DATA_PL3, GDT_GRAN_FLAGS)
37 {
38     // The GDT limit is its total size in bytes minus 1\&.
39     // 5 entries * 8 bytes/entry = 40 bytes\&. Limit = 39 (0x27)\&.
40     limit = (sizeof(essential::GDT_row) * 5) \- 1;
41     
42     // The base address is the address of the first entry in our table\&.
43     base = (uintptr_t)&this\->nullSegment;
44 }
.fi

.PP
References \fBbase\fP, \fBlimit\fP, and \fBnullSegment\fP\&.
.SS "essential::GDT::~GDT ()"

.PP
Destroys the \fBGDT\fP object\&. 
.PP
Definition at line \fB47\fP of file \fBkgdt\&.cpp\fP\&..PP
.nf
47 {}
.fi

.SH "Member Function Documentation"
.PP 
.SS "void essential::GDT::installTable ()"

.PP
Loads this \fBGDT\fP into the CPU's GDTR and reloads all segment registers\&. 
.PP
Definition at line \fB51\fP of file \fBkgdt\&.cpp\fP\&..PP
.nf
51                                 {
52     // A structure that matches the 6\-byte format required by the 'lgdt' instruction\&.
53     struct GDT_Pointer {
54         uint16_t limit;
55         uint32_t base; // Use uint32_t for our i686 (32\-bit) target
56     } __attribute__((packed));
57 
58     GDT_Pointer gdt_ptr;
59     gdt_ptr\&.limit = this\->limit;
60     gdt_ptr\&.base = this\->base;
61     
62     asm volatile(
63         // Load the address of our GDT_Pointer structure into the GDTR\&.
64         "lgdt (%0)\\n\\t"
65 
66         // Reload all data segment registers with the kernel data selector\&.
67         "mov $0x10, %%ax\\n\\t"   // 0x10 is the selector for kernel_DS
68         "mov %%ax, %%ds\\n\\t"
69         "mov %%ax, %%es\\n\\t"
70         "mov %%ax, %%fs\\n\\t"
71         "mov %%ax, %%gs\\n\\t"
72         "mov %%ax, %%ss\\n\\t"
73 
74         // Perform a 32\-bit far jump to reload the CS register and flush the CPU pipeline\&.
75         "jmp $0x08, $flush_cs\\n\\t" // 0x08 is the selector for kernel_CS
76         "flush_cs:\\n\\t"
77         : // No output operands
78         : "r"(&gdt_ptr) // Input: address of our GDT_Pointer
79         : "memory", "eax" // Clobbered registers
80     );
81     basic::printf("GDT Installed\\n");
82 }
.fi

.PP
References \fB__attribute__\fP, \fBbase\fP, \fBlimit\fP, and \fBbasic::printf()\fP\&.
.PP
Referenced by \fBkernelMain()\fP\&.
.SS "uint16_t essential::GDT::kernel_CS_selector ()\fC [static]\fP"

.PP
(Static) Gets the kernel code segment selector\&. 
.PP
\fBReturns\fP
.RS 4
The 16-bit selector value\&. 
.RE
.PP

.PP
Definition at line \fB146\fP of file \fBkgdt\&.cpp\fP\&..PP
.nf
146 { return sizeof(essential::GDT_row) * 1; } // Selector 0x08
.fi

.PP
Referenced by \fBhardware_communication::InterruptManager::InterruptManager()\fP\&.
.SS "uint16_t essential::GDT::kernel_DS_selector ()\fC [static]\fP"

.PP
(Static) Gets the kernel data segment selector\&. 
.PP
\fBReturns\fP
.RS 4
The 16-bit selector value\&. 
.RE
.PP

.PP
Definition at line \fB149\fP of file \fBkgdt\&.cpp\fP\&..PP
.nf
149 { return sizeof(essential::GDT_row) * 2; } // Selector 0x10
.fi

.SS "void essential::GDT::printLoadedTable ()\fC [static]\fP"

.PP
(Static) Prints the details of all entries in the currently loaded \fBGDT\fP\&. 
.PP
Definition at line \fB85\fP of file \fBkgdt\&.cpp\fP\&..PP
.nf
85                                     {
86     struct GDT_Pointer {
87         uint16_t limit;
88         uint32_t base;
89     } __attribute__((packed));
90 
91     GDT_Pointer gdtr;
92     // Store the current GDT register contents into our struct\&.
93     asm volatile("sgdt %0" : "=m"(gdtr));
94 
95     basic::printf("\-\-\-\\n");
96     basic::printf("INFO about : Currently Loaded GDT\\n");
97     basic::printf("Base Address: %#x\\n", gdtr\&.base);
98     basic::printf("Limit: %#x (%d bytes)\\n", gdtr\&.limit, gdtr\&.limit);
99     basic::printf("Entries: %d\\n", (gdtr\&.limit + 1) / sizeof(essential::GDT_row));
100     basic::printf("\-\-\-\\n");
101 
102     essential::GDT_row* gdt_entries = (essential::GDT_row*)gdtr\&.base;
103     int num_entries = (gdtr\&.limit + 1) / sizeof(essential::GDT_row);
104 
105     for (int i = 0; i < num_entries; i++) {
106         essential::GDT_row entry = gdt_entries[i];
107 
108         // Reconstruct the base and limit from the scattered fields\&.
109         uint32_t base = entry\&.base_high << 24 | entry\&.base_middle << 16 | entry\&.base_low;
110         uint32_t limit = (entry\&.granularity & 0x0F) << 16 | entry\&.limit_low;
111         
112         // If the granularity bit is set, the limit is in 4 KiB pages\&.
113         if ((entry\&.granularity & 0x80) != 0) {
114             limit = (limit << 12) | 0xFFF;
115         }
116 
117         basic::printf("GDT Entry %d: Base=%p, Limit=%#x, Access=%#x, Granularity=%#x\\n",
118                i, (void*)(uintptr_t)base, limit, entry\&.access, entry\&.granularity);
119     }
120     basic::printf("\-\-\-\\n");
121 }
.fi

.PP
References \fB__attribute__\fP, \fBessential::GDT_row::access\fP, \fBbase\fP, \fBessential::GDT_row::base_high\fP, \fBessential::GDT_row::base_low\fP, \fBessential::GDT_row::base_middle\fP, \fBessential::GDT_row::granularity\fP, \fBlimit\fP, \fBessential::GDT_row::limit_low\fP, and \fBbasic::printf()\fP\&.
.SS "void essential::GDT::printLoadedTableHeader ()\fC [static]\fP"

.PP
(Static) Prints the header information (base, limit, count) of the currently loaded \fBGDT\fP\&. 
.PP
Definition at line \fB124\fP of file \fBkgdt\&.cpp\fP\&..PP
.nf
124                                           {
125     struct GDT_Pointer {
126         uint16_t limit;
127         uint32_t base;
128     } __attribute__((packed));
129 
130     GDT_Pointer gdtr;
131     // Store the current GDT register contents into our struct\&.
132     asm volatile("sgdt %0" : "=m"(gdtr));
133 
134     basic::printf("\-\-\-\\n");
135     basic::printf("INFO about : Currently Loaded GDT\\n");
136     basic::printf("Base Address: %#x\\n", gdtr\&.base);
137     basic::printf("Limit: %#x (%d bytes)\\n", gdtr\&.limit, gdtr\&.limit);
138     basic::printf("Entries: %d\\n", (gdtr\&.limit + 1) / sizeof(essential::GDT_row));
139     basic::printf("\-\-\-\\n");
140 }
.fi

.PP
References \fB__attribute__\fP, \fBbase\fP, \fBlimit\fP, and \fBbasic::printf()\fP\&.
.PP
Referenced by \fBkernelMain()\fP\&.
.SS "uint16_t essential::GDT::user_CS_selector ()\fC [static]\fP"

.PP
(Static) Gets the user code segment selector\&. 
.PP
\fBReturns\fP
.RS 4
The 16-bit selector value\&. 
.RE
.PP

.PP
Definition at line \fB152\fP of file \fBkgdt\&.cpp\fP\&..PP
.nf
152 { return sizeof(essential::GDT_row) * 3; } // Selector 0x18
.fi

.SS "uint16_t essential::GDT::user_DS_selector ()\fC [static]\fP"

.PP
(Static) Gets the user data segment selector\&. 
.PP
\fBReturns\fP
.RS 4
The 16-bit selector value\&. 
.RE
.PP

.PP
Definition at line \fB155\fP of file \fBkgdt\&.cpp\fP\&..PP
.nf
155 { return sizeof(essential::GDT_row) * 4; }
.fi

.SH "Member Data Documentation"
.PP 
.SS "uintptr_t essential::GDT::base\fC [private]\fP"

.PP
Definition at line \fB56\fP of file \fBkgdt\&.hpp\fP\&.
.PP
Referenced by \fBGDT()\fP\&.
.SS "\fBGDT_row\fP essential::GDT::kernel_CS\fC [private]\fP"

.PP
Definition at line \fB58\fP of file \fBkgdt\&.hpp\fP\&.
.SS "\fBGDT_row\fP essential::GDT::kernel_DS\fC [private]\fP"

.PP
Definition at line \fB59\fP of file \fBkgdt\&.hpp\fP\&.
.SS "uint16_t essential::GDT::limit\fC [private]\fP"

.PP
Definition at line \fB55\fP of file \fBkgdt\&.hpp\fP\&.
.PP
Referenced by \fBGDT()\fP\&.
.SS "\fBGDT_row\fP essential::GDT::nullSegment\fC [private]\fP"

.PP
Definition at line \fB57\fP of file \fBkgdt\&.hpp\fP\&.
.PP
Referenced by \fBGDT()\fP\&.
.SS "\fBGDT_row\fP essential::GDT::user_CS\fC [private]\fP"

.PP
Definition at line \fB60\fP of file \fBkgdt\&.hpp\fP\&.
.SS "\fBGDT_row\fP essential::GDT::user_DS\fC [private]\fP"

.PP
Definition at line \fB61\fP of file \fBkgdt\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OSOS - Documentation from the source code\&.
