.TH "essential::atexit_func_entry_t" 3 "Thu Oct 23 2025 23:59:22" "OSOS - 32-bit Operating System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
essential::atexit_func_entry_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'kicxxabi\&.hpp'\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void(* \fBdestructor_func\fP )(void *)"
.br
.ti -1c
.RI "void * \fBdso_handle\fP"
.br
.ti -1c
.RI "void * \fBobj_ptr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBkicxxabi\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "void(* essential::atexit_func_entry_t::destructor_func) (void *)"

.PP
Definition at line \fB14\fP of file \fBkicxxabi\&.hpp\fP\&.
.PP
Referenced by \fB__cxa_atexit()\fP, and \fBessential::__cxa_finalize()\fP\&.
.SS "void* essential::atexit_func_entry_t::dso_handle"

.PP
Definition at line \fB16\fP of file \fBkicxxabi\&.hpp\fP\&.
.PP
Referenced by \fB__cxa_atexit()\fP\&.
.SS "void* essential::atexit_func_entry_t::obj_ptr"

.PP
Definition at line \fB15\fP of file \fBkicxxabi\&.hpp\fP\&.
.PP
Referenced by \fB__cxa_atexit()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OSOS - 32-bit Operating System from the source code\&.
