.TH "hardware_communication::Port8Bit" 3 "Fri Oct 24 2025 10:32:01" "OSOS - Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hardware_communication::Port8Bit \- Represents an 8-bit (byte-sized) I/O port\&. @inherits \fBPort\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'kport\&.hpp'\fP
.PP
Inherits \fBhardware_communication::Port\fP\&.
.PP
Inherited by \fBhardware_communication::Port8BitSlow\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPort8Bit\fP (uint16_t \fBportnumber\fP)"
.br
.RI "Constructs a new \fBPort8Bit\fP object\&. "
.ti -1c
.RI "virtual \fB~Port8Bit\fP () override"
.br
.RI "Destroys the \fBPort8Bit\fP object\&. "
.ti -1c
.RI "uint8_t \fBread\fP ()"
.br
.RI "Reads an 8-bit value from the I/O port\&. "
.ti -1c
.RI "virtual void \fBwrite\fP (uint8_t data)"
.br
.RI "Writes an 8-bit value to the I/O port\&. "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "uint16_t \fBportnumber\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents an 8-bit (byte-sized) I/O port\&. @inherits \fBPort\fP\&. 
.PP
Definition at line \fB20\fP of file \fBkport\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "hardware_communication::Port8Bit::Port8Bit (uint16_t portnumber)\fC [explicit]\fP"

.PP
Constructs a new \fBPort8Bit\fP object\&. 
.PP
\fBParameters\fP
.RS 4
\fIportnumber\fP The 16-bit address of the I/O port\&. 
.RE
.PP

.PP
Definition at line \fB15\fP of file \fBkport\&.cpp\fP\&..PP
.nf
15 :Port(portnumber){} 
.fi

.SS "hardware_communication::Port8Bit::~Port8Bit ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Destroys the \fBPort8Bit\fP object\&. 
.PP
Definition at line \fB17\fP of file \fBkport\&.cpp\fP\&..PP
.nf
17 {}
.fi

.SH "Member Function Documentation"
.PP 
.SS "uint8_t hardware_communication::Port8Bit::read ()"

.PP
Reads an 8-bit value from the I/O port\&. 
.PP
\fBReturns\fP
.RS 4
The 8-bit value read from the port\&. 
.RE
.PP

.PP
Definition at line \fB26\fP of file \fBkport\&.cpp\fP\&..PP
.nf
26                                             {
27     uint8_t result;
28     __asm__ volatile("inb %1, %0" :"=a"(result) : "Nd"(portnumber));
29     return result;
30 }
.fi

.PP
Referenced by \fBbasic::enable_cursor()\fP\&.
.SS "void hardware_communication::Port8Bit::write (uint8_t data)\fC [virtual]\fP"

.PP
Writes an 8-bit value to the I/O port\&. 
.PP
\fBParameters\fP
.RS 4
\fIdata\fP The 8-bit value to write\&. 
.RE
.PP

.PP
Reimplemented in \fBhardware_communication::Port8BitSlow\fP\&.
.PP
Definition at line \fB21\fP of file \fBkport\&.cpp\fP\&..PP
.nf
21                                                       {
22     __asm__ volatile("outb %0, %1" : : "a"(data), "Nd"(portnumber));
23 }
.fi

.PP
Referenced by \fBbasic::disable_cursor()\fP, \fBbasic::enable_cursor()\fP, and \fBbasic::update_cursor()\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "uint16_t hardware_communication::Port::portnumber\fC [protected]\fP, \fC [inherited]\fP"

.PP
Definition at line \fB11\fP of file \fBkport\&.hpp\fP\&.
.PP
Referenced by \fBhardware_communication::Port::Port()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OSOS - Documentation from the source code\&.
