.TH "hardware_communication" 3 "Fri Oct 24 2025 00:40:52" "OSOS - Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hardware_communication
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBIDT_row\fP"
.br
.ti -1c
.RI "class \fBInterruptHandler\fP"
.br
.ti -1c
.RI "class \fBInterruptManager\fP"
.br
.ti -1c
.RI "class \fBPort\fP"
.br
.ti -1c
.RI "class \fBPort16Bit\fP"
.br
.ti -1c
.RI "class \fBPort32Bit\fP"
.br
.ti -1c
.RI "class \fBPort8Bit\fP"
.br
.ti -1c
.RI "class \fBPort8BitSlow\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "class \fBhardware_communication::IDT_row\fP \fB__attribute__\fP ((packed))"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "class \fBhardware_communication::InterruptManager\fP \fB__attribute__\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "class \fBhardware_communication::IDT_row\fP hardware_communication::__attribute__ ((packed))"

.SH "Variable Documentation"
.PP 
.SS "class \fBhardware_communication::InterruptManager\fP hardware_communication::__attribute__"

.PP
Referenced by \fBhardware_communication::InterruptManager::installTable()\fP, \fBhardware_communication::InterruptManager::printLoadedTable()\fP, and \fBhardware_communication::InterruptManager::printLoadedTableHeader()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OSOS - Documentation from the source code\&.
