.TH "hardware_communication::Port16Bit" 3 "Fri Oct 24 2025 10:32:01" "OSOS - Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hardware_communication::Port16Bit \- Represents a 16-bit (word-sized) I/O port\&. @inherits \fBPort\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'kport\&.hpp'\fP
.PP
Inherits \fBhardware_communication::Port\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPort16Bit\fP (uint16_t \fBportnumber\fP)"
.br
.RI "Constructs a new \fBPort16Bit\fP object\&. "
.ti -1c
.RI "\fB~Port16Bit\fP () override"
.br
.RI "Destroys the \fBPort16Bit\fP object\&. "
.ti -1c
.RI "uint16_t \fBread\fP ()"
.br
.RI "Reads a 16-bit value from the I/O port\&. "
.ti -1c
.RI "void \fBwrite\fP (uint16_t data)"
.br
.RI "Writes a 16-bit value to the I/O port\&. "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "uint16_t \fBportnumber\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents a 16-bit (word-sized) I/O port\&. @inherits \fBPort\fP\&. 
.PP
Definition at line \fB40\fP of file \fBkport\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "hardware_communication::Port16Bit::Port16Bit (uint16_t portnumber)\fC [explicit]\fP"

.PP
Constructs a new \fBPort16Bit\fP object\&. 
.PP
\fBParameters\fP
.RS 4
\fIportnumber\fP The 16-bit address of the I/O port\&. 
.RE
.PP

.PP
Definition at line \fB50\fP of file \fBkport\&.cpp\fP\&..PP
.nf
50 :Port(portnumber){} 
.fi

.SS "hardware_communication::Port16Bit::~Port16Bit ()\fC [override]\fP"

.PP
Destroys the \fBPort16Bit\fP object\&. 
.PP
Definition at line \fB52\fP of file \fBkport\&.cpp\fP\&..PP
.nf
52 {}
.fi

.SH "Member Function Documentation"
.PP 
.SS "uint16_t hardware_communication::Port16Bit::read ()"

.PP
Reads a 16-bit value from the I/O port\&. 
.PP
\fBReturns\fP
.RS 4
The 16-bit value read from the port\&. 
.RE
.PP

.PP
Definition at line \fB61\fP of file \fBkport\&.cpp\fP\&..PP
.nf
61                                               {
62     uint16_t result;
63     __asm__ volatile("inw %1, %0" :"=a"(result) : "Nd"(portnumber));
64     return result;
65 }
.fi

.SS "void hardware_communication::Port16Bit::write (uint16_t data)"

.PP
Writes a 16-bit value to the I/O port\&. 
.PP
\fBParameters\fP
.RS 4
\fIdata\fP The 16-bit value to write\&. 
.RE
.PP

.PP
Definition at line \fB56\fP of file \fBkport\&.cpp\fP\&..PP
.nf
56                                                         {
57     __asm__ volatile("outw %0, %1" : : "a"(data), "Nd"(portnumber));
58 }
.fi

.SH "Member Data Documentation"
.PP 
.SS "uint16_t hardware_communication::Port::portnumber\fC [protected]\fP, \fC [inherited]\fP"

.PP
Definition at line \fB11\fP of file \fBkport\&.hpp\fP\&.
.PP
Referenced by \fBhardware_communication::Port::Port()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OSOS - Documentation from the source code\&.
