.TH "hardware_communication::Port32Bit" 3 "Fri Oct 24 2025 10:32:01" "OSOS - Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hardware_communication::Port32Bit \- Represents a 32-bit (double-word-sized) I/O port\&. @inherits \fBPort\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'kport\&.hpp'\fP
.PP
Inherits \fBhardware_communication::Port\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPort32Bit\fP (uint16_t \fBportnumber\fP)"
.br
.RI "Constructs a new \fBPort32Bit\fP object\&. "
.ti -1c
.RI "\fB~Port32Bit\fP () override"
.br
.RI "Destroys the \fBPort32Bit\fP object\&. "
.ti -1c
.RI "uint32_t \fBread\fP ()"
.br
.RI "Reads a 32-bit value from the I/O port\&. "
.ti -1c
.RI "void \fBwrite\fP (uint32_t data)"
.br
.RI "Writes a 32-bit value to the I/O port\&. "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "uint16_t \fBportnumber\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents a 32-bit (double-word-sized) I/O port\&. @inherits \fBPort\fP\&. 
.PP
Definition at line \fB51\fP of file \fBkport\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "hardware_communication::Port32Bit::Port32Bit (uint16_t portnumber)\fC [explicit]\fP"

.PP
Constructs a new \fBPort32Bit\fP object\&. 
.PP
\fBParameters\fP
.RS 4
\fIportnumber\fP The 16-bit address of the I/O port\&. 
.RE
.PP

.PP
Definition at line \fB71\fP of file \fBkport\&.cpp\fP\&..PP
.nf
71 :Port(portnumber){} 
.fi

.SS "hardware_communication::Port32Bit::~Port32Bit ()\fC [override]\fP"

.PP
Destroys the \fBPort32Bit\fP object\&. 
.PP
Definition at line \fB73\fP of file \fBkport\&.cpp\fP\&..PP
.nf
73 {}
.fi

.SH "Member Function Documentation"
.PP 
.SS "uint32_t hardware_communication::Port32Bit::read ()"

.PP
Reads a 32-bit value from the I/O port\&. 
.PP
\fBReturns\fP
.RS 4
The 32-bit value read from the port\&. 
.RE
.PP

.PP
Definition at line \fB82\fP of file \fBkport\&.cpp\fP\&..PP
.nf
82                                               {
83     uint32_t result;
84     __asm__ volatile("inl %1, %0" :"=a"(result) : "Nd"(portnumber));
85     return result;
86 }
.fi

.SS "void hardware_communication::Port32Bit::write (uint32_t data)"

.PP
Writes a 32-bit value to the I/O port\&. 
.PP
\fBParameters\fP
.RS 4
\fIdata\fP The 32-bit value to write\&. 
.RE
.PP

.PP
Definition at line \fB77\fP of file \fBkport\&.cpp\fP\&..PP
.nf
77                                                         {
78     __asm__ volatile("outl %0, %1" : : "a"(data), "Nd"(portnumber));
79 }
.fi

.SH "Member Data Documentation"
.PP 
.SS "uint16_t hardware_communication::Port::portnumber\fC [protected]\fP, \fC [inherited]\fP"

.PP
Definition at line \fB11\fP of file \fBkport\&.hpp\fP\&.
.PP
Referenced by \fBhardware_communication::Port::Port()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OSOS - Documentation from the source code\&.
