.TH "hardware_communication::Port" 3 "Fri Oct 24 2025 10:32:01" "OSOS - Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hardware_communication::Port \- Base class for hardware I/O port communication\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'kport\&.hpp'\fP
.PP
Inherited by \fBhardware_communication::Port16Bit\fP, \fBhardware_communication::Port32Bit\fP, and \fBhardware_communication::Port8Bit\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~Port\fP ()"
.br
.RI "Destroys the \fBPort\fP object\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBPort\fP (uint16_t \fBportnumber\fP)"
.br
.RI "Constructs a new \fBPort\fP object\&. "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "uint16_t \fBportnumber\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Base class for hardware I/O port communication\&. 
.PP
Definition at line \fB9\fP of file \fBkport\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "hardware_communication::Port::Port (uint16_t portnumber)\fC [explicit]\fP, \fC [protected]\fP"

.PP
Constructs a new \fBPort\fP object\&. 
.PP
\fBParameters\fP
.RS 4
\fIportnumber\fP The 16-bit address of the I/O port\&. 
.RE
.PP

.PP
Definition at line \fB5\fP of file \fBkport\&.cpp\fP\&..PP
.nf
5                                                    {
6     this\->portnumber = portnumber;
7 }
.fi

.PP
References \fBportnumber\fP\&.
.SS "hardware_communication::Port::~Port ()\fC [virtual]\fP"

.PP
Destroys the \fBPort\fP object\&. 
.PP
Definition at line \fB9\fP of file \fBkport\&.cpp\fP\&..PP
.nf
9 {}
.fi

.SH "Member Data Documentation"
.PP 
.SS "uint16_t hardware_communication::Port::portnumber\fC [protected]\fP"

.PP
Definition at line \fB11\fP of file \fBkport\&.hpp\fP\&.
.PP
Referenced by \fBPort()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OSOS - Documentation from the source code\&.
