.TH "hardware_communication::Port8Bit" 3 "Fri Oct 24 2025 00:08:28" "OSOS - 32-bit Operating System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hardware_communication::Port8Bit
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'kport\&.hpp'\fP
.PP
Inherits \fBhardware_communication::Port\fP\&.
.PP
Inherited by \fBhardware_communication::Port8BitSlow\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPort8Bit\fP (uint16_t \fBportnumber\fP)"
.br
.ti -1c
.RI "virtual \fB~Port8Bit\fP () override"
.br
.ti -1c
.RI "uint8_t \fBread\fP ()"
.br
.ti -1c
.RI "virtual void \fBwrite\fP (uint8_t data)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "uint16_t \fBportnumber\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB30\fP of file \fBkport\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "hardware_communication::Port8Bit::Port8Bit (uint16_t portnumber)\fC [explicit]\fP"

.PP
Definition at line \fB10\fP of file \fBkport\&.cpp\fP\&..PP
.nf
10 :Port(portnumber){} 
.fi

.SS "hardware_communication::Port8Bit::~Port8Bit ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Definition at line \fB11\fP of file \fBkport\&.cpp\fP\&..PP
.nf
11 {}
.fi

.SH "Member Function Documentation"
.PP 
.SS "uint8_t hardware_communication::Port8Bit::read ()"

.PP
Definition at line \fB16\fP of file \fBkport\&.cpp\fP\&..PP
.nf
16                                             {
17     uint8_t result;
18     __asm__ volatile("inb %1, %0" :"=a"(result) : "Nd"(portnumber));
19     return result;
20 }
.fi

.PP
Referenced by \fBbasic::enable_cursor()\fP\&.
.SS "void hardware_communication::Port8Bit::write (uint8_t data)\fC [virtual]\fP"

.PP
Reimplemented in \fBhardware_communication::Port8BitSlow\fP\&.
.PP
Definition at line \fB13\fP of file \fBkport\&.cpp\fP\&..PP
.nf
13                                                       {
14     __asm__ volatile("outb %0, %1" : : "a"(data), "Nd"(portnumber));
15 }
.fi

.PP
Referenced by \fBbasic::disable_cursor()\fP, \fBbasic::enable_cursor()\fP, and \fBbasic::update_cursor()\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "uint16_t hardware_communication::Port::portnumber\fC [protected]\fP, \fC [inherited]\fP"

.PP
Definition at line \fB13\fP of file \fBkport\&.hpp\fP\&.
.PP
Referenced by \fBhardware_communication::Port::Port()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OSOS - 32-bit Operating System from the source code\&.
