.TH "/home/shreekar/Desktop/Building_own_OS/OSOS/libk_src/driver/kdriver.cpp" 3 "Fri Oct 24 2025 00:40:52" "OSOS - Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/shreekar/Desktop/Building_own_OS/OSOS/libk_src/driver/kdriver.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'driver/kdriver\&.hpp'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for OSOS - Documentation from the source code\&.
