.TH "libk_src/driver/kdriver.cpp" 3 "Thu Oct 23 2025 23:59:22" "OSOS - 32-bit Operating System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libk_src/driver/kdriver.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'driver/kdriver\&.hpp'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for OSOS - 32-bit Operating System from the source code\&.
