.TH "/home/shreekar/Desktop/Building_own_OS/OSOS/libk_header/driver/kdriver.hpp" 3 "Fri Oct 24 2025 10:32:01" "OSOS - Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/shreekar/Desktop/Building_own_OS/OSOS/libk_header/driver/kdriver.hpp
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBdriver::Driver\fP"
.br
.RI "Base class (interface) for all hardware drivers in the operating system\&. "
.ti -1c
.RI "class \fBdriver::DriverManager\fP"
.br
.RI "Manages a collection of \fBDriver\fP objects, facilitating their activation and organization\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBdriver\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAX_NUMDRIVERS\fP   265"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MAX_NUMDRIVERS   265"

.PP
Definition at line \fB3\fP of file \fBkdriver\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OSOS - Documentation from the source code\&.
