.TH "KeyboardEventHandler_for_kernel" 3 "Fri Oct 24 2025 00:21:12" "OSOS - Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KeyboardEventHandler_for_kernel
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdriver::KeyboardEventHandler\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBKeyboardEventHandler_for_kernel\fP ()"
.br
.ti -1c
.RI "\fB~KeyboardEventHandler_for_kernel\fP ()"
.br
.ti -1c
.RI "void \fBonKeyDown\fP (char ascii) override"
.br
.ti -1c
.RI "void \fBonKeyUp\fP (char ascii) override"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB13\fP of file \fBkernel\&.cpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "KeyboardEventHandler_for_kernel::KeyboardEventHandler_for_kernel ()\fC [inline]\fP"

.PP
Definition at line \fB15\fP of file \fBkernel\&.cpp\fP\&..PP
.nf
15 {}
.fi

.SS "KeyboardEventHandler_for_kernel::~KeyboardEventHandler_for_kernel ()\fC [inline]\fP"

.PP
Definition at line \fB16\fP of file \fBkernel\&.cpp\fP\&..PP
.nf
16 {}
.fi

.SH "Member Function Documentation"
.PP 
.SS "void KeyboardEventHandler_for_kernel::onKeyDown (char ascii)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBdriver::KeyboardEventHandler\fP\&.
.PP
Definition at line \fB17\fP of file \fBkernel\&.cpp\fP\&..PP
.nf
17                                             {
18             if (ascii != 0) {
19                 basic::printf("%c", ascii);
20             }
21         }
.fi

.PP
References \fBbasic::printf()\fP\&.
.SS "void KeyboardEventHandler_for_kernel::onKeyUp (char ascii)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBdriver::KeyboardEventHandler\fP\&.
.PP
Definition at line \fB22\fP of file \fBkernel\&.cpp\fP\&..PP
.nf
22                                           {
23             (void) ascii;
24         }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for OSOS - Documentation from the source code\&.
