.TH "/home/shreekar/Desktop/Building_own_OS/OSOS/libk_header/essential/kgdt.hpp" 3 "Fri Oct 24 2025 10:32:01" "OSOS - Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/shreekar/Desktop/Building_own_OS/OSOS/libk_header/essential/kgdt.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <cstdint>\fP
.br
\fC#include 'basic/kiostream\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBessential::GDT\fP"
.br
.RI "Manages the Global Descriptor Table (\fBGDT\fP), holding segment descriptors for the CPU\&. "
.ti -1c
.RI "class \fBessential::GDT_row\fP"
.br
.RI "Represents a single 8-byte segment descriptor entry in the Global Descriptor Table (\fBGDT\fP)\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBessential\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBGDT_ACCESS_CODE_PL0\fP   \fBSEG_ACCESS_PRES\fP(1) | \fBSEG_ACCESS_PRIV\fP(0) | \fBSEG_ACCESS_DESCTYPE\fP(1) | \fBSEG_ACCESS_TYPE\fP(\fBSEG_CODE_EXRD\fP)"
.br
.ti -1c
.RI "#define \fBGDT_ACCESS_CODE_PL3\fP   \fBSEG_ACCESS_PRES\fP(1) | \fBSEG_ACCESS_PRIV\fP(3) | \fBSEG_ACCESS_DESCTYPE\fP(1) | \fBSEG_ACCESS_TYPE\fP(\fBSEG_CODE_EXRD\fP)"
.br
.ti -1c
.RI "#define \fBGDT_ACCESS_DATA_PL0\fP   \fBSEG_ACCESS_PRES\fP(1) | \fBSEG_ACCESS_PRIV\fP(0) | \fBSEG_ACCESS_DESCTYPE\fP(1) | \fBSEG_ACCESS_TYPE\fP(\fBSEG_DATA_RDWR\fP)"
.br
.ti -1c
.RI "#define \fBGDT_ACCESS_DATA_PL3\fP   \fBSEG_ACCESS_PRES\fP(1) | \fBSEG_ACCESS_PRIV\fP(3) | \fBSEG_ACCESS_DESCTYPE\fP(1) | \fBSEG_ACCESS_TYPE\fP(\fBSEG_DATA_RDWR\fP)"
.br
.ti -1c
.RI "#define \fBGDT_GRAN_FLAGS\fP   \fBSEG_GRAN_GRAN\fP(1) | \fBSEG_GRAN_SIZE\fP(1) | \fBSEG_GRAN_LONG\fP(0) | \fBSEG_GRAN_SAVL\fP(0)"
.br
.ti -1c
.RI "#define \fBSEG_ACCESS_DESCTYPE\fP(x)   ((x) << 4)"
.br
.ti -1c
.RI "#define \fBSEG_ACCESS_PRES\fP(x)   ((x) << 7)"
.br
.ti -1c
.RI "#define \fBSEG_ACCESS_PRIV\fP(x)   (((x) & 0x03) << 5)"
.br
.ti -1c
.RI "#define \fBSEG_ACCESS_TYPE\fP(x)   ((x) << 0)"
.br
.ti -1c
.RI "#define \fBSEG_CODE_EXRD\fP   0x0A"
.br
.ti -1c
.RI "#define \fBSEG_DATA_RDWR\fP   0x02"
.br
.ti -1c
.RI "#define \fBSEG_GRAN_GRAN\fP(x)   ((x) << 7)"
.br
.ti -1c
.RI "#define \fBSEG_GRAN_LONG\fP(x)   ((x) << 5)"
.br
.ti -1c
.RI "#define \fBSEG_GRAN_SAVL\fP(x)   ((x) << 4)"
.br
.ti -1c
.RI "#define \fBSEG_GRAN_SIZE\fP(x)   ((x) << 6)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fB~GDT\fP ()"
.br
.ti -1c
.RI "\fB~GDT_row\fP ()"
.br
.ti -1c
.RI "class \fBessential::GDT_row\fP \fBessential::__attribute__\fP ((packed))"
.br
.ti -1c
.RI "\fBGDT_row\fP ()"
.br
.ti -1c
.RI "\fBGDT_row\fP (uint32_t \fBbase\fP, uint32_t \fBlimit\fP, uint8_t access_byte, uint8_t gran_byte)"
.br
.ti -1c
.RI "void \fBinstallTable\fP ()"
.br
.ti -1c
.RI "static uint16_t \fBkernel_CS_selector\fP ()"
.br
.ti -1c
.RI "static uint16_t \fBkernel_DS_selector\fP ()"
.br
.ti -1c
.RI "static void \fBprintLoadedTable\fP ()"
.br
.ti -1c
.RI "static void \fBprintLoadedTableHeader\fP ()"
.br
.ti -1c
.RI "static uint16_t \fBuser_CS_selector\fP ()"
.br
.ti -1c
.RI "static uint16_t \fBuser_DS_selector\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "uint8_t \fBaccess\fP"
.br
.ti -1c
.RI "uintptr_t \fBbase\fP"
.br
.ti -1c
.RI "uint8_t \fBbase_high\fP"
.br
.ti -1c
.RI "uint16_t \fBbase_low\fP"
.br
.ti -1c
.RI "uint8_t \fBbase_middle\fP"
.br
.ti -1c
.RI "uint8_t \fBgranularity\fP"
.br
.ti -1c
.RI "\fBGDT_row\fP \fBkernel_CS\fP"
.br
.ti -1c
.RI "\fBGDT_row\fP \fBkernel_DS\fP"
.br
.ti -1c
.RI "uint16_t \fBlimit\fP"
.br
.ti -1c
.RI "uint16_t \fBlimit_low\fP"
.br
.ti -1c
.RI "\fBGDT_row\fP \fBnullSegment\fP"
.br
.ti -1c
.RI "\fBGDT_row\fP \fBuser_CS\fP"
.br
.ti -1c
.RI "\fBGDT_row\fP \fBuser_DS\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define GDT_ACCESS_CODE_PL0   \fBSEG_ACCESS_PRES\fP(1) | \fBSEG_ACCESS_PRIV\fP(0) | \fBSEG_ACCESS_DESCTYPE\fP(1) | \fBSEG_ACCESS_TYPE\fP(\fBSEG_CODE_EXRD\fP)"

.PP
Definition at line \fB24\fP of file \fBkgdt\&.hpp\fP\&.
.SS "#define GDT_ACCESS_CODE_PL3   \fBSEG_ACCESS_PRES\fP(1) | \fBSEG_ACCESS_PRIV\fP(3) | \fBSEG_ACCESS_DESCTYPE\fP(1) | \fBSEG_ACCESS_TYPE\fP(\fBSEG_CODE_EXRD\fP)"

.PP
Definition at line \fB26\fP of file \fBkgdt\&.hpp\fP\&.
.SS "#define GDT_ACCESS_DATA_PL0   \fBSEG_ACCESS_PRES\fP(1) | \fBSEG_ACCESS_PRIV\fP(0) | \fBSEG_ACCESS_DESCTYPE\fP(1) | \fBSEG_ACCESS_TYPE\fP(\fBSEG_DATA_RDWR\fP)"

.PP
Definition at line \fB25\fP of file \fBkgdt\&.hpp\fP\&.
.SS "#define GDT_ACCESS_DATA_PL3   \fBSEG_ACCESS_PRES\fP(1) | \fBSEG_ACCESS_PRIV\fP(3) | \fBSEG_ACCESS_DESCTYPE\fP(1) | \fBSEG_ACCESS_TYPE\fP(\fBSEG_DATA_RDWR\fP)"

.PP
Definition at line \fB27\fP of file \fBkgdt\&.hpp\fP\&.
.SS "#define GDT_GRAN_FLAGS   \fBSEG_GRAN_GRAN\fP(1) | \fBSEG_GRAN_SIZE\fP(1) | \fBSEG_GRAN_LONG\fP(0) | \fBSEG_GRAN_SAVL\fP(0)"

.PP
Definition at line \fB31\fP of file \fBkgdt\&.hpp\fP\&.
.SS "#define SEG_ACCESS_DESCTYPE(x)   ((x) << 4)"

.PP
Definition at line \fB9\fP of file \fBkgdt\&.hpp\fP\&.
.SS "#define SEG_ACCESS_PRES(x)   ((x) << 7)"

.PP
Definition at line \fB11\fP of file \fBkgdt\&.hpp\fP\&.
.SS "#define SEG_ACCESS_PRIV(x)   (((x) & 0x03) << 5)"

.PP
Definition at line \fB10\fP of file \fBkgdt\&.hpp\fP\&.
.SS "#define SEG_ACCESS_TYPE(x)   ((x) << 0)"

.PP
Definition at line \fB8\fP of file \fBkgdt\&.hpp\fP\&.
.SS "#define SEG_CODE_EXRD   0x0A"

.PP
Definition at line \fB21\fP of file \fBkgdt\&.hpp\fP\&.
.SS "#define SEG_DATA_RDWR   0x02"

.PP
Definition at line \fB20\fP of file \fBkgdt\&.hpp\fP\&.
.SS "#define SEG_GRAN_GRAN(x)   ((x) << 7)"

.PP
Definition at line \fB17\fP of file \fBkgdt\&.hpp\fP\&.
.SS "#define SEG_GRAN_LONG(x)   ((x) << 5)"

.PP
Definition at line \fB15\fP of file \fBkgdt\&.hpp\fP\&.
.SS "#define SEG_GRAN_SAVL(x)   ((x) << 4)"

.PP
Definition at line \fB14\fP of file \fBkgdt\&.hpp\fP\&.
.SS "#define SEG_GRAN_SIZE(x)   ((x) << 6)"

.PP
Definition at line \fB16\fP of file \fBkgdt\&.hpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "__attribute__::~GDT ()"

.SS "__attribute__::~GDT_row ()"

.SS "__attribute__::GDT_row ()"

.SS "__attribute__::GDT_row (uint32_t base, uint32_t limit, uint8_t access_byte, uint8_t gran_byte)"

.SS "void __attribute__::installTable ()"

.SS "static uint16_t __attribute__::kernel_CS_selector ()\fC [static]\fP"

.SS "static uint16_t __attribute__::kernel_DS_selector ()\fC [static]\fP"

.SS "static void __attribute__::printLoadedTable ()\fC [static]\fP"

.SS "static void __attribute__::printLoadedTableHeader ()\fC [static]\fP"

.SS "static uint16_t __attribute__::user_CS_selector ()\fC [static]\fP"

.SS "static uint16_t __attribute__::user_DS_selector ()\fC [static]\fP"

.SH "Variable Documentation"
.PP 
.SS "uint8_t access\fC [private]\fP"

.PP
Definition at line \fB4\fP of file \fBkgdt\&.hpp\fP\&.
.PP
Referenced by \fBessential::GDT_row::GDT_row()\fP, and \fBhardware_communication::InterruptManager::printLoadedTable()\fP\&.
.SS "uintptr_t base\fC [private]\fP"

.PP
Definition at line \fB2\fP of file \fBkgdt\&.hpp\fP\&.
.PP
Referenced by \fBhardware_communication::InterruptManager::InterruptManager()\fP, \fBessential::GDT::installTable()\fP, \fBhardware_communication::InterruptManager::installTable()\fP, \fBpower()\fP, \fBbasic::printf()\fP, \fBessential::GDT::printLoadedTable()\fP, \fBhardware_communication::InterruptManager::printLoadedTable()\fP, \fBessential::GDT::printLoadedTableHeader()\fP, \fBhardware_communication::InterruptManager::printLoadedTableHeader()\fP, and \fBullToString()\fP\&.
.SS "uint8_t base_high\fC [private]\fP"

.PP
Definition at line \fB6\fP of file \fBkgdt\&.hpp\fP\&.
.PP
Referenced by \fBessential::GDT_row::GDT_row()\fP\&.
.SS "uint16_t base_low\fC [private]\fP"

.PP
Definition at line \fB2\fP of file \fBkgdt\&.hpp\fP\&.
.PP
Referenced by \fBessential::GDT_row::GDT_row()\fP\&.
.SS "uint8_t base_middle\fC [private]\fP"

.PP
Definition at line \fB3\fP of file \fBkgdt\&.hpp\fP\&.
.PP
Referenced by \fBessential::GDT_row::GDT_row()\fP\&.
.SS "uint8_t granularity\fC [private]\fP"

.PP
Definition at line \fB5\fP of file \fBkgdt\&.hpp\fP\&.
.PP
Referenced by \fBessential::GDT_row::GDT_row()\fP\&.
.SS "\fBGDT_row\fP kernel_CS\fC [private]\fP"

.PP
Definition at line \fB4\fP of file \fBkgdt\&.hpp\fP\&.
.SS "\fBGDT_row\fP kernel_DS\fC [private]\fP"

.PP
Definition at line \fB5\fP of file \fBkgdt\&.hpp\fP\&.
.SS "uint16_t limit\fC [private]\fP"

.PP
Definition at line \fB1\fP of file \fBkgdt\&.hpp\fP\&.
.PP
Referenced by \fBhardware_communication::InterruptManager::InterruptManager()\fP, \fBessential::GDT::installTable()\fP, \fBhardware_communication::InterruptManager::installTable()\fP, \fBessential::GDT::printLoadedTable()\fP, \fBhardware_communication::InterruptManager::printLoadedTable()\fP, \fBessential::GDT::printLoadedTableHeader()\fP, and \fBhardware_communication::InterruptManager::printLoadedTableHeader()\fP\&.
.SS "uint16_t limit_low\fC [private]\fP"

.PP
Definition at line \fB1\fP of file \fBkgdt\&.hpp\fP\&.
.PP
Referenced by \fBessential::GDT_row::GDT_row()\fP\&.
.SS "\fBGDT_row\fP nullSegment\fC [private]\fP"

.PP
Definition at line \fB3\fP of file \fBkgdt\&.hpp\fP\&.
.SS "\fBGDT_row\fP user_CS\fC [private]\fP"

.PP
Definition at line \fB6\fP of file \fBkgdt\&.hpp\fP\&.
.SS "\fBGDT_row\fP user_DS\fC [private]\fP"

.PP
Definition at line \fB7\fP of file \fBkgdt\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OSOS - Documentation from the source code\&.
