.TH "libk_src/essential/kgdt.cpp" 3 "Fri Oct 24 2025 00:21:12" "OSOS - Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libk_src/essential/kgdt.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'essential/kgdt\&.hpp'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for OSOS - Documentation from the source code\&.
