.TH "/home/shreekar/Desktop/Building_own_OS/OSOS/libk_header/essential/kicxxabi.hpp" 3 "Fri Oct 24 2025 10:32:01" "OSOS - Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/shreekar/Desktop/Building_own_OS/OSOS/libk_header/essential/kicxxabi.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'basic/kiostream\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBessential::atexit_func_entry_t\fP"
.br
.RI "Structure to hold a registered C++ ABI exit function (destructor)\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBessential\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBATEXIT_MAX_FUNCS\fP   128"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef unsigned \fBuarch_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBessential::__callConstructors\fP ()"
.br
.RI "Iterates over the list of global constructors and calls them to initialize global C++ objects\&. "
.ti -1c
.RI "void \fBessential::__cxa_finalize\fP (void *f)"
.br
.RI "Executes registered destructors/cleanup functions\&. "
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ATEXIT_MAX_FUNCS   128"

.PP
Definition at line \fB4\fP of file \fBkicxxabi\&.hpp\fP\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef unsigned \fBuarch_t\fP"

.PP
Definition at line \fB5\fP of file \fBkicxxabi\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OSOS - Documentation from the source code\&.
