.TH "/home/shreekar/Desktop/Building_own_OS/OSOS/libk_header/hardware_communication/kinterrupt.hpp" 3 "Fri Oct 24 2025 10:32:01" "OSOS - Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/shreekar/Desktop/Building_own_OS/OSOS/libk_header/hardware_communication/kinterrupt.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <cstdint>\fP
.br
\fC#include 'basic/kiostream\&.hpp'\fP
.br
\fC#include 'hardware_communication/kport\&.hpp'\fP
.br
\fC#include 'essential/kgdt\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBhardware_communication::IDT_row\fP"
.br
.RI "Represents a single 8-byte entry (gate descriptor) in the Interrupt Descriptor Table (IDT)\&. "
.ti -1c
.RI "class \fBhardware_communication::InterruptHandler\fP"
.br
.RI "Base class (interface) for handling specific CPU interrupts\&. "
.ti -1c
.RI "class \fBhardware_communication::InterruptManager\fP"
.br
.RI "Manages the Interrupt Descriptor Table (IDT) and Programmable Interrupt Controllers (PICs), dispatching interrupts to registered handlers\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBhardware_communication\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fB~IDT_row\fP ()"
.br
.ti -1c
.RI "class \fBhardware_communication::IDT_row\fP \fBhardware_communication::__attribute__\fP ((packed))"
.br
.ti -1c
.RI "void \fBhandleIRQ0x00\fP ()"
.br
.ti -1c
.RI "void \fBhandleIRQ0x01\fP ()"
.br
.ti -1c
.RI "void \fBhandleIRQ0x0C\fP ()"
.br
.ti -1c
.RI "\fBIDT_row\fP ()"
.br
.ti -1c
.RI "void \fBignoreInterrupt\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "class \fBhardware_communication::InterruptManager\fP \fBhardware_communication::__attribute__\fP"
.br
.ti -1c
.RI "uint8_t \fBaccess\fP"
.br
.ti -1c
.RI "uint16_t \fBhandlerAddressHighbits\fP"
.br
.ti -1c
.RI "uint16_t \fBhandlerAddressLowbits\fP"
.br
.ti -1c
.RI "uint16_t \fBkernelCodeSegmentSelector\fP"
.br
.ti -1c
.RI "uint8_t \fBreserved\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "__attribute__::~IDT_row ()"

.SS "void handleIRQ0x00 ()"

.PP
Referenced by \fBhardware_communication::InterruptManager::InterruptManager()\fP\&.
.SS "void handleIRQ0x01 ()"

.PP
Referenced by \fBhardware_communication::InterruptManager::InterruptManager()\fP\&.
.SS "void handleIRQ0x0C ()"

.PP
Referenced by \fBhardware_communication::InterruptManager::InterruptManager()\fP\&.
.SS "__attribute__::IDT_row ()"

.SS "void ignoreInterrupt ()"

.PP
Referenced by \fBhardware_communication::InterruptManager::InterruptManager()\fP\&.
.SH "Variable Documentation"
.PP 
.SS "uint8_t access\fC [private]\fP"

.PP
Definition at line \fB4\fP of file \fBkinterrupt\&.hpp\fP\&.
.SS "uint16_t handlerAddressHighbits\fC [private]\fP"

.PP
Definition at line \fB5\fP of file \fBkinterrupt\&.hpp\fP\&.
.SS "uint16_t handlerAddressLowbits\fC [private]\fP"

.PP
Definition at line \fB1\fP of file \fBkinterrupt\&.hpp\fP\&.
.PP
Referenced by \fBhardware_communication::InterruptManager::printLoadedTable()\fP\&.
.SS "uint16_t kernelCodeSegmentSelector\fC [private]\fP"

.PP
Definition at line \fB2\fP of file \fBkinterrupt\&.hpp\fP\&.
.PP
Referenced by \fBhardware_communication::InterruptManager::printLoadedTable()\fP\&.
.SS "uint8_t reserved\fC [private]\fP"

.PP
Definition at line \fB3\fP of file \fBkinterrupt\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OSOS - Documentation from the source code\&.
