.TH "libk_header/basic/kiostream.hpp" 3 "Fri Oct 24 2025 00:08:28" "OSOS - 32-bit Operating System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libk_header/basic/kiostream.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <cstdint>\fP
.br
\fC#include <cstdarg>\fP
.br
\fC#include 'hardware_communication/kport\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBbasic\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBbasic::__clearScreen\fP ()"
.br
.ti -1c
.RI "void \fBbasic::disable_cursor\fP ()"
.br
.ti -1c
.RI "void \fBbasic::enable_cursor\fP (uint8_t cursor_start, uint8_t cursor_end)"
.br
.ti -1c
.RI "int \fBbasic::printf\fP (const char *format,\&.\&.\&.)"
.br
.RI "A custom implementation of the standard printf function for writing to VGA text mode memory\&. "
.ti -1c
.RI "void \fBbasic::update_cursor\fP (int x, int y)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for OSOS - 32-bit Operating System from the source code\&.
