.TH "/home/shreekar/Desktop/Building_own_OS/OSOS/libk_header/driver/kkeyboard.hpp" 3 "Fri Oct 24 2025 10:32:01" "OSOS - Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/shreekar/Desktop/Building_own_OS/OSOS/libk_header/driver/kkeyboard.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <cstdint>\fP
.br
\fC#include 'hardware_communication/kinterrupt\&.hpp'\fP
.br
\fC#include 'hardware_communication/kport\&.hpp'\fP
.br
\fC#include 'driver/kdriver\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBdriver::KeyboardDriver\fP"
.br
.RI "\fBDriver\fP for the PS/2 keyboard, handling scancodes and managing keyboard state (Shift, Caps Lock)\&. @inherits \fBhardware_communication::InterruptHandler\fP @inherits \fBdriver::Driver\fP\&. "
.ti -1c
.RI "class \fBdriver::KeyboardEventHandler\fP"
.br
.RI "Base class (interface) for handling keyboard events (key presses and releases)\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBdriver\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for OSOS - Documentation from the source code\&.
