.TH "libk_src/driver/kkeyboard.cpp" 3 "Fri Oct 24 2025 00:21:12" "OSOS - Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libk_src/driver/kkeyboard.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'driver/kkeyboard\&.hpp'\fP
.br
\fC#include 'driver/kmouse\&.hpp'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for OSOS - Documentation from the source code\&.
