.TH "libk_header/basic/kmemory.hpp" 3 "Thu Oct 23 2025 23:59:22" "OSOS - 32-bit Operating System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libk_header/basic/kmemory.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'basic/kiostream\&.hpp'\fP
.br
\fC#include 'basic/multiboot\&.hpp'\fP
.br
\fC#include <cstddef>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBbasic\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBbasic::__printMemoryMap\fP (multiboot_info_t *mbi)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for OSOS - 32-bit Operating System from the source code\&.
