.TH "/home/shreekar/Desktop/Building_own_OS/OSOS/libk_header/basic/kmemory.hpp" 3 "Fri Oct 24 2025 10:32:01" "OSOS - Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/shreekar/Desktop/Building_own_OS/OSOS/libk_header/basic/kmemory.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'basic/kiostream\&.hpp'\fP
.br
\fC#include 'basic/multiboot\&.h'\fP
.br
\fC#include <cstddef>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBbasic\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBbasic::__printMemoryMap\fP (multiboot_info_t *mbi)"
.br
.RI "Prints the system memory map provided by the Multiboot bootloader\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for OSOS - Documentation from the source code\&.
