.TH "/home/shreekar/Desktop/Building_own_OS/OSOS/libk_src/driver/kmouse.cpp" 3 "Fri Oct 24 2025 10:32:01" "OSOS - Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/shreekar/Desktop/Building_own_OS/OSOS/libk_src/driver/kmouse.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'driver/kmouse\&.hpp'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for OSOS - Documentation from the source code\&.
