.TH "libk_src/driver/kmouse.cpp" 3 "Fri Oct 24 2025 00:08:28" "OSOS - 32-bit Operating System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libk_src/driver/kmouse.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'driver/kmouse\&.hpp'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for OSOS - 32-bit Operating System from the source code\&.
