.TH "/home/shreekar/Desktop/Building_own_OS/OSOS/libk_header/driver/kmouse.hpp" 3 "Fri Oct 24 2025 10:32:01" "OSOS - Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/shreekar/Desktop/Building_own_OS/OSOS/libk_header/driver/kmouse.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <cstdint>\fP
.br
\fC#include 'hardware_communication/kinterrupt\&.hpp'\fP
.br
\fC#include 'hardware_communication/kport\&.hpp'\fP
.br
\fC#include 'basic/kiostream\&.hpp'\fP
.br
\fC#include 'driver/kdriver\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBdriver::MouseDriver\fP"
.br
.RI "\fBDriver\fP for the PS/2 mouse, handling 3-byte packets and managing mouse state\&. @inherits \fBhardware_communication::InterruptHandler\fP @inherits \fBdriver::Driver\fP\&. "
.ti -1c
.RI "class \fBdriver::MouseEventHandler\fP"
.br
.RI "Base class (interface) for handling mouse events (movement and button clicks)\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBdriver\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBKMOUSE_COLOR_BLACK\fP   0x0"
.br
.ti -1c
.RI "#define \fBKMOUSE_COLOR_BLUE\fP   0x1"
.br
.ti -1c
.RI "#define \fBKMOUSE_COLOR_BROWN\fP   0x6"
.br
.ti -1c
.RI "#define \fBKMOUSE_COLOR_CYAN\fP   0x3"
.br
.ti -1c
.RI "#define \fBKMOUSE_COLOR_DARK_GREY\fP   0x8"
.br
.ti -1c
.RI "#define \fBKMOUSE_COLOR_GREEN\fP   0x2"
.br
.ti -1c
.RI "#define \fBKMOUSE_COLOR_LIGHT_BLUE\fP   0x9"
.br
.ti -1c
.RI "#define \fBKMOUSE_COLOR_LIGHT_CYAN\fP   0xB"
.br
.ti -1c
.RI "#define \fBKMOUSE_COLOR_LIGHT_GREEN\fP   0xA"
.br
.ti -1c
.RI "#define \fBKMOUSE_COLOR_LIGHT_GREY\fP   0x7"
.br
.ti -1c
.RI "#define \fBKMOUSE_COLOR_LIGHT_MAGENTA\fP   0xD"
.br
.ti -1c
.RI "#define \fBKMOUSE_COLOR_LIGHT_RED\fP   0xC"
.br
.ti -1c
.RI "#define \fBKMOUSE_COLOR_MAGENTA\fP   0x5"
.br
.ti -1c
.RI "#define \fBKMOUSE_COLOR_RED\fP   0x4"
.br
.ti -1c
.RI "#define \fBKMOUSE_COLOR_WHITE\fP   0xF"
.br
.ti -1c
.RI "#define \fBKMOUSE_COLOR_YELLOW\fP   0xE"
.br
.ti -1c
.RI "#define \fBMOUSE_POINTER_COLOR\fP   \fBKMOUSE_COLOR_GREEN\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define KMOUSE_COLOR_BLACK   0x0"

.PP
Definition at line \fB9\fP of file \fBkmouse\&.hpp\fP\&.
.SS "#define KMOUSE_COLOR_BLUE   0x1"

.PP
Definition at line \fB10\fP of file \fBkmouse\&.hpp\fP\&.
.SS "#define KMOUSE_COLOR_BROWN   0x6"

.PP
Definition at line \fB15\fP of file \fBkmouse\&.hpp\fP\&.
.SS "#define KMOUSE_COLOR_CYAN   0x3"

.PP
Definition at line \fB12\fP of file \fBkmouse\&.hpp\fP\&.
.SS "#define KMOUSE_COLOR_DARK_GREY   0x8"

.PP
Definition at line \fB17\fP of file \fBkmouse\&.hpp\fP\&.
.SS "#define KMOUSE_COLOR_GREEN   0x2"

.PP
Definition at line \fB11\fP of file \fBkmouse\&.hpp\fP\&.
.SS "#define KMOUSE_COLOR_LIGHT_BLUE   0x9"

.PP
Definition at line \fB18\fP of file \fBkmouse\&.hpp\fP\&.
.SS "#define KMOUSE_COLOR_LIGHT_CYAN   0xB"

.PP
Definition at line \fB20\fP of file \fBkmouse\&.hpp\fP\&.
.SS "#define KMOUSE_COLOR_LIGHT_GREEN   0xA"

.PP
Definition at line \fB19\fP of file \fBkmouse\&.hpp\fP\&.
.SS "#define KMOUSE_COLOR_LIGHT_GREY   0x7"

.PP
Definition at line \fB16\fP of file \fBkmouse\&.hpp\fP\&.
.SS "#define KMOUSE_COLOR_LIGHT_MAGENTA   0xD"

.PP
Definition at line \fB22\fP of file \fBkmouse\&.hpp\fP\&.
.SS "#define KMOUSE_COLOR_LIGHT_RED   0xC"

.PP
Definition at line \fB21\fP of file \fBkmouse\&.hpp\fP\&.
.SS "#define KMOUSE_COLOR_MAGENTA   0x5"

.PP
Definition at line \fB14\fP of file \fBkmouse\&.hpp\fP\&.
.SS "#define KMOUSE_COLOR_RED   0x4"

.PP
Definition at line \fB13\fP of file \fBkmouse\&.hpp\fP\&.
.SS "#define KMOUSE_COLOR_WHITE   0xF"

.PP
Definition at line \fB24\fP of file \fBkmouse\&.hpp\fP\&.
.SS "#define KMOUSE_COLOR_YELLOW   0xE"

.PP
Definition at line \fB23\fP of file \fBkmouse\&.hpp\fP\&.
.SS "#define MOUSE_POINTER_COLOR   \fBKMOUSE_COLOR_GREEN\fP"

.PP
Definition at line \fB25\fP of file \fBkmouse\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OSOS - Documentation from the source code\&.
