.TH "/home/shreekar/Desktop/Building_own_OS/OSOS/libk_header/hardware_communication/kport.hpp" 3 "Fri Oct 24 2025 10:32:01" "OSOS - Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/shreekar/Desktop/Building_own_OS/OSOS/libk_header/hardware_communication/kport.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <cstdint>\fP
.br
\fC#include 'basic/kiostream\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBhardware_communication::Port\fP"
.br
.RI "Base class for hardware I/O port communication\&. "
.ti -1c
.RI "class \fBhardware_communication::Port16Bit\fP"
.br
.RI "Represents a 16-bit (word-sized) I/O port\&. @inherits \fBPort\fP\&. "
.ti -1c
.RI "class \fBhardware_communication::Port32Bit\fP"
.br
.RI "Represents a 32-bit (double-word-sized) I/O port\&. @inherits \fBPort\fP\&. "
.ti -1c
.RI "class \fBhardware_communication::Port8Bit\fP"
.br
.RI "Represents an 8-bit (byte-sized) I/O port\&. @inherits \fBPort\fP\&. "
.ti -1c
.RI "class \fBhardware_communication::Port8BitSlow\fP"
.br
.RI "Represents an 8-bit I/O port with a forced delay on writes\&. @inherits \fBPort8Bit\fP\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBhardware_communication\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for OSOS - Documentation from the source code\&.
