.TH "libk_header/hardware_communication/kport.hpp" 3 "Fri Oct 24 2025 00:21:12" "OSOS - Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libk_header/hardware_communication/kport.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <cstdint>\fP
.br
\fC#include 'basic/kiostream\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBhardware_communication::Port\fP"
.br
.ti -1c
.RI "class \fBhardware_communication::Port16Bit\fP"
.br
.ti -1c
.RI "class \fBhardware_communication::Port32Bit\fP"
.br
.ti -1c
.RI "class \fBhardware_communication::Port8Bit\fP"
.br
.ti -1c
.RI "class \fBhardware_communication::Port8BitSlow\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBhardware_communication\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for OSOS - Documentation from the source code\&.
