OSOS Dev: hardware_communication::PCI_Controller
hardware_communication::PCI_Controller
Manages communication with the PCI bus via the x86 Configuration Space mechanism.
#include "kpci.hpp"
Public Member Functions
PCI_Controller ()
~PCI_Controller ()
bool deviceHasFunctions (uint8_t bus, uint8_t device)
Checks if a device is a multi-function device.
BaseAddressRegister getBaseAddressRegister (uint8_t bus, uint8_t device, uint8_t function, uint16_t bar)
Decodes a raw BAR value into a BaseAddressRegister object.
PCI_DeviceDescriptor getDeviceDescriptor (uint8_t bus, uint8_t device, uint8_t function)
Reads the configuration header to create a descriptor object.
driver::Driver * getDriver (PCI_DeviceDescriptor dev, hardware_communication::InterruptManager *interrupt_manager)
Factory method that instantiates the correct driver for a given device.
uint16_t read16 (uint8_t bus, uint8_t device, uint8_t function, uint8_t registerOffset)
Reads a 16-bit word from the PCI configuration space.
uint32_t read32 (uint8_t bus, uint8_t device, uint8_t function, uint8_t registerOffset)
Reads a 32-bit double word from the PCI configuration space.
uint8_t read8 (uint8_t bus, uint8_t device, uint8_t function, uint8_t registerOffset)
Reads an 8-bit byte from the PCI configuration space.
void recursiveSelDriver (uint8_t bus, driver::DriverManager *driver_manager, hardware_communication::InterruptManager *interrupt_manager)
Recursively scans the bus for devices and bridges, assigning drivers where possible.
void scanBus (uint8_t bus)
Scans a bus just for listing devices (does not instantiate drivers).
void selectDrivers (driver::DriverManager *driver_manager, hardware_communication::InterruptManager *interrupt_manager)
Starts the driver selection process from Bus 0.
void write16 (uint8_t bus, uint8_t device, uint8_t function, uint8_t registerOffset, uint16_t value)
Safely writes a 16-bit word to the PCI configuration space.
void write32 (uint8_t bus, uint8_t device, uint8_t function, uint8_t registerOffset, uint32_t value)
Writes a 32-bit double word to the PCI configuration space.
void write8 (uint8_t bus, uint8_t device, uint8_t function, uint8_t registerOffset, uint8_t value)
Safely writes an 8-bit byte to the PCI configuration space.
Private Member Functions
uint32_t getAddress (uint8_t bus, uint8_t device, uint8_t function, uint8_t registerOffset)
Helper to construct the 32-bit CONFIG_ADDRESS.
Private Attributes
Port32Bit commandPort
Port32Bit dataPort
Detailed Description
Manages communication with the PCI bus via the x86 Configuration Space mechanism.
Definition at line 54 of file kpci.hpp.
Constructor & Destructor Documentation
PCI_Controller()
PCI_Controller::PCI_Controller ()
Definition at line 16 of file kpci.cpp.
: dataPort(0xCFC), commandPort(0xCF8) {}
~PCI_Controller()
PCI_Controller::~PCI_Controller ()
Definition at line 18 of file kpci.cpp.
{}
Member Function Documentation
deviceHasFunctions()
bool PCI_Controller::deviceHasFunctions (uint8_t bus, uint8_t device)
Checks if a device is a multi-function device.
Parameters
bus bus number.
device device number.
Returns
True if the device has multiple functions (bit 7 of Header Type is set), false otherwise.
Definition at line 87 of file kpci.cpp.
{
    return (read8(bus, device, 0, 0x0E) & 0x80);
}
References read8().
Referenced by recursiveSelDriver(), and scanBus().
getAddress()
uint32_t PCI_Controller::getAddress (uint8_t bus, uint8_t device, uint8_t function, uint8_t registerOffset) private
Helper to construct the 32-bit CONFIG_ADDRESS.
Parameters
bus bus number (0-255).
device device number (0-31).
function function number (0-7).
registerOffset offset into the configuration space (must be 4-byte aligned).
Returns
A 32-bit integer formatted for port 0xCF8.
Definition at line 20 of file kpci.cpp.
{
    uint32_t lbus = (uint32_t)bus;
    uint32_t ldevice = (uint32_t)device;
    uint32_t lfunction = (uint32_t)function;
    return 0x80000000
         | (lbus << 16)
         | (ldevice << 11)
         | (lfunction << 8)
         | (registerOffset & 0xFC);
}
Referenced by read32(), and write32().
getBaseAddressRegister()
BaseAddressRegister PCI_Controller::getBaseAddressRegister (uint8_t bus, uint8_t device, uint8_t function, uint16_t bar)
Decodes a raw BAR value into a BaseAddressRegister object.
Parameters
bus bus number.
device device number.
function function number.
bar index of the BAR to read (0-5).
Returns
A BaseAddressRegister struct with the decoded address and type.
Definition at line 220 of file kpci.cpp.
{
    BaseAddressRegister result;
    uint32_t headertype = read8(bus, device, function, 0x0E) & 0x7F;
    int maxBARs = 6 - (4 * headertype);
    if(bar >= maxBARs) return result;
    uint32_t bar_value = read32(bus, device, function, 0x10 + (4 * bar));
    result.type = (bar_value & 0x1) ? inputOutput : memoryMapping;
    if(result.type == memoryMapping)
    {
        result.address = (uint8_t*)(bar_value & ~0xF);
        result.prefetchable = ((bar_value & 0x8) != 0);
    }
    else
    {
        result.address = (uint8_t*)(bar_value & ~0x3);
        result.prefetchable = false;
    }
    return result;
}
References hardware_communication::BaseAddressRegister::address, hardware_communication::inputOutput, hardware_communication::memoryMapping, hardware_communication::BaseAddressRegister::prefetchable, read32(), read8(), and hardware_communication::BaseAddressRegister::type.
Referenced by recursiveSelDriver().
getDeviceDescriptor()
PCI_DeviceDescriptor PCI_Controller::getDeviceDescriptor (uint8_t bus, uint8_t device, uint8_t function)
Reads the configuration header to create a descriptor object.
Parameters
bus bus number.
device device number.
function function number.
Returns
A populated PCI_DeviceDescriptor object.
Definition at line 92 of file kpci.cpp.
{
    PCI_DeviceDescriptor result;
    result.bus =        bus;
    result.device =     device;
    result.function =   function;
    result.vendorId =   read16(bus, device, function, 0x00);
    result.deviceId =   read16(bus, device, function, 0x02);
    result.revision =       read8(bus, device, function, 0x08);
    result.interfaceId =    read8(bus, device, function, 0x09);
    result.subclassId =     read8(bus, device, function, 0x0A);
    result.classId =        read8(bus, device, function, 0x0B);
    result.headerType = read8(bus, device, function, 0x0E);
    for(int i = 0; i < 6; i++){
        result.bar[i] = read32(bus, device, function, 0x10 + (i * 4));
    }
    result.interrupt =  read8(bus, device, function, 0x3C);
    return result;
}
References hardware_communication::PCI_DeviceDescriptor::bar, hardware_communication::PCI_DeviceDescriptor::bus, hardware_communication::PCI_DeviceDescriptor::classId, hardware_communication::PCI_DeviceDescriptor::device, hardware_communication::PCI_DeviceDescriptor::deviceId, hardware_communication::PCI_DeviceDescriptor::function, hardware_communication::PCI_DeviceDescriptor::headerType, hardware_communication::PCI_DeviceDescriptor::interfaceId, hardware_communication::PCI_DeviceDescriptor::interrupt, read16(), read32(), read8(), hardware_communication::PCI_DeviceDescriptor::revision, hardware_communication::PCI_DeviceDescriptor::subclassId, and hardware_communication::PCI_DeviceDescriptor::vendorId.
Referenced by recursiveSelDriver(), and scanBus().
getDriver()
driver::Driver * PCI_Controller::getDriver (PCI_DeviceDescriptor dev, hardware_communication::InterruptManager * interrupt_manager)
Factory method that instantiates the correct driver for a given device.
Parameters
dev device descriptor containing VendorID and DeviceID.
interrupt_manager interrupt manager to pass to the driver.
Returns
A pointer to the new driver instance, or 0 if no driver is found.
Definition at line 246 of file kpci.cpp.
{
    (void) interrupt_manager;
    driver::Driver* driver = 0;
    switch(dev.vendorId)
    {
        case 0x1022: // AMD
            switch(dev.deviceId)
            {
                case 0x2000:
                    basic::printf("AMD am79c973 ");
                    break;
            }
            break;
        case 0x8086: // Intel
            switch(dev.deviceId)
            {
                case 0x1237: basic::printf("Intel 440FX Host Bridge "); break;
                case 0x7000: basic::printf("Intel PIIX3 ISA Bridge "); break;
                case 0x7010: basic::printf("Intel PIIX3 IDE Controller "); break;
                case 0x7113: basic::printf("Intel PIIX4 ACPI "); break;
                case 0x100E: basic::printf("Intel E1000 Ethernet "); break;
            }
            break;
        case 0x1234:
            switch(dev.deviceId)
            {
                case 0x1111: basic::printf("QEMU VGA Graphics "); break;
            }
            break;
    }
    basic::printf("| ");
    switch(dev.classId)
    {
        case 0x03:
            if(dev.subclassId == 0x00) basic::printf("Generic VGA ");
            break;
        case 0x02:
            basic::printf("Generic Network Card ");
            break;
    }
    basic::printf("|\n---\n");
    return driver;
}
References hardware_communication::PCI_DeviceDescriptor::classId, hardware_communication::PCI_DeviceDescriptor::deviceId, basic::printf(), hardware_communication::PCI_DeviceDescriptor::subclassId, and hardware_communication::PCI_DeviceDescriptor::vendorId.
Referenced by recursiveSelDriver().
read16()
uint16_t PCI_Controller::read16 (uint8_t bus, uint8_t device, uint8_t function, uint8_t registerOffset)
Reads a 16-bit word from the PCI configuration space.
Parameters
bus bus number.
device device number.
function function number.
registerOffset offset.
Returns
16-bit value.
Definition at line 40 of file kpci.cpp.
{
    uint32_t dword = read32(bus, device, function, registerOffset);
    uint32_t shift = (8 * (registerOffset % 4));
    return (uint16_t)(dword >> shift);
}
References read32().
Referenced by getDeviceDescriptor().
read32()
uint32_t PCI_Controller::read32 (uint8_t bus, uint8_t device, uint8_t function, uint8_t registerOffset)
Reads a 32-bit double word from the PCI configuration space.
Parameters
bus bus number.
device device number.
function function number.
registerOffset offset (will be aligned automatically).
Returns
32-bit value at the register.
Definition at line 33 of file kpci.cpp.
{
    uint32_t address = getAddress(bus, device, function, registerOffset);
    commandPort.write(address);
    return dataPort.read();
}
References commandPort, dataPort, getAddress(), hardware_communication::Port32Bit::read(), and hardware_communication::Port32Bit::write().
Referenced by getBaseAddressRegister(), getDeviceDescriptor(), read16(), read8(), write16(), and write8().
read8()
uint8_t PCI_Controller::read8 (uint8_t bus, uint8_t device, uint8_t function, uint8_t registerOffset)
Reads an 8-bit byte from the PCI configuration space.
Parameters
bus bus number.
device device number.
function function number.
registerOffset offset.
Returns
8-bit value.
Definition at line 47 of file kpci.cpp.
{
    uint32_t dword = read32(bus, device, function, registerOffset);
    uint32_t shift = (8 * (registerOffset % 4));
    return (uint8_t)(dword >> shift);
}
References read32().
Referenced by deviceHasFunctions(), getBaseAddressRegister(), getDeviceDescriptor(), recursiveSelDriver(), and scanBus().
recursiveSelDriver()
void PCI_Controller::recursiveSelDriver (uint8_t bus, driver::DriverManager * driver_manager, hardware_communication::InterruptManager * interrupt_manager)
Recursively scans the bus for devices and bridges, assigning drivers where possible.
Parameters
bus current bus being scanned.
driver_manager Pointer to the global driver manager.
interrupt_manager Pointer to the global interrupt manager.
Definition at line 118 of file kpci.cpp.
{
    for(uint8_t device=0; device<32; device++)
    {
        uint8_t numFunctions = deviceHasFunctions(bus, device) ? 8 : 1;
        for(uint8_t function=0; function<numFunctions; function++)
        {
            PCI_DeviceDescriptor dev = getDeviceDescriptor(bus, device, function);
            if(dev.vendorId == 0x0000 || dev.vendorId == 0xFFFF) continue;
            basic::printf("PCI Bus %#3x, Device %#3x, Function %#3x ", bus, device, function);
            basic::printf("=> Vendor %#5hx, Device %#5hx (Class %#3x, Sub %#3x)\n", dev.vendorId, dev.deviceId, dev.classId, dev.subclassId);
            for(uint16_t barNum = 0; barNum < 6; barNum++){
                BaseAddressRegister bar = getBaseAddressRegister(bus, device, function, barNum);
                if(bar.address && (bar.type == inputOutput)) dev.portBase[barNum] = (uint32_t)bar.address;
            }
            driver::Driver* driver = getDriver(dev, interrupt_manager);
            if(driver != 0) driver_manager->addDriver(driver);
            if(dev.classId == 0x06 && dev.subclassId == 0x04)
            {
                uint8_t secondaryBus = read8(bus, device, function, 0x19);
                if (secondaryBus != bus) recursiveSelDriver(secondaryBus, driver_manager, interrupt_manager);
            }
        }
    }
}
References driver::DriverManager::addDriver(), hardware_communication::BaseAddressRegister::address, hardware_communication::PCI_DeviceDescriptor::classId, deviceHasFunctions(), hardware_communication::PCI_DeviceDescriptor::deviceId, getBaseAddressRegister(), getDeviceDescriptor(), getDriver(), hardware_communication::inputOutput, hardware_communication::PCI_DeviceDescriptor::portBase, basic::printf(), read8(), recursiveSelDriver(), hardware_communication::PCI_DeviceDescriptor::subclassId, hardware_communication::BaseAddressRegister::type, and hardware_communication::PCI_DeviceDescriptor::vendorId.
Referenced by recursiveSelDriver(), and selectDrivers().
scanBus()
void PCI_Controller::scanBus (uint8_t bus)
Scans a bus just for listing devices (does not instantiate drivers).
Parameters
bus bus number to scan.
Definition at line 154 of file kpci.cpp.
{
    for(uint8_t device=0; device<32; device++)
    {
        uint8_t numFunctions = deviceHasFunctions(bus, (uint8_t)device) ? 8 : 1;
        for(uint8_t function=0; function<numFunctions; function++)
        {
            PCI_DeviceDescriptor dev = getDeviceDescriptor(bus, device, function);
            if(dev.vendorId == 0x0000 || dev.vendorId == 0xFFFF) continue;
            basic::printf("---\n");
            basic::printf("PCI Bus %#3x, Device %#3x, Function %#3x ", bus, device, function);
            basic::printf("=> Vendor %#5hx, Device %#5hx (Class %#3x, Sub %#3x)\n", dev.vendorId, dev.deviceId, dev.classId, dev.subclassId);
            switch(dev.vendorId)
            {
                case 0x1022: // AMD
                    switch(dev.deviceId)
                    {
                        case 0x2000: basic::printf("AMD am79c973 "); break;
                    }
                    break;
                case 0x8086: // Intel
                    switch(dev.deviceId)
                    {
                        case 0x1237: basic::printf("Intel 440FX Host Bridge "); break;
                        case 0x7000: basic::printf("Intel PIIX3 ISA Bridge "); break;
                        case 0x7010: basic::printf("Intel PIIX3 IDE Controller "); break;
                        case 0x7113: basic::printf("Intel PIIX4 ACPI "); break;
                        case 0x100E: basic::printf("Intel E1000 Ethernet "); break;
                    }
                    break;
                case 0x1234: // QEMU / Bochs
                    switch(dev.deviceId)
                    {
                        case 0x1111: basic::printf("QEMU VGA Graphics "); break;
                    }
                    break;
            }
            basic::printf("| ");
            switch(dev.classId)
            {
                case 0x03:
                    if(dev.subclassId == 0x00) basic::printf("Generic VGA ");
                    break;
                case 0x02:
                    basic::printf("Generic Network Card ");
                    break;
            }
            basic::printf("|\n");
            if(dev.classId == 0x06 && dev.subclassId == 0x04)
            {
                uint8_t secondaryBus = read8(bus, device, function, 0x19);
                if (secondaryBus != bus) scanBus(secondaryBus);
            }
        }
    }
}
References hardware_communication::PCI_DeviceDescriptor::classId, deviceHasFunctions(), hardware_communication::PCI_DeviceDescriptor::deviceId, getDeviceDescriptor(), basic::printf(), read8(), scanBus(), hardware_communication::PCI_DeviceDescriptor::subclassId, and hardware_communication::PCI_DeviceDescriptor::vendorId.
Referenced by KernelShell::process_command(), and scanBus().
selectDrivers()
void PCI_Controller::selectDrivers (driver::DriverManager * driver_manager, hardware_communication::InterruptManager * interrupt_manager)
Starts the driver selection process from Bus 0.
Parameters
driver_manager Pointer to the global driver manager.
interrupt_manager Pointer to the global interrupt manager.
Definition at line 149 of file kpci.cpp.
{
    recursiveSelDriver(0, driver_manager, interrupt_manager);
}
References recursiveSelDriver().
Referenced by kernelMain().
write16()
void PCI_Controller::write16 (uint8_t bus, uint8_t device, uint8_t function, uint8_t registerOffset, uint16_t value)
Safely writes a 16-bit word to the PCI configuration space.
Parameters
bus bus number.
device device number.
function function number.
registerOffset offset.
value 16-bit value to write.
Definition at line 61 of file kpci.cpp.
{
    uint32_t dword = read32(bus, device, function, registerOffset);
    uint32_t shift = (8 * (registerOffset % 4));
    uint32_t mask = 0xFFFF << shift;
    dword &= ~mask;
    dword |= ((uint32_t)value << shift);
    write32(bus, device, function, registerOffset, dword);
}
References read32(), and write32().
write32()
void PCI_Controller::write32 (uint8_t bus, uint8_t device, uint8_t function, uint8_t registerOffset, uint32_t value)
Writes a 32-bit double word to the PCI configuration space.
Parameters
bus bus number.
device device number.
function function number.
registerOffset offset.
value 32-bit value to write.
Definition at line 54 of file kpci.cpp.
{
    uint32_t address = getAddress(bus, device, function, registerOffset);
    commandPort.write(address);
    dataPort.write(value);
}
References commandPort, dataPort, getAddress(), and hardware_communication::Port32Bit::write().
Referenced by write16(), and write8().
write8()
void PCI_Controller::write8 (uint8_t bus, uint8_t device, uint8_t function, uint8_t registerOffset, uint8_t value)
Safely writes an 8-bit byte to the PCI configuration space.
Parameters
bus bus number.
device device number.
function function number.
registerOffset offset.
value 8-bit value to write.
Definition at line 74 of file kpci.cpp.
{
    uint32_t dword = read32(bus, device, function, registerOffset);
    uint32_t shift = (8 * (registerOffset % 4));
    uint32_t mask = 0xFF << shift;
    dword &= ~mask;
    dword |= ((uint32_t)value << shift);
    write32(bus, device, function, registerOffset, dword);
}
References read32(), and write32().
Member Data Documentation
commandPort
Port32Bit hardware_communication::PCI_Controller::commandPort private
Definition at line 57 of file kpci.hpp.
Referenced by read32(), and write32().
dataPort
Port32Bit hardware_communication::PCI_Controller::dataPort private
Definition at line 56 of file kpci.hpp.
Referenced by read32(), and write32().
The documentation for this class was generated from the following files:
kpci.hpp
kpci.cpp