OSOS Dev: KernelShell
KernelShell
A simple shell/terminal manager for the kernel.
#include "kernel.hpp"
Public Member Functions
KernelShell (essential::KernelThreadManager *osos_ThreadManager_ptr, multiboot_info_t *mbi)
~KernelShell ()
bool addShellTask (essential::KernelThread *task)
to add KernelThread to task list of shell...
void handle_key (char c)
The single, centralized function for handling all key presses.
void process_command (const char *command)
Simple command processor.
Private Attributes
int m_buffer_index
char m_line_buffer [256]
multiboot_info_t * mbi
int numShellThreads
essential::KernelThreadManager * osos_ThreadManager_ptr
hardware_communication::PCI_Controller pciController
essential::KernelThread * shell_threads_ptr [maxNumShellTask]
Detailed Description
A simple shell/terminal manager for the kernel.
Definition at line 22 of file kernel.hpp.
Constructor & Destructor Documentation
KernelShell()
KernelShell::KernelShell (essential::KernelThreadManager * osos_ThreadManager_ptr, multiboot_info_t * mbi) inline
Definition at line 33 of file kernel.hpp.
    {
        this->osos_ThreadManager_ptr=osos_ThreadManager_ptr;
        this->mbi=mbi;
        m_buffer_index = 0;
        m_line_buffer[0] = '\0';
        numShellThreads = 0;
    }
References m_buffer_index, m_line_buffer, mbi, numShellThreads, and osos_ThreadManager_ptr.
~KernelShell()
KernelShell::~KernelShell () inline
Definition at line 41 of file kernel.hpp.
{}
Member Function Documentation
addShellTask()
bool KernelShell::addShellTask (essential::KernelThread * task) inline
to add KernelThread to task list of shell...
Parameters
task pointer of KernelThread
Returns
bool : true if successfully added else false
Definition at line 46 of file kernel.hpp.
{
        if(numShellThreads >= maxNumShellTask) return false;
        shell_threads_ptr[numShellThreads++]=task;
        return true;
    }
References maxNumShellTask, numShellThreads, and shell_threads_ptr.
Referenced by kernelMain().
handle_key()
void KernelShell::handle_key (char c) inline
The single, centralized function for handling all key presses.
Parameters
c The character received from any input driver (keyboard or serial driver).
Definition at line 54 of file kernel.hpp.
    {
        if (c == 0) return;
        switch(c)
        {
            // PS/2 Keyboard sends '\n' (from keyboard driver)
            // Serial sends '\r' (from serial driver)
            case '\r':
            case '\n':
                basic::printf("\n");
                m_line_buffer[m_buffer_index] = '\0';
                if (m_buffer_index > 0) {
                    process_command(m_line_buffer);
                }
                // Reset for next line
                m_buffer_index = 0;
                m_line_buffer[0] = '\0';
                basic::printf("\nOSOS> "); // Print a new prompt
                break;
            case 8: // Backspace '\b'
                if (m_buffer_index > 0){
                    m_buffer_index--;
                    m_line_buffer[m_buffer_index] = '\0';
                    basic::printf("\b \b"); // '\b' only move cursor back in serial terminal (e.g. my Ubuntu terminal), so i am printing ' ' once and then again '\b'
                }
                break;
            // Handle printable characters
            default:
                if (c >= ' ' && c <= '~' && m_buffer_index < 254)
                {
                    m_line_buffer[m_buffer_index++] = c;
                    m_line_buffer[m_buffer_index] = '\0';
                    basic::printf("%c", c);
                }
                break;
        }
    }
References m_buffer_index, m_line_buffer, basic::printf(), and process_command().
Referenced by SerialEventHandler_for_kernel::onDataReceived(), and KeyboardEventHandler_for_kernel::onKeyDown().
process_command()
void KernelShell::process_command (const char * command) inline
Simple command processor.
Parameters
command The null-terminated command string to process.
Definition at line 97 of file kernel.hpp.
    {
        if (basic::strcmp(command, "help") == 0) {
            basic::printf("OSOS Kernel Shell Help\n\
help      : list commands\n\
clear     : clear shell\n\
lsmem     : print memory map provided by grub\n\
checkmem  : check how much memory is free (in KB)\n\
checkheap : examine kernel heap\n\
lspagedir : check active page directory entries for kernel\n\
lspci     : list PCI devices\n\
task<i>   : start ith task(thread) from OSOS shell\n\
numtasks  : to see number of tasks in shell list\n");
        }
        else if(basic::strcmp(command, "clear") ==0){
            basic::clearScreen();
        }
        else if (basic::strcmp(command, "lsmem") == 0){
            memory::printMemoryMap(mbi);
        }
        else if (basic::strcmp(command, "lspci") == 0){
            basic::printf("Listing PCI devices...\n");
            pciController.scanBus(0);
        }
        else if (basic::strncmp(command, "task", 4) == 0){
            char* tasknumstr=(char*)command+4;
            int tasknum = basic::stoi(tasknumstr) - 1;
            if(tasknum<0 || tasknum>=numShellThreads)
                basic::printf("task number %d not present in task list of OSOS shell :(", tasknum+1);
            else{
                basic::printf("Starting task number %d...\n", tasknum+1);
                if (osos_ThreadManager_ptr->addThread(shell_threads_ptr[tasknum])==false) {
                     basic::printf("Error: failed to start task%d.\n", tasknum+1);
                }
            }
        }
        else if(basic::strcmp(command, "numtasks") ==0){
            basic::printf("Number of tasks in shell list : %d\n", numShellThreads);
        }
        else if(basic::strcmp(command, "checkmem") ==0){
            basic::printf("Total Free Memory : %d KB\n",memory::PhysicalMemoryManager::get_free_memory_kb());
        }
        else if(basic::strcmp(command, "checkheap") ==0){
            memory::kernel_heap.printHeapInfo();
        }
        else if(basic::strcmp(command, "lspagedir") ==0){
            memory::PagingManager::printPageDirectory();
        }
        else {
            basic::printf("Unknown command: '%s'\n", command);
        }
    }
References essential::KernelThreadManager::addThread(), basic::clearScreen(), memory::PhysicalMemoryManager::get_free_memory_kb(), memory::kernel_heap, mbi, numShellThreads, osos_ThreadManager_ptr, pciController, basic::printf(), memory::HeapManager::printHeapInfo(), memory::printMemoryMap(), memory::PagingManager::printPageDirectory(), hardware_communication::PCI_Controller::scanBus(), shell_threads_ptr, basic::stoi(), basic::strcmp(), and basic::strncmp().
Referenced by handle_key().
Member Data Documentation
m_buffer_index
int KernelShell::m_buffer_index private
Definition at line 26 of file kernel.hpp.
Referenced by KernelShell(), and handle_key().
m_line_buffer
char KernelShell::m_line_buffer[256] private
Definition at line 25 of file kernel.hpp.
Referenced by KernelShell(), and handle_key().
mbi
multiboot_info_t* KernelShell::mbi private
Definition at line 24 of file kernel.hpp.
Referenced by KernelShell(), and process_command().
numShellThreads
int KernelShell::numShellThreads private
Definition at line 30 of file kernel.hpp.
Referenced by KernelShell(), addShellTask(), and process_command().
osos_ThreadManager_ptr
essential::KernelThreadManager* KernelShell::osos_ThreadManager_ptr private
Definition at line 28 of file kernel.hpp.
Referenced by KernelShell(), and process_command().
pciController
hardware_communication::PCI_Controller KernelShell::pciController private
Definition at line 27 of file kernel.hpp.
Referenced by process_command().
shell_threads_ptr
essential::KernelThread* KernelShell::shell_threads_ptr[maxNumShellTask] private
Definition at line 29 of file kernel.hpp.
Referenced by addShellTask(), and process_command().
The documentation for this class was generated from the following file:
kernel.hpp