OSOS Dev: kernel.cpp File Reference
kernel.cpp File Reference
#include <cstdint>
#include "basic/multiboot.h"
#include "essential/kicxxabi.hpp"
#include "basic/kiostream.hpp"
#include "basic/kmemory.hpp"
#include "essential/kgdt.hpp"
#include "hardware_communication/kinterrupt.hpp"
#include "driver/kkeyboard.hpp"
#include "driver/kmouse.hpp"
#include "driver/kdriver.hpp"
#include "driver/kserial.hpp"
#include "hardware_communication/kpci.hpp"
Classes
class KernelShell
A simple shell/terminal manager for the kernel.
class KeyboardEventHandler_for_kernel
Custom KeyboardEventHandler implementation for kernel.
class MouseEventHandler_for_kernel
Custom MouseEventHandler implementation for kernel.
class SerialEventHandler_for_kernel
Custom SerialEventHandler implementation for kernel.
Functions
void kernelMain (multiboot_info_t *mbi, uint32_t magicnumber)
The main entry point for the C++ kernel.
Function Documentation
kernelMain()
void kernelMain (multiboot_info_t * mbi, uint32_t magicnumber)
The main entry point for the C++ kernel.
Parameters
mbi Pointer to the Multiboot information structure provided by GRUB.
magicnumber The magic number passed by GRUB to verify boot.
Definition at line 209 of file kernel.cpp.
{
    essential::__callConstructors(); // calling all global constructors
    basic::enable_cursor(0,15);
    basic::clearScreen();
    //-------------Global Descriptor Table -------------
    essential::GDT_Manager osos_GDT;
    osos_GDT.installTable();
    //------------Interrupt Descriptor Table and Drivers -------------
    hardware_communication::InterruptManager osos_InterruptManager(&osos_GDT);
    osos_InterruptManager.installTable();
    // --- Create the central shell FIRST ---
    KernelShell shell;
    //------------Creating object of drivers so that they will handle their corresponding Interrupts------------
    driver::DriverManager driverManager;
        // --- Pass the shell to the handlers ---
        KeyboardEventHandler_for_kernel keyboardEventHandler_for_kernel(&shell);
        driver::KeyboardDriver keyboard(&osos_InterruptManager,&keyboardEventHandler_for_kernel);
        driverManager.addDriver(&keyboard);
        MouseEventHandler_for_kernel mouseEventHandler_for_kernel;
        driver::MouseDriver mouse(&osos_InterruptManager, &mouseEventHandler_for_kernel);
        driverManager.addDriver(&mouse);
        SerialEventHandler_for_kernel serialEventHandler_for_kernel(&shell);
        driver::SerialDriver serialIO(&osos_InterruptManager, &serialEventHandler_for_kernel);
        driverManager.addDriver(&serialIO);
        hardware_communication::PCI_Controller pciController;
        pciController.selectDrivers(&driverManager);
    driverManager.activateAll();
    hardware_communication::InterruptManager::activate();
    // essential::GDT_Manager::printLoadedTableHeader();
    // hardware_communication::InterruptManager::printLoadedTableHeader();
    basic::printf("HELLO FROM OSOS :)\n");
    basic::printf("OSOS> "); // Print the first prompt
    while (true){asm("hlt");};
    basic::disable_cursor();
    essential::__cxa_finalize(0); // calling all global destructors
    (void)mbi;
    (void)magicnumber;
}
References essential::__callConstructors(), essential::__cxa_finalize(), hardware_communication::InterruptManager::activate(), driver::DriverManager::activateAll(), driver::DriverManager::addDriver(), basic::clearScreen(), basic::disable_cursor(), basic::enable_cursor(), essential::GDT_Manager::installTable(), hardware_communication::InterruptManager::installTable(), basic::printf(), and hardware_communication::PCI_Controller::selectDrivers().