OSOS Dev: concurrency::KThread
concurrency::KThread
Represents a single unit of execution (a thread or process) in the OS.
#include "kmultitasking.hpp"
Public Member Functions
KThread (void(*entrypoint)(void *), void *arg)
Constructs a new KThread.
~KThread ()
void reset ()
Resets or initializes the thread's stack frame.
bool start ()
start thread (add thread to thread scheduling)
Private Attributes
CPUState * cpustate
Pointer to the saved register state inside the stack. Used by the scheduler to restore this thread's context.
void * m_arg
this is argument pointer for entrypoint.
uint16_t m_codeSegmentSelector
The Code Segment selector to run this thread in (Kernel vs User).
void(* m_entrypoint)(void *)
The function to execute when the thread starts.
uint8_t stack [4096]
The dedicated kernel stack for this thread.
Detailed Description
Represents a single unit of execution (a thread or process) in the OS.
Each KThread maintains its own private stack memory (4KB) and a pointer to its saved CPU state.
Definition at line 32 of file kmultitasking.hpp.
Constructor & Destructor Documentation
KThread()
KThread::KThread (void(*)(void *) entrypoint, void * arg)
Constructs a new KThread.
Parameters
entrypoint The function pointer where execution should begin.
arg Void* argument pointer for entrypoint
Definition at line 8 of file kmultitasking.cpp.
{
    this->m_entrypoint = entrypoint;
    this->m_arg = arg;
    this->m_codeSegmentSelector = activeKThreadManager->gdt_manager->kernel_CS_selector();
}
References concurrency::KThreadManager::gdt_manager, essential::GDT_Manager::kernel_CS_selector(), m_arg, m_codeSegmentSelector, and m_entrypoint.
~KThread()
KThread::~KThread ()
Definition at line 15 of file kmultitasking.cpp.
{}
Member Function Documentation
reset()
void KThread::reset ()
Resets or initializes the thread's stack frame.
This function sets up a "fake" interrupt stack frame at the top of the stack array. It sets the instruction pointer (EIP) to the entrypoint and the stack pointer (ESP) to the onTaskExit handler. This must be called before the thread is run for the first time.
Definition at line 22 of file kmultitasking.cpp.
{
    cpustate = (CPUState*) (stack + 4096 - sizeof(CPUState));
    cpustate->eax = 0; cpustate->ebx = 0; cpustate->ecx = 0; cpustate->edx = 0;
    cpustate->esi = 0; cpustate->edi = 0; cpustate->ebp = 0;
    cpustate->gs = 0x10;
    cpustate->fs = 0x10;
    cpustate->es = 0x10;
    cpustate->ds = 0x10;
    cpustate->error = 0;
    cpustate->eip = (uint32_t)m_entrypoint;
    cpustate->cs = m_codeSegmentSelector;
    cpustate->eflags = 0x202;
    cpustate->esp = (uint32_t)KThreadManager::onThreadExit;
    cpustate->ss  = (uint32_t)m_arg;
}
References cpustate, concurrency::CPUState::cs, concurrency::CPUState::ds, concurrency::CPUState::eax, concurrency::CPUState::ebp, concurrency::CPUState::ebx, concurrency::CPUState::ecx, concurrency::CPUState::edi, concurrency::CPUState::edx, concurrency::CPUState::eflags, concurrency::CPUState::eip, concurrency::CPUState::error, concurrency::CPUState::es, concurrency::CPUState::esi, concurrency::CPUState::esp, concurrency::CPUState::fs, concurrency::CPUState::gs, m_arg, m_codeSegmentSelector, m_entrypoint, concurrency::KThreadManager::onThreadExit(), concurrency::CPUState::ss, and stack.
Referenced by concurrency::KThreadManager::addThread().
start()
bool KThread::start ()
start thread (add thread to thread scheduling)
Returns
true if the thread was added successfully, false if the queue is full or thread is already running.
Definition at line 17 of file kmultitasking.cpp.
{
    return activeKThreadManager->addThread(this);
}
References activeKThreadManager, and concurrency::KThreadManager::addThread().
Referenced by kernelMain().
Member Data Documentation
cpustate
CPUState* concurrency::KThread::cpustate private
Pointer to the saved register state inside the stack. Used by the scheduler to restore this thread's context.
Definition at line 40 of file kmultitasking.hpp.
Referenced by reset(), and concurrency::KThreadManager::scheduleThreads().
m_arg
void* concurrency::KThread::m_arg private
this is argument pointer for entrypoint.
Definition at line 46 of file kmultitasking.hpp.
Referenced by KThread(), and reset().
m_codeSegmentSelector
uint16_t concurrency::KThread::m_codeSegmentSelector private
The Code Segment selector to run this thread in (Kernel vs User).
Definition at line 49 of file kmultitasking.hpp.
Referenced by KThread(), and reset().
m_entrypoint
void(* concurrency::KThread::m_entrypoint) (void *) private
The function to execute when the thread starts.
Definition at line 43 of file kmultitasking.hpp.
Referenced by KThread(), and reset().
stack
uint8_t concurrency::KThread::stack[4096] private
The dedicated kernel stack for this thread.
Definition at line 36 of file kmultitasking.hpp.
Referenced by reset().
The documentation for this class was generated from the following files:
kmultitasking.hpp
kmultitasking.cpp