OSOS Dev: kernel.hpp File Reference
kernel.hpp File Reference
#include "basic/multiboot.h"
#include "essential/kgdt.hpp"
#include "essential/kicxxabi.hpp"
#include "essential/kmultitasking.hpp"
#include "hardware_communication/kinterrupt.hpp"
#include "hardware_communication/kpci.hpp"
#include "driver/kdriver.hpp"
#include "driver/ktimer.hpp"
#include "driver/kkeyboard.hpp"
#include "driver/kmouse.hpp"
#include "driver/kserial.hpp"
#include "kshell.hpp"
#include "khandlers.hpp"
#include "essential/ktime.hpp"
#include "kernel.hpp"
Classes
struct KernelArgs
Functions
void kernelMain (multiboot_info_t *mbi, uint32_t magicnumber)
Entrypoint for C++ code. we will call this function from assembly.
void kernelTail (void *arg)
This is tail of kernelMain whose CPU state will be preserved.
void task_o (void *arg)
function for shell task1
void task_x (void *arg)
function for shell task2
Class Documentation
KernelArgs
struct KernelArgs
Definition at line 21 of file kernel.hpp.
Class Members
DriverManager * driverManager
GDT_Manager * gdtManager
InterruptManager * interruptManager
KeyboardDriver * keyboard
multiboot_info_t * mbi
MouseDriver * mouse
SerialDriver * serial
KernelShell * shell
TimerDriver * timer
Function Documentation
kernelMain()
void kernelMain (multiboot_info_t * mbi, uint32_t magicnumber)
Entrypoint for C++ code. we will call this function from assembly.
Parameters
mbi multiboot information provided by grub
magicnumber magic number (just to varify)
Definition at line 34 of file kernel.cpp.
{
    essential::__callConstructors();
    basic::enable_cursor(0,15);
    basic::clearScreen();
    // Install GDT
    essential::GDT_Manager osos_GDT_Manager;
    osos_GDT_Manager.installTable();
    // Initialize Memory
    memory::PhysicalMemoryManager::init(mbi);
    memory::PagingManager::init();
    memory::kernel_heap.init((void*)0x1000000, 8 * 1024 * 1024);
    // Initialize Core Kernel Managers
    essential::KThreadManager osos_ThreadManager(&osos_GDT_Manager);
    hardware_communication::InterruptManager osos_InterruptManager(&osos_GDT_Manager, &osos_ThreadManager);
    // Initialize Shell
    KernelShell shell(&osos_ThreadManager, mbi);
    // Initialize Drivers
    driver::DriverManager driverManager;
        driver::TimerDriver timer(&osos_InterruptManager, 1000);
        essential::Time::setTimerDriver(&timer); // to initialize essential::Time with timer
        driverManager.addDriver(&timer);
        KeyboardEventHandler_for_kernel kbdHandler(&shell);
        driver::KeyboardDriver keyboard(&osos_InterruptManager, &kbdHandler);
        driverManager.addDriver(&keyboard);
        MouseEventHandler_for_kernel mouseHandler;
        driver::MouseDriver mouse(&osos_InterruptManager, &mouseHandler);
        driverManager.addDriver(&mouse);
        SerialEventHandler_for_kernel serialHandler(&shell);
        driver::SerialDriver serialIO(&osos_InterruptManager, &serialHandler);
        driverManager.addDriver(&serialIO);
        hardware_communication::PCI_Controller pciController;
        pciController.selectDrivers(&driverManager, &osos_InterruptManager);
    // Activate Hardware
    driverManager.activateAll();
    osos_InterruptManager.installTable();
    // Prepare Thread Arguments
    KernelArgs* kArgs = new KernelArgs();
    kArgs->gdtManager = &osos_GDT_Manager;
    kArgs->interruptManager = &osos_InterruptManager;
    kArgs->driverManager = &driverManager;
    kArgs->timer = &timer;
    kArgs->shell = &shell;
    // Create Tasks
    essential::KThread *haltTask= new essential::KThread(&kernelTail, kArgs);
    essential::KThread* task1 = new essential::KThread(&task_o, nullptr);
    essential::KThread* task2 = new essential::KThread(&task_x, nullptr);
    osos_ThreadManager.addThread(haltTask);
    shell.addShellTask(task1);
    shell.addShellTask(task2);
    // Enable Interrupts (Start the System)
    hardware_communication::InterruptManager::activate();
    while (true){asm("hlt");};
    basic::disable_cursor();
    essential::__cxa_finalize(0);
    (void)magicnumber;
}
References essential::__callConstructors(), essential::__cxa_finalize(), hardware_communication::InterruptManager::activate(), driver::DriverManager::activateAll(), driver::DriverManager::addDriver(), KernelShell::addShellTask(), essential::KThreadManager::addThread(), basic::clearScreen(), basic::disable_cursor(), KernelArgs::driverManager, basic::enable_cursor(), KernelArgs::gdtManager, memory::PagingManager::init(), memory::PhysicalMemoryManager::init(), memory::HeapManager::init(), essential::GDT_Manager::installTable(), hardware_communication::InterruptManager::installTable(), KernelArgs::interruptManager, memory::kernel_heap, kernelTail(), hardware_communication::PCI_Controller::selectDrivers(), essential::Time::setTimerDriver(), KernelArgs::shell, task_o(), task_x(), and KernelArgs::timer.
kernelTail()
void kernelTail (void * arg)
This is tail of kernelMain whose CPU state will be preserved.
Parameters
arg
Definition at line 19 of file kernel.cpp.
{
    KernelArgs* args = (KernelArgs*)arg;
    basic::printf("\nHELLO FROM OSOS (`help` to see commands)...\n");
    basic::printf("\nOSOS> ");
    while (true){
        args->shell->update();
        asm("hlt");
    }
    basic::disable_cursor();
    essential::__cxa_finalize(0);
}
References essential::__cxa_finalize(), basic::disable_cursor(), basic::printf(), KernelArgs::shell, and KernelShell::update().
Referenced by kernelMain().
task_o()
void task_o (void * arg)
function for shell task1
Parameters
arg necessory argument as per KThread rule
Definition at line 3 of file kernel.cpp.
                       {
    (void) arg;
    for(int i=0; i<2000; i++){
        basic::printf("o");
        essential::Time::sleep(1);
    }
}
References basic::printf(), and essential::Time::sleep().
Referenced by kernelMain().
task_x()
void task_x (void * arg)
function for shell task2
Parameters
arg necessory argument as per KThread rule
Definition at line 11 of file kernel.cpp.
                       {
    (void) arg;
    for(int i=0; i<2000; i++){
        basic::printf("x");
        essential::Time::sleep(1);
    }
}
References basic::printf(), and essential::Time::sleep().
Referenced by kernelMain().