OSOS Dev: essential::TaskManager
essential::TaskManager
Manages multitasking and scheduling of tasks.
#include "kmultitasking.hpp"
Public Member Functions
TaskManager ()
Initializes the Task Manager.
~TaskManager ()
bool addTask (Task *task)
Adds a task to the scheduling queue.
void killCurrentTask ()
Removes the currently running task from the scheduling queue.
CPUState * schedule (CPUState *cpustate)
The core scheduling function called by the timer interrupt.
Static Public Member Functions
static void onTaskExit ()
A static helper function used as the return address for tasks.
Private Attributes
int currentTask
The index of the currently running task in the tasks array.
int numTasks
The current number of active tasks.
Task * tasks [256]
Array of pointers to all active tasks.
Static Private Attributes
static TaskManager * activeTaskManager = nullptr
Global pointer to the active TaskManager instance (used by onTaskExit).
Detailed Description
Manages multitasking and scheduling of tasks.
Implements a simple Round-Robin scheduler to switch between registered tasks.
Definition at line 65 of file kmultitasking.hpp.
Constructor & Destructor Documentation
TaskManager()
TaskManager::TaskManager ()
Initializes the Task Manager.
Definition at line 32 of file kmultitasking.cpp.
{
    numTasks = 0;
    currentTask = -1;
    activeTaskManager = this;
}
References activeTaskManager, currentTask, and numTasks.
~TaskManager()
TaskManager::~TaskManager ()
Definition at line 39 of file kmultitasking.cpp.
{}
Member Function Documentation
addTask()
bool TaskManager::addTask (Task * task)
Adds a task to the scheduling queue.
Calls reset() on the task to prepare its stack.
Parameters
task Pointer to the Task object to add.
Returns
true if the task was added successfully, false if the queue is full or task is already running.
Definition at line 41 of file kmultitasking.cpp.
{
    // Prevent adding the same task object twice
    for(int i = 0; i < numTasks; i++) {
        if(tasks[i] == task) {
            return false; // Task is already running
        }
    }
    task->reset();
    if (numTasks >= 256)
        return false;
    tasks[numTasks++] = task;
    return true;
}
References numTasks, essential::Task::reset(), and tasks.
Referenced by kernelMain(), and KernelShell::process_command().
killCurrentTask()
void TaskManager::killCurrentTask ()
Removes the currently running task from the scheduling queue.
This is typically called when a task finishes execution.
Definition at line 57 of file kmultitasking.cpp.
{
    if (numTasks <= 0) return;
    tasks[currentTask] = tasks[numTasks - 1];
    numTasks--;
    currentTask = -1;
}
References currentTask, numTasks, and tasks.
Referenced by onTaskExit().
onTaskExit()
void TaskManager::onTaskExit () static
A static helper function used as the return address for tasks.
When a task function returns (finishes), the CPU pops this address from the stack. This function effectively calls killCurrentTask() and halts the CPU until the next scheduler tick.
Definition at line 65 of file kmultitasking.cpp.
{
    if (activeTaskManager != nullptr)
        activeTaskManager->killCurrentTask();
    while(true)
        asm("hlt");
}
References activeTaskManager, and killCurrentTask().
Referenced by essential::Task::reset().
schedule()
CPUState * TaskManager::schedule (CPUState * cpustate)
The core scheduling function called by the timer interrupt.
Saves the current task's state (passed in cpustate) and selects the next task to run. Uses a Round-Robin algorithm with a time quantum.
Parameters
cpustate The register state of the task that was just interrupted.
Returns
The register state of the next task to run (which the interrupt handler will restore).
Definition at line 73 of file kmultitasking.cpp.
{
    const int TIME_QUANTUM = 4;
    static int tick_counter = 0;
    if(numTasks <= 0)
        return cpustate;
    if(currentTask >= 0)
        tasks[currentTask]->cpustate = cpustate;
    tick_counter++;
    if (tick_counter < TIME_QUANTUM) {
        return cpustate;
    }
    tick_counter = 0;
    // Round Robin Logic
    if(++currentTask >= numTasks)
        currentTask = 0;
    return tasks[currentTask]->cpustate;
}
References essential::Task::cpustate, currentTask, numTasks, and tasks.
Referenced by hardware_communication::InterruptManager::handleInterrupt().
Member Data Documentation
activeTaskManager
TaskManager * TaskManager::activeTaskManager = nullptr static private
Global pointer to the active TaskManager instance (used by onTaskExit).
Definition at line 77 of file kmultitasking.hpp.
Referenced by TaskManager(), and onTaskExit().
currentTask
int essential::TaskManager::currentTask private
The index of the currently running task in the tasks array.
Definition at line 74 of file kmultitasking.hpp.
Referenced by TaskManager(), killCurrentTask(), and schedule().
numTasks
int essential::TaskManager::numTasks private
The current number of active tasks.
Definition at line 71 of file kmultitasking.hpp.
Referenced by TaskManager(), addTask(), killCurrentTask(), and schedule().
tasks
Task* essential::TaskManager::tasks[256] private
Array of pointers to all active tasks.
Definition at line 68 of file kmultitasking.hpp.
Referenced by addTask(), killCurrentTask(), and schedule().
The documentation for this class was generated from the following files:
kmultitasking.hpp
kmultitasking.cpp