OSOS Dev: kernel.cpp File Reference
kernel.cpp File Reference
#include "kernel.hpp"
Functions
void halt (void *arg)
This is halt for kernelMain.
void kernelMain (multiboot_info_t *mbi, uint32_t magicnumber)
The main entry point for the C++ kernel.
void task_o (void *arg)
task_o for testing multitasking
void task_x (void *arg)
task_x for testing multitasking
Variables
essential::KernelThread task1 & task_o
essential::KernelThread task2 & task_x
Function Documentation
halt()
void halt (void * arg)
This is halt for kernelMain.
Definition at line 27 of file kernel.cpp.
{
    basic::printf("\nHELLO FROM OSOS (`help` to see commands)...\npress Enter to continue... :)");
    (void) arg;
    while (true){asm("hlt");};
    basic::disable_cursor();
    essential::__cxa_finalize(0);
}
References essential::__cxa_finalize(), basic::disable_cursor(), and basic::printf().
Referenced by kernelMain().
kernelMain()
void kernelMain (multiboot_info_t * mbi, uint32_t magicnumber)
The main entry point for the C++ kernel.
Parameters
mbi Pointer to the Multiboot information structure provided by GRUB.
magicnumber The magic number passed by GRUB to verify boot.
Definition at line 39 of file kernel.cpp.
{
    essential::__callConstructors();
    basic::enable_cursor(0,15);
    basic::clearScreen();
    // initiating PMM
    memory::PhysicalMemoryManager::init(mbi);
    // initiating Paging
    memory::PagingManager::init(); // Maps 0-24MB now
    // initiating Heap : Start at 16MB (0x1000000), Size 8MB
    memory::kernel_heap.init((void*)0x1000000, 8 * 1024 * 1024);
    // testing C++ new
    int* arr = new int[10];
    arr[0] = 99;
    basic::printf("Heap Test (new): %d\n", arr[0]);
    delete[] arr;
    // testing C malloc
    void* ptr = malloc(100);
    basic::printf("Heap Test (malloc): 0x%x\n", ptr);
    free(ptr);
    essential::GDT_Manager osos_GDT_Manager;
    osos_GDT_Manager.installTable();
    essential::GDT_Manager::printLoadedTableHeader();
    essential::KernelThreadManager osos_ThreadManager(&osos_GDT_Manager);
    // central kernel shell
    KernelShell shell(&osos_ThreadManager, mbi);
    hardware_communication::InterruptManager osos_InterruptManager(&osos_GDT_Manager, &osos_ThreadManager);
    // object of drivers so that they will handle their corresponding Interrupts
    driver::DriverManager driverManager;
        KeyboardEventHandler_for_kernel keyboardEventHandler_for_kernel(&shell);
        driver::KeyboardDriver keyboard(&osos_InterruptManager,&keyboardEventHandler_for_kernel);
        driverManager.addDriver(&keyboard);
        MouseEventHandler_for_kernel mouseEventHandler_for_kernel;
        driver::MouseDriver mouse(&osos_InterruptManager, &mouseEventHandler_for_kernel);
        driverManager.addDriver(&mouse);
        SerialEventHandler_for_kernel serialEventHandler_for_kernel(&shell);
        driver::SerialDriver serialIO(&osos_InterruptManager, &serialEventHandler_for_kernel);
        driverManager.addDriver(&serialIO);
        hardware_communication::PCI_Controller pciController;
        pciController.selectDrivers(&driverManager, &osos_InterruptManager);
    driverManager.activateAll();
    osos_InterruptManager.installTable();
    hardware_communication::InterruptManager::printLoadedTableHeader();
    essential::KernelThread haltTask(&halt, nullptr);
    osos_ThreadManager.addThread(&haltTask);
    shell.addShellTask(&task1);
    shell.addShellTask(&task2);
    hardware_communication::InterruptManager::activate();
    while (true){asm("hlt");};
    basic::disable_cursor();
    essential::__cxa_finalize(0);
    (void)mbi;
    (void)magicnumber;
}
References essential::__callConstructors(), essential::__cxa_finalize(), hardware_communication::InterruptManager::activate(), driver::DriverManager::activateAll(), driver::DriverManager::addDriver(), KernelShell::addShellTask(), essential::KernelThreadManager::addThread(), basic::clearScreen(), basic::disable_cursor(), basic::enable_cursor(), free(), halt(), memory::PagingManager::init(), memory::PhysicalMemoryManager::init(), memory::HeapManager::init(), essential::GDT_Manager::installTable(), hardware_communication::InterruptManager::installTable(), memory::kernel_heap, malloc(), basic::printf(), essential::GDT_Manager::printLoadedTableHeader(), hardware_communication::InterruptManager::printLoadedTableHeader(), and hardware_communication::PCI_Controller::selectDrivers().
task_o()
void task_o (void * arg)
task_o for testing multitasking
Definition at line 4 of file kernel.cpp.
{
    (void) arg;
    for(int i=0; i<200; i++){
        basic::printf("o");
        for(long long i=0; i<100000; i++){basic::printf("");} //for some short delay
    }
}
References basic::printf().
task_x()
void task_x (void * arg)
task_x for testing multitasking
Definition at line 14 of file kernel.cpp.
{
    (void) arg;
    for(int i=0; i<200; i++){
        basic::printf("x");
        for(long long i=0; i<100000; i++){basic::printf("");} //for some short delay
    }
}
References basic::printf().
Variable Documentation
task_o
essential::KernelThread task1& task_o
Definition at line 23 of file kernel.cpp.
task_x
essential::KernelThread task2& task_x
Definition at line 24 of file kernel.cpp.