OSOS - Documentation: hardware_communication::Port8Bit
hardware_communication::Port8Bit
Represents an 8-bit (byte-sized) I/O port.
#include "kport.hpp"
Public Member Functions
Port8Bit (uint16_t portnumber)
Constructs a new Port8Bit object.
virtual ~Port8Bit () override
Destroys the Port8Bit object.
uint8_t read ()
Reads an 8-bit value from the I/O port.
virtual void write (uint8_t data)
Writes an 8-bit value to the I/O port.
Protected Attributes
uint16_t portnumber
Detailed Description
Represents an 8-bit (byte-sized) I/O port.
Definition at line 19 of file kport.hpp.
Constructor & Destructor Documentation
Port8Bit()
hardware_communication::Port8Bit::Port8Bit (uint16_t portnumber) explicit
Constructs a new Port8Bit object.
Parameters
portnumber The 16-bit address of the I/O port.
Definition at line 15 of file kport.cpp.
:Port(portnumber){}
~Port8Bit()
hardware_communication::Port8Bit::~Port8Bit () override virtual
Destroys the Port8Bit object.
Definition at line 17 of file kport.cpp.
{}
Member Function Documentation
read()
uint8_t hardware_communication::Port8Bit::read ()
Reads an 8-bit value from the I/O port.
Returns
The 8-bit value read from the port.
Definition at line 26 of file kport.cpp.
{
    uint8_t result;
    __asm__ volatile("inb %1, %0" :"=a"(result) : "Nd"(portnumber));
    return result;
}
Referenced by basic::enable_cursor().
write()
void hardware_communication::Port8Bit::write (uint8_t data) virtual
Writes an 8-bit value to the I/O port.
Parameters
data The 8-bit value to write.
Reimplemented in hardware_communication::Port8BitSlow.
Definition at line 21 of file kport.cpp.
{
    __asm__ volatile("outb %0, %1" : : "a"(data), "Nd"(portnumber));
}
Referenced by basic::disable_cursor(), basic::enable_cursor(), and basic::update_cursor().
Member Data Documentation
portnumber
uint16_t hardware_communication::Port::portnumber protected inherited
Definition at line 11 of file kport.hpp.
Referenced by hardware_communication::Port::Port().
The documentation for this class was generated from the following files:
/home/shreekar/Desktop/Building_own_OS/OSOS/libk_header/hardware_communication/kport.hpp
/home/shreekar/Desktop/Building_own_OS/OSOS/libk_src/hardware_communication/kport.cpp