OSOS Dev: driver::RawDataHandler
driver::RawDataHandler
#include "kamd79c973.hpp"
Public Member Functions
RawDataHandler (amd_am79c973 *backend)
~RawDataHandler ()
virtual bool onRawDataReceived (uint8_t *buffer, uint32_t size)
void send (uint8_t *buffer, uint32_t size)
Protected Attributes
amd_am79c973 * backend
Detailed Description
Definition at line 14 of file kamd79c973.hpp.
Constructor & Destructor Documentation
RawDataHandler()
RawDataHandler::RawDataHandler (amd_am79c973 * backend)
Definition at line 9 of file kamd79c973.cpp.
{
    this->backend = backend;
    backend->setHandler(this);
}
References backend, and driver::amd_am79c973::setHandler().
~RawDataHandler()
RawDataHandler::~RawDataHandler ()
Definition at line 15 of file kamd79c973.cpp.
{
    backend->setHandler(0);
}
References backend, and driver::amd_am79c973::setHandler().
Member Function Documentation
onRawDataReceived()
bool RawDataHandler::onRawDataReceived (uint8_t * buffer, uint32_t size) virtual
Reimplemented in net::EtherFrameProvider.
Definition at line 20 of file kamd79c973.cpp.
{
    (void) buffer;
    (void) size;
    return false;
}
References size.
Referenced by driver::amd_am79c973::receive().
send()
void RawDataHandler::send (uint8_t * buffer, uint32_t size)
Definition at line 27 of file kamd79c973.cpp.
{
    backend->send(buffer, size);
}
References backend, driver::amd_am79c973::send(), and size.
Member Data Documentation
backend
amd_am79c973* driver::RawDataHandler::backend protected
Definition at line 17 of file kamd79c973.hpp.
Referenced by RawDataHandler(), ~RawDataHandler(), net::EtherFrameProvider::getIPAddress(), net::EtherFrameProvider::getMACAddress(), net::EtherFrameProvider::onRawDataReceived(), net::EtherFrameProvider::send(), and send().
The documentation for this class was generated from the following files:
kamd79c973.hpp
kamd79c973.cpp