OSOS - Documentation: basic Namespace Reference
basic Namespace Reference
Functions
void __clearScreen ()
Clears the entire text mode screen and resets the cursor to (0,0).
void __printMemoryMap (multiboot_info_t *mbi)
Prints the system memory map provided by the Multiboot bootloader.
void disable_cursor ()
Disables the text mode cursor.
void enable_cursor (uint8_t cursor_start, uint8_t cursor_end)
Enables the text mode cursor and sets its shape.
int printf (const char *format,...)
A custom implementation of the standard printf function for writing to VGA text mode memory.
void update_cursor (int x, int y)
Updates the position of the text mode cursor.
Function Documentation
__clearScreen()
void basic::__clearScreen ()
Clears the entire text mode screen and resets the cursor to (0,0).
Definition at line 128 of file kiostream.cpp.
{
    unsigned short *video_memory = (unsigned short *)0xb8000;
    unsigned short blank = (0x07 << 8) | ' ';
    int screenSize = MAGIC_WIDTH * MAGIC_HEIGHT;
    for (int i = 0; i < screenSize; i++)
    {
        video_memory[i] = blank;
    }
    cursor_x_ = 0;
    cursor_y_ = 0;
}
References cursor_x_, cursor_y_, MAGIC_HEIGHT, and MAGIC_WIDTH.
Referenced by kernelMain().
__printMemoryMap()
void basic::__printMemoryMap (multiboot_info_t * mbi)
Prints the system memory map provided by the Multiboot bootloader.
Parameters
mbi Pointer to the Multiboot information structure.
Definition at line 5 of file kmemory.cpp.
{
    // Check if the memory map flag is set (bit 6)
    if (!(mbi->flags & (1 << 6))) {
        basic::printf("\nError: Memory map not provided by bootloader.\n");
        return;
    }
    basic::printf("\n--- System Memory Map ---\n");
    // Use uint64_t to correctly accumulate total memory size
    uint64_t total_available_bytes = 0;
    // Use uintptr_t for pointer arithmetic to ensure portability
    uintptr_t mmap_start = mbi->mmap_addr;
    uintptr_t mmap_end = mbi->mmap_addr + mbi->mmap_length;
    for (multiboot_memory_map_t *mmap = (multiboot_memory_map_t *)mmap_start;
         (uintptr_t)mmap < mmap_end;
         mmap = (multiboot_memory_map_t *)((uintptr_t)mmap + mmap->size + sizeof(mmap->size)))
    {
        const char *type_str;
        switch (mmap->type)
        {
        case MULTIBOOT_MEMORY_AVAILABLE:
            type_str = "Available";
            total_available_bytes += mmap->len;
            break;
        case MULTIBOOT_MEMORY_RESERVED:
            type_str = "Reserved";
            break;
        case MULTIBOOT_MEMORY_ACPI_RECLAIMABLE:
            type_str = "ACPI Reclaimable";
            break;
        case MULTIBOOT_MEMORY_NVS:
            type_str = "NVS";
            break;
        case MULTIBOOT_MEMORY_BADRAM:
            type_str = "Bad RAM";
            break;
        default:
            type_str = "Unknown";
            break;
        }
        // Use %#llx for 64-bit hex values (address and length)
        basic::printf("Addr: %#llx | Len: %.2fKB | Type: %s\n", mmap->addr, mmap->len/1024.0, type_str);
    }
    // Use floating point for the final calculation and display
    double total_mb = total_available_bytes / 1024.0;
    basic::printf("Total available memory: %.2f KB\n\n", total_mb);
}
References MULTIBOOT_MEMORY_ACPI_RECLAIMABLE, MULTIBOOT_MEMORY_AVAILABLE, MULTIBOOT_MEMORY_BADRAM, MULTIBOOT_MEMORY_NVS, MULTIBOOT_MEMORY_RESERVED, and printf().
disable_cursor()
void basic::disable_cursor ()
Disables the text mode cursor.
Definition at line 42 of file kiostream.cpp.
{
    vgaIndexPort.write(0x0A);
    vgaDataPort.write(0x20);
}
References vgaDataPort, vgaIndexPort, and hardware_communication::Port8Bit::write().
Referenced by kernelMain().
enable_cursor()
void basic::enable_cursor (uint8_t cursor_start, uint8_t cursor_end)
Enables the text mode cursor and sets its shape.
Parameters
cursor_start The starting scanline for the cursor block.
cursor_end The ending scanline for the cursor block.
Definition at line 20 of file kiostream.cpp.
{
    vgaIndexPort.write(0x0A);
    vgaDataPort.write((vgaDataPort.read() & 0xC0) | cursor_start);
    vgaIndexPort.write(0x0B);
    vgaDataPort.write((vgaDataPort.read() & 0xE0) | cursor_end);
}
References hardware_communication::Port8Bit::read(), vgaDataPort, vgaIndexPort, and hardware_communication::Port8Bit::write().
Referenced by kernelMain().
printf()
int basic::printf (const char * format, ...)
A custom implementation of the standard printf function for writing to VGA text mode memory.
This function formats a string and prints it to the screen, handling various format specifiers, flags, width, precision, and length modifiers. It returns the total number of characters written.
Parameters
format The format string.
... Variable arguments corresponding to the format specifiers.
Returns
The total number of characters written to the screen.
Supported Format Specifiers: c - Character s - String d, i - Signed decimal integer u - Unsigned decimal integer f - Floating point number (double) x - Unsigned hexadecimal integer (lowercase) X - Unsigned hexadecimal integer (uppercase) b - Unsigned binary integer o - Unsigned octal integer p - Pointer address %% - A literal '' character
Supported Flags: '#' - Alternative form (e.g., 0x for hex, 0 for octal). '0' - Zero-padding for width.
Supported Width: A number after '' specifies the minimum field width (e.g., %10d).
Supported Precision: A period followed by a number specifies precision (e.g., %.4f, %.8X). For integers, this specifies the minimum number of digits to print.
Supported Length Modifiers: h - short int (for d, i, u, x, X, o, b) hh - signed/unsigned char (for d, i, u, x, X, o, b) l - long int ll - long long int
Definition at line 306 of file kiostream.cpp.
{
    int chars_written = 0;
    va_list args;
    va_start(args, format);
    char buffer[128];
    char char_str[2] = {0, 0};
    for (int i = 0; format[i] != '\0'; i++)
    {
        if (format[i] == '%')
        {
            i++;
            int use_alternative_form = 0;
            int zero_pad = 0;
            int width = 0;
            int precision = -1;
            // 1. Flags
            // A boolean is clearer than using a while loop here
            if (format[i] == '#') {
                use_alternative_form = 1;
                i++;
            }
            if (format[i] == '0') {
                zero_pad = 1;
                i++;
            }
            // 2. Width
            while (format[i] >= '0' && format[i] <= '9') {
                width = width * 10 + (format[i] - '0');
                i++;
            }
            // 3. Precision
            if (format[i] == '.') {
                i++;
                precision = 0;
                while (format[i] >= '0' && format[i] <= '9') {
                    precision = precision * 10 + (format[i] - '0');
                    i++;
                }
                zero_pad = 0;
            }
            // 4. Length Modifiers
            int is_long = 0, is_long_long = 0, is_short = 0, is_char = 0;
            if (format[i] == 'l') {
                is_long = 1; i++;
                if (format[i] == 'l') { is_long_long = 1; is_long = 0; i++; }
            } else if (format[i] == 'h') {
                is_short = 1; i++;
                if (format[i] == 'h') { is_char = 1; is_short = 0; i++; }
            }
            // --- Handle Specifiers ---
            switch (format[i])
            {
                case 'c':
                    char_str[0] = (char)va_arg(args, int);
                    printCharStr(char_str);
                    chars_written++;
                    break;
                case 's':
                {
                    const char *str = va_arg(args, char *);
                    if (!str) {
                        str = "(null)";
                    }
                    int len = 0;
                    while (str[len]) {
                        len++;
                    }
                    printCharStr(str);
                    chars_written += len;
                    break;
                }
                case 'f':
                {
                    doubleToString(va_arg(args, double), buffer, precision);
                    int len = 0;
                    while(buffer[len]) {
                        len++;
                    }
                    printCharStr(buffer);
                    chars_written += len;
                    break;
                }
                case 'd': case 'i': case 'u': case 'x': case 'X': case 'b': case 'o':
                {
                    unsigned long long val;
                    int base = 10;
                    int uppercase = 0;
                    char sign_char = 0;
                    if (format[i] == 'd' || format[i] == 'i') {
                        long long signed_val;
                        if (is_long_long) signed_val = va_arg(args, long long);
                        else if (is_long) signed_val = va_arg(args, long);
                        else if (is_char) signed_val = (signed char)va_arg(args, int);
                        else if (is_short) signed_val = (short)va_arg(args, int);
                        else signed_val = va_arg(args, int);
                        if (signed_val < 0) {
                            sign_char = '-';
                            val = -signed_val;
                        } else {
                            val = signed_val;
                        }
                    } else {
                        if (is_long_long) val = va_arg(args, unsigned long long);
                        else if (is_long) val = va_arg(args, unsigned long);
                        else if (is_char) val = (unsigned char)va_arg(args, unsigned int);
                        else if (is_short) val = (unsigned short)va_arg(args, unsigned int);
                        else val = va_arg(args, unsigned int);
                    }
                    switch(format[i]) {
                        case 'x': base = 16; break;
                        case 'X': base = 16; uppercase = 1; break;
                        case 'b': base = 2; break;
                        case 'o': base = 8; break;
                    }
                    ullToString(val, buffer, base, 0, uppercase);
                    const char* prefix = "";
                    if (use_alternative_form && val != 0) {
                        switch(format[i]) {
                            case 'x': prefix = "0x"; break;
                            case 'X': prefix = "0X"; break;
                            case 'b': prefix = "0b"; break;
                            case 'o': prefix = "0"; break;
                        }
                    }
                    int num_len = 0; while(buffer[num_len]) num_len++;
                    int prefix_len = 0; while(prefix[prefix_len]) prefix_len++;
                    int precision_pads = (precision > num_len) ? (precision - num_len) : 0;
                    int total_len = num_len + (sign_char ? 1 : 0) + prefix_len + precision_pads;
                    int width_pads = (width > total_len) ? (width - total_len) : 0;
                    chars_written += width_pads + total_len;
                    if (!zero_pad && width_pads > 0) {
                        for (int j = 0; j < width_pads; j++) printCharStr(" ");
                    }
                    if (sign_char) {
                        char_str[0] = sign_char; printCharStr(char_str);
                    }
                    if (prefix_len > 0) printCharStr(prefix);
                    if (zero_pad && width_pads > 0) {
                        for (int j = 0; j < width_pads; j++) printCharStr("0");
                    }
                    if (precision_pads > 0) {
                        for (int j = 0; j < precision_pads; j++) printCharStr("0");
                    }
                    printCharStr(buffer);
                    break;
                }
                case 'p':
                {
                    printCharStr("0x");
                    int hex_digits = sizeof(uintptr_t) * 2;
                    printHex((uintptr_t)va_arg(args, void *), hex_digits);
                    chars_written += 2 + hex_digits;
                    break;
                }
                case '%':
                    printCharStr("%");
                    chars_written++;
                    break;
                default:
                    printCharStr("%");
                    char_str[0] = format[i];
                    printCharStr(char_str);
                    chars_written += 2;
                    break;
            }
        }
        else
        {
            char_str[0] = format[i];
            printCharStr(char_str);
            chars_written++;
        }
    }
    va_end(args);
    update_cursor(cursor_x_, cursor_y_);
    return chars_written;
}
References base, cursor_x_, cursor_y_, doubleToString(), len, printCharStr(), printHex(), ullToString(), and update_cursor().
Referenced by __printMemoryMap(), hardware_communication::InterruptManager::activate(), driver::KeyboardDriver::activate(), driver::MouseDriver::activate(), hardware_communication::InterruptManager::deactivate(), hardware_communication::InterruptManager::handleInterrupt(), essential::GDT::installTable(), hardware_communication::InterruptManager::installTable(), kernelMain(), KeyboardEventHandler_for_kernel::onKeyDown(), essential::GDT::printLoadedTable(), hardware_communication::InterruptManager::printLoadedTable(), essential::GDT::printLoadedTableHeader(), and hardware_communication::InterruptManager::printLoadedTableHeader().
update_cursor()
void basic::update_cursor (int x, int y)
Updates the position of the text mode cursor.
Parameters
x The new x-coordinate (column).
y The new y-coordinate (row).
Definition at line 31 of file kiostream.cpp.
{
    cursor_x_=x;
    cursor_y_=y;
    uint16_t pos = y * 80 + x;
    vgaIndexPort.write(0x0F);
    vgaDataPort.write((uint8_t)(pos & 0xFF));
    vgaIndexPort.write(0x0E);
    vgaDataPort.write((uint8_t)((pos >> 8) & 0xFF));
}
References cursor_x_, cursor_y_, vgaDataPort, vgaIndexPort, and hardware_communication::Port8Bit::write().
Referenced by MouseEventHandler_for_kernel::onMouseDown(), and printf().